// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavusans/dejavusans.12.font

package dejavusans12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 126 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 12, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 48 bytes
	},
}

// Xfe00 font data, 5353 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 995, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 285,
		Pix:    pixXfe00, // 4275 bytes
	},
}

// Xfb00 font data, 5653 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1120, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 305,
		Pix:    pixXfb00, // 4575 bytes
	},
}

// Xf6c5 font data, 1100 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixXf6c5, // 22 bytes
	},
}

// Xf001 font data, 1168 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 21, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 9,
		Pix:    pixXf001, // 90 bytes
	},
}

// Xef00 font data, 1398 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 94, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 32,
		Pix:    pixXef00, // 320 bytes
	},
}

// Xa746 font data, 2023 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 240, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 63,
		Pix:    pixXa746, // 945 bytes
	},
}

// Xa644 font data, 3002 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 561, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 148,
		Pix:    pixXa644, // 1924 bytes
	},
}

// X4dc0 font data, 2806 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 576, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 144,
		Pix:    pixX4dc0, // 1728 bytes
	},
}

// X2d61 font data, 1270 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 59, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 16,
		Pix:    pixX2d61, // 192 bytes
	},
}

// X2c60 font data, 2898 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 545, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 140,
		Pix:    pixX2c60, // 1820 bytes
	},
}

// X2a7d font data, 3483 bytes, orgbpp: 8
var X2a7d = font9.Variable{
	Info: infoX2a7d, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 719, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 185,
		Pix:    pixX2a7d, // 2405 bytes
	},
}

// X2940 font data, 2100 bytes, orgbpp: 8
var X2940 = font9.Variable{
	Info: infoX2940, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 272, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 73,
		Pix:    pixX2940, // 1022 bytes
	},
}

// X2814 font data, 4546 bytes, orgbpp: 8
var X2814 = font9.Variable{
	Info: infoX2814, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1152, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 289,
		Pix:    pixX2814, // 3468 bytes
	},
}

// X2713 font data, 7336 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1616, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 447,
		Pix:    pixX2713, // 6258 bytes
	},
}

// X2612 font data, 7048 bytes, orgbpp: 8
var X2612 = font9.Variable{
	Info: infoX2612, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1492, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 398,
		Pix:    pixX2612, // 5970 bytes
	},
}

// X2523 font data, 8521 bytes, orgbpp: 8
var X2523 = font9.Variable{
	Info: infoX2523, // 958 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1831, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX2523, // 7515 bytes
	},
}

// X2422 font data, 2263 bytes, orgbpp: 8
var X2422 = font9.Variable{
	Info: infoX2422, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 284, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 79,
		Pix:    pixX2422, // 1185 bytes
	},
}

// X22f8 font data, 2968 bytes, orgbpp: 8
var X22f8 = font9.Variable{
	Info: infoX22f8, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 463, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 126,
		Pix:    pixX22f8, // 1890 bytes
	},
}

// X21fc font data, 8086 bytes, orgbpp: 8
var X21fc = font9.Variable{
	Info: infoX21fc, // 1010 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1948, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX21fc, // 7028 bytes
	},
}

// X2104 font data, 8557 bytes, orgbpp: 8
var X2104 = font9.Variable{
	Info: infoX2104, // 994 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1906, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX2104, // 7515 bytes
	},
}

// X2003 font data, 4228 bytes, orgbpp: 8
var X2003 = font9.Variable{
	Info: infoX2003, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 836, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 225,
		Pix:    pixX2003, // 3150 bytes
	},
}

// X1f02 font data, 7453 bytes, orgbpp: 8
var X1f02 = font9.Variable{
	Info: infoX1f02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1697, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 425,
		Pix:    pixX1f02, // 6375 bytes
	},
}

// X1e01 font data, 7378 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1443, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 420,
		Pix:    pixX1e01, // 6300 bytes
	},
}

// X1d00 font data, 3717 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 727, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 203,
		Pix:    pixX1d00, // 2639 bytes
	},
}

// X1502 font data, 5488 bytes, orgbpp: 8
var X1502 = font9.Variable{
	Info: infoX1502, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1166, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 315,
		Pix:    pixX1502, // 4410 bytes
	},
}

// X1401 font data, 6545 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1905, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 497,
		Pix:    pixX1401, // 5467 bytes
	},
}

// X10a0 font data, 3067 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 582, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 153,
		Pix:    pixX10a0, // 1989 bytes
	},
}

// X0e3f font data, 2674 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 431, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 114,
		Pix:    pixX0e3f, // 1596 bytes
	},
}

// X07c0 font data, 1906 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 271, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 69,
		Pix:    pixX07c0, // 828 bytes
	},
}

// X0606 font data, 5758 bytes, orgbpp: 8
var X0606 = font9.Variable{
	Info: infoX0606, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1102, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 312,
		Pix:    pixX0606, // 4680 bytes
	},
}

// X0505 font data, 5012 bytes, orgbpp: 8
var X0505 = font9.Variable{
	Info: infoX0505, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1082, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 281,
		Pix:    pixX0505, // 3934 bytes
	},
}

// X0404 font data, 8248 bytes, orgbpp: 8
var X0404 = font9.Variable{
	Info: infoX0404, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1853, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 478,
		Pix:    pixX0404, // 7170 bytes
	},
}

// X03c0 font data, 56 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   7,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX03c0, // 12 bytes
	},
}

// X03a9 font data, 62 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   9,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX03a9, // 18 bytes
	},
}

// X0303 font data, 5803 bytes, orgbpp: 8
var X0303 = font9.Variable{
	Info: infoX0303, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1218, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 315,
		Pix:    pixX0303, // 4725 bytes
	},
}

// X0202 font data, 6118 bytes, orgbpp: 8
var X0202 = font9.Variable{
	Info: infoX0202, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1296, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 336,
		Pix:    pixX0202, // 5040 bytes
	},
}

// X0101 font data, 7408 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1635, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 422,
		Pix:    pixX0101, // 6330 bytes
	},
}

// X00a0 font data, 2939 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 561, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 167,
		Pix:    pixX00a0, // 2505 bytes
	},
}

// X0020 font data, 2458 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 519, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 156,
		Pix:    pixX0020, // 2028 bytes
	},
}

// X0000 font data, 66 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   7,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 6, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 22 bytes
	},
}
