// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusans/dejavusans.16.font

package dejavusans16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 367 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 17, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 17,
		Pix:    pixXfff9, // 289 bytes
	},
}

// Xfe00 font data, 29718 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1422, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1432,
		Pix:    pixXfe00, // 28640 bytes
	},
}

// Xfb00 font data, 31678 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1530, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1530,
		Pix:    pixXfb00, // 30600 bytes
	},
}

// Xf6c5 font data, 1204 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixXf6c5, // 126 bytes
	},
}

// Xf001 font data, 1663 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 27, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 45,
		Pix:    pixXf001, // 585 bytes
	},
}

// Xef00 font data, 3080 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 137, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 143,
		Pix:    pixXef00, // 2002 bytes
	},
}

// Xa746 font data, 7500 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 338, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 338,
		Pix:    pixXa746, // 6422 bytes
	},
}

// Xa644 font data, 14525 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 791, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 791,
		Pix:    pixXa644, // 13447 bytes
	},
}

// X4dc0 font data, 13558 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 832, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 832,
		Pix:    pixX4dc0, // 12480 bytes
	},
}

// X2d61 font data, 2422 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 84, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 84,
		Pix:    pixX2d61, // 1344 bytes
	},
}

// X2c60 font data, 14632 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 753, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 753,
		Pix:    pixX2c60, // 13554 bytes
	},
}

// X1e01 font data, 41038 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 910 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1741, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2004,
		Pix:    pixX1e01, // 40080 bytes
	},
}

// X1d00 font data, 18571 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1029, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1029,
		Pix:    pixX1d00, // 17493 bytes
	},
}

// X1401 font data, 30884 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 806 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1947, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX1401, // 30030 bytes
	},
}

// X10a0 font data, 14440 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 785, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 786,
		Pix:    pixX10a0, // 13362 bytes
	},
}

// X0e3f font data, 12516 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 582, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 602,
		Pix:    pixX0e3f, // 11438 bytes
	},
}

// X07c0 font data, 6388 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 349, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 354,
		Pix:    pixX07c0, // 5310 bytes
	},
}

// X03c0 font data, 124 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixX03c0, // 80 bytes
	},
}

// X03a9 font data, 200 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 13,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 13,
		Pix:    pixX03a9, // 156 bytes
	},
}

// X0101 font data, 41078 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 930 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1968, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX0101, // 40100 bytes
	},
}

// X0020 font data, 14013 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 704, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 799,
		Pix:    pixX0020, // 13583 bytes
	},
}

// X0000 font data, 156 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixX0000, // 112 bytes
	},
}
