// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusans/dejavusans.16.font

package dejavusans16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 163 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 16, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 85 bytes
	},
}

// Xfe00 font data, 8238 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1308, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 358,
		Pix:    pixXfe00, // 7160 bytes
	},
}

// Xfb00 font data, 8738 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1450, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 383,
		Pix:    pixXfb00, // 7660 bytes
	},
}

// Xf6c5 font data, 1120 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 8, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf6c5, // 42 bytes
	},
}

// Xf001 font data, 1234 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 27, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixXf001, // 156 bytes
	},
}

// Xef00 font data, 1582 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 125, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 36,
		Pix:    pixXef00, // 504 bytes
	},
}

// Xa746 font data, 2693 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 316, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 85,
		Pix:    pixXa746, // 1615 bytes
	},
}

// Xa644 font data, 4444 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 743, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 198,
		Pix:    pixXa644, // 3366 bytes
	},
}

// X4dc0 font data, 4198 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 208,
		Pix:    pixX4dc0, // 3120 bytes
	},
}

// X2d61 font data, 1414 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 84, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 21,
		Pix:    pixX2d61, // 336 bytes
	},
}

// X2c60 font data, 4480 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 732, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 189,
		Pix:    pixX2c60, // 3402 bytes
	},
}

// X1e01 font data, 10978 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 910 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1709, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1e01, // 10020 bytes
	},
}

// X1d00 font data, 5464 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 953, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 258,
		Pix:    pixX1d00, // 4386 bytes
	},
}

// X1401 font data, 8369 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 806 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1890, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1401, // 7515 bytes
	},
}

// X10a0 font data, 4427 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 731, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 197,
		Pix:    pixX10a0, // 3349 bytes
	},
}

// X0e3f font data, 3947 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 564, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 151,
		Pix:    pixX0e3f, // 2869 bytes
	},
}

// X07c0 font data, 2413 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 343, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 89,
		Pix:    pixX07c0, // 1335 bytes
	},
}

// X03c0 font data, 68 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 24 bytes
	},
}

// X03a9 font data, 80 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   12,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03a9, // 36 bytes
	},
}

// X0101 font data, 11018 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 930 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1954, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 10040 bytes
	},
}

// X0020 font data, 3830 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 694, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 200,
		Pix:    pixX0020, // 3400 bytes
	},
}

// X0000 font data, 72 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 28 bytes
	},
}
