// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavubd/dejavubd.18.font

package dejavubd18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 478 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 20, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 20,
		Pix:    pixXfff9, // 400 bytes
	},
}

// Xfb00 font data, 2683 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 107, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 107,
		Pix:    pixXfb00, // 1605 bytes
	},
}

// Xf6c5 font data, 1520 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 26, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 26,
		Pix:    pixXf6c5, // 442 bytes
	},
}

// Xf400 font data, 12145 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 527, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 527,
		Pix:    pixXf400, // 11067 bytes
	},
}

// Xa746 font data, 9966 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 404, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 404,
		Pix:    pixXa746, // 8888 bytes
	},
}

// Xa644 font data, 14340 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 697, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 698,
		Pix:    pixXa644, // 13262 bytes
	},
}

// X2e18 font data, 1809 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 43, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 43,
		Pix:    pixX2e18, // 731 bytes
	},
}

// X2c60 font data, 16630 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 864, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 864,
		Pix:    pixX2c60, // 15552 bytes
	},
}

// X2b00 font data, 7147 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 357, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 357,
		Pix:    pixX2b00, // 6069 bytes
	},
}

// X28a2 font data, 38844 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 758 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 2002, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX28a2, // 38038 bytes
	},
}

// X27a1 font data, 35298 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1711, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1711,
		Pix:    pixX27a1, // 34220 bytes
	},
}

// X2580 font data, 41050 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 962 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1982, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX2580, // 40040 bytes
	},
}

// X2423 font data, 1169 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -2},
			Max: image.Point{X: 13, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 13,
		Pix:    pixX2423, // 91 bytes
	},
}

// X1e01 font data, 46905 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 650 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1857, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX1e01, // 46207 bytes
	},
}

// X1d00 font data, 30538 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1472, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1473,
		Pix:    pixX1d00, // 29460 bytes
	},
}

// X10a0 font data, 24577 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1118, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1119,
		Pix:    pixX10a0, // 23499 bytes
	},
}

// X0101 font data, 46871 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 662 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1984, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2007,
		Pix:    pixX0101, // 46161 bytes
	},
}

// X0000 font data, 43267 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 2007, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX0000, // 42189 bytes
	},
}
