// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/anonpro/anonpro.16.font

package anonpro16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1258 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 18, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 18,
		Pix:    pixXfb01, // 180 bytes
	},
}

// Xf8ff font data, 1287 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 19, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 19,
		Pix:    pixXf8ff, // 209 bytes
	},
}

// Xf6c3 font data, 1084 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 1},
			Max: image.Point{X: 3, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 3,
		Pix:    pixXf6c3, // 6 bytes
	},
}

// Xe000 font data, 1870 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 72, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 72,
		Pix:    pixXe000, // 792 bytes
	},
}

// X2713 font data, 1141 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 9, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX2713, // 63 bytes
	},
}

// X2500 font data, 5990 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 307, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 307,
		Pix:    pixX2500, // 4912 bytes
	},
}

// X2324 font data, 1760 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 61, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 62,
		Pix:    pixX2324, // 682 bytes
	},
}

// X221a font data, 2113 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 69, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 69,
		Pix:    pixX221a, // 1035 bytes
	},
}

// X2116 font data, 1718 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 64, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 64,
		Pix:    pixX2116, // 640 bytes
	},
}

// X2013 font data, 2534 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 112, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 112,
		Pix:    pixX2013, // 1456 bytes
	},
}

// X1e02 font data, 3942 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 178, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 179,
		Pix:    pixX1e02, // 2864 bytes
	},
}

// X0490 font data, 1270 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixX0490, // 192 bytes
	},
}

// X0384 font data, 21254 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1257, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1261,
		Pix:    pixX0384, // 20176 bytes
	},
}

// X0218 font data, 2058 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 70, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 70,
		Pix:    pixX0218, // 980 bytes
	},
}

// X0101 font data, 16902 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 980, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 989,
		Pix:    pixX0101, // 15824 bytes
	},
}

// X0000 font data, 22678 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1344, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1350,
		Pix:    pixX0000, // 21600 bytes
	},
}
