// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavu/dejavu.16.font

package dejavu16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 367 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 17, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 17,
		Pix:    pixXfff9, // 289 bytes
	},
}

// Xfb00 font data, 2268 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 85, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 85,
		Pix:    pixXfb00, // 1190 bytes
	},
}

// Xf6c5 font data, 1338 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 20, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 20,
		Pix:    pixXf6c5, // 260 bytes
	},
}

// Xf400 font data, 9214 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 451, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 452,
		Pix:    pixXf400, // 8136 bytes
	},
}

// Xa746 font data, 7139 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 319, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 319,
		Pix:    pixXa746, // 6061 bytes
	},
}

// Xa644 font data, 10734 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 566, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 568,
		Pix:    pixXa644, // 9656 bytes
	},
}

// X2e18 font data, 1590 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 32, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 32,
		Pix:    pixX2e18, // 512 bytes
	},
}

// X2c60 font data, 13488 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 718, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 730,
		Pix:    pixX2c60, // 12410 bytes
	},
}

// X2b00 font data, 5516 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 317, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 317,
		Pix:    pixX2b00, // 4438 bytes
	},
}

// X28a2 font data, 34905 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 806 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 2003, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2003,
		Pix:    pixX28a2, // 34051 bytes
	},
}

// X27a1 font data, 29519 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1673, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1673,
		Pix:    pixX27a1, // 28441 bytes
	},
}

// X1e01 font data, 41018 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 850 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1707, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2006,
		Pix:    pixX1e01, // 40120 bytes
	},
}

// X1d00 font data, 21036 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1173, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1174,
		Pix:    pixX1d00, // 19958 bytes
	},
}

// X10a0 font data, 18034 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 942, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 942,
		Pix:    pixX10a0, // 16956 bytes
	},
}

// X0101 font data, 38901 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 834 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1989, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2001,
		Pix:    pixX0101, // 38019 bytes
	},
}

// X0000 font data, 31288 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1590, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1590,
		Pix:    pixX0000, // 30210 bytes
	},
}
