// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavusansbi/dejavusansbi.18.font

package dejavusansbi18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 178 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 19, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 100 bytes
	},
}

// Xfe00 font data, 1114 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 29, Y: -13},
		},
		LogN:   1, // 2 bpp
		Stride: 9,
		Pix:    pixXfe00, // 36 bytes
	},
}

// Xfb00 font data, 5098 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 739, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 201,
		Pix:    pixXfb00, // 4020 bytes
	},
}

// Xf5c5 font data, 1123 bytes, orgbpp: 8
var Xf5c5 = font9.Variable{
	Info: infoXf5c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 12, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf5c5, // 45 bytes
	},
}

// Xef00 font data, 1680 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 153, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 43,
		Pix:    pixXef00, // 602 bytes
	},
}

// Xa746 font data, 3619 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 458, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 121,
		Pix:    pixXa746, // 2541 bytes
	},
}

// Xa644 font data, 5974 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1030, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 272,
		Pix:    pixXa644, // 4896 bytes
	},
}

// X4dc0 font data, 4662 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX4dc0, // 3584 bytes
	},
}

// X2e18 font data, 1299 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 45, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX2e18, // 221 bytes
	},
}

// X2c60 font data, 3178 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 383, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 105,
		Pix:    pixX2c60, // 2100 bytes
	},
}

// X2580 font data, 11724 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 610 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1930, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2580, // 11066 bytes
	},
}

// X1e01 font data, 12259 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 642 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1875, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1e01, // 11569 bytes
	},
}

// X1d00 font data, 8298 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1320, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 361,
		Pix:    pixX1d00, // 7220 bytes
	},
}

// X1401 font data, 9158 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 542 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1846, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 504,
		Pix:    pixX1401, // 8568 bytes
	},
}

// X10a0 font data, 5866 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 953, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 252,
		Pix:    pixX10a0, // 4788 bytes
	},
}

// X0e3f font data, 6460 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 857, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 234,
		Pix:    pixX0e3f, // 5382 bytes
	},
}

// X03c0 font data, 74 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 12,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 30 bytes
	},
}

// X03a9 font data, 96 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   14,
	Width: 14,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixX03a9, // 52 bytes
	},
}

// X00a0 font data, 6545 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1047, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 291,
		Pix:    pixX00a0, // 6111 bytes
	},
}

// X0020 font data, 5470 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1007, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 280,
		Pix:    pixX0020, // 5040 bytes
	},
}

// X0000 font data, 92 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0000, // 48 bytes
	},
}
