// DO NOT EDIT
// Generated by: go run 9font.go -n bit/anonpro/anonpro.11.font

package anonpro11

import (
	"image"

	"github.com/embeddedgo/display/pixdisp"
	"github.com/embeddedgo/display/pixdisp/font/font9"
)

// Xfb01 font data, 1099 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXfb01, // 21 bytes
	},
}

// Xf8ff font data, 1102 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf8ff, // 24 bytes
	},
}

// Xf6c3 font data, 1080 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 1, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 1,
		Pix:    pixXf6c3, // 2 bytes
	},
}

// Xe000 font data, 1174 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 45, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixXe000, // 96 bytes
	},
}

// X2713 font data, 1088 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -4},
			Max: image.Point{X: 6, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX2713, // 10 bytes
	},
}

// X2500 font data, 1578 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 178, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 50,
		Pix:    pixX2500, // 500 bytes
	},
}

// X2324 font data, 1166 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 38, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 11,
		Pix:    pixX2324, // 88 bytes
	},
}

// X221a font data, 1198 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 42, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixX221a, // 120 bytes
	},
}

// X2116 font data, 1166 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 42, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 11,
		Pix:    pixX2116, // 88 bytes
	},
}

// X2013 font data, 1258 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 72, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 20,
		Pix:    pixX2013, // 180 bytes
	},
}

// X1e02 font data, 1388 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 109, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 31,
		Pix:    pixX1e02, // 310 bytes
	},
}

// X0490 font data, 1102 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0490, // 24 bytes
	},
}

// X0384 font data, 3388 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 798, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 210,
		Pix:    pixX0384, // 2310 bytes
	},
}

// X0218 font data, 1208 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 43, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX0218, // 130 bytes
	},
}

// X0101 font data, 2758 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 646, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 168,
		Pix:    pixX0101, // 1680 bytes
	},
}

// X0000 font data, 3378 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 862, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 230,
		Pix:    pixX0000, // 2300 bytes
	},
}
