// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansbi/dejavusansbi.14.font

package dejavusansbi14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 318 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 16, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixXfff9, // 240 bytes
	},
}

// Xfe00 font data, 1156 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 25, Y: -10},
		},
		LogN:   3, // 8 bpp
		Stride: 26,
		Pix:    pixXfe00, // 78 bytes
	},
}

// Xfb00 font data, 10408 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 615, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 622,
		Pix:    pixXfb00, // 9330 bytes
	},
}

// Xf5c5 font data, 1198 bytes, orgbpp: 8
var Xf5c5 = font9.Variable{
	Info: infoXf5c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixXf5c5, // 120 bytes
	},
}

// Xef00 font data, 2488 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 133, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 141,
		Pix:    pixXef00, // 1410 bytes
	},
}

// Xa746 font data, 7623 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 378, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 385,
		Pix:    pixXa746, // 6545 bytes
	},
}

// Xa644 font data, 13888 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 843, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 854,
		Pix:    pixXa644, // 12810 bytes
	},
}

// X4dc0 font data, 10934 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 704, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 704,
		Pix:    pixX4dc0, // 9856 bytes
	},
}

// X2e18 font data, 1598 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 40, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 40,
		Pix:    pixX2e18, // 520 bytes
	},
}

// X2c60 font data, 6294 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 324, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 326,
		Pix:    pixX2c60, // 5216 bytes
	},
}

// X2a84 font data, 14214 bytes, orgbpp: 8
var X2a84 = font9.Variable{
	Info: infoX2a84, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 815, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 821,
		Pix:    pixX2a84, // 13136 bytes
	},
}

// X2983 font data, 8167 bytes, orgbpp: 8
var X2983 = font9.Variable{
	Info: infoX2983, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 416, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 417,
		Pix:    pixX2983, // 7089 bytes
	},
}

// X2580 font data, 36988 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 778 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2006, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX2580, // 36162 bytes
	},
}

// X1e01 font data, 36942 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 822 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1726, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2004,
		Pix:    pixX1e01, // 36072 bytes
	},
}

// X1d00 font data, 19334 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1124, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1141,
		Pix:    pixX1d00, // 18256 bytes
	},
}

// X1401 font data, 30772 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 694 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1922, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX1401, // 30030 bytes
	},
}

// X10a0 font data, 13108 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 798, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 802,
		Pix:    pixX10a0, // 12030 bytes
	},
}

// X0e3f font data, 14434 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 713, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 742,
		Pix:    pixX0e3f, // 13356 bytes
	},
}

// X03c0 font data, 107 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 9, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX03c0, // 63 bytes
	},
}

// X03a9 font data, 154 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixX03a9, // 110 bytes
	},
}

// X0101 font data, 37030 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 802 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1991, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2010,
		Pix:    pixX0101, // 36180 bytes
	},
}

// X00a0 font data, 16176 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 826, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 926,
		Pix:    pixX00a0, // 15742 bytes
	},
}

// X0020 font data, 13855 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 796, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 895,
		Pix:    pixX0020, // 13425 bytes
	},
}

// X0000 font data, 128 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 7,
		Pix:    pixX0000, // 84 bytes
	},
}
