// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansbd/dejavusansbd.14.font

package dejavusansbd14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 318 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 16, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixXfff9, // 240 bytes
	},
}

// Xfe00 font data, 28060 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1491, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1499,
		Pix:    pixXfe00, // 26982 bytes
	},
}

// Xfb00 font data, 29680 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1579, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1589,
		Pix:    pixXfb00, // 28602 bytes
	},
}

// Xf6c5 font data, 1198 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 9, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixXf6c5, // 120 bytes
	},
}

// Xef00 font data, 2418 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 134, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 134,
		Pix:    pixXef00, // 1340 bytes
	},
}

// Xa746 font data, 6909 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 343, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 343,
		Pix:    pixXa746, // 5831 bytes
	},
}

// Xa644 font data, 12628 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 768, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 770,
		Pix:    pixXa644, // 11550 bytes
	},
}

// X4dc0 font data, 10934 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 704, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 704,
		Pix:    pixX4dc0, // 9856 bytes
	},
}

// X2d61 font data, 2365 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 99, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 99,
		Pix:    pixX2d61, // 1287 bytes
	},
}

// X2c60 font data, 13398 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 770,
		Pix:    pixX2c60, // 12320 bytes
	},
}

// X2a84 font data, 14214 bytes, orgbpp: 8
var X2a84 = font9.Variable{
	Info: infoX2a84, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 815, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 821,
		Pix:    pixX2a84, // 13136 bytes
	},
}

// X2983 font data, 8116 bytes, orgbpp: 8
var X2983 = font9.Variable{
	Info: infoX2983, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 413, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 414,
		Pix:    pixX2983, // 7038 bytes
	},
}

// X2580 font data, 36988 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 778 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2006, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX2580, // 36162 bytes
	},
}

// X1e01 font data, 37130 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 938 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1701, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2008,
		Pix:    pixX1e01, // 36144 bytes
	},
}

// X1d00 font data, 18150 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1065, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1067,
		Pix:    pixX1d00, // 17072 bytes
	},
}

// X1401 font data, 30925 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 742 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1951, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX1401, // 30135 bytes
	},
}

// X10a0 font data, 12718 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 776, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 776,
		Pix:    pixX10a0, // 11640 bytes
	},
}

// X0e3f font data, 13264 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 676, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 677,
		Pix:    pixX0e3f, // 12186 bytes
	},
}

// X07c0 font data, 7243 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 409, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 411,
		Pix:    pixX07c0, // 6165 bytes
	},
}

// X03c0 font data, 107 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 9, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX03c0, // 63 bytes
	},
}

// X03a9 font data, 154 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixX03a9, // 110 bytes
	},
}

// X0101 font data, 37050 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 930 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1977, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2004,
		Pix:    pixX0101, // 36072 bytes
	},
}

// X00a0 font data, 14612 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 736, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 834,
		Pix:    pixX00a0, // 14178 bytes
	},
}

// X0020 font data, 12235 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 692, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 787,
		Pix:    pixX0020, // 11805 bytes
	},
}

// X0000 font data, 128 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 7,
		Pix:    pixX0000, // 84 bytes
	},
}
