// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavubi/dejavubi.12.font

package dejavubi12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 274 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixXfff9, // 196 bytes
	},
}

// Xfb00 font data, 2196 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 86, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 86,
		Pix:    pixXfb00, // 1118 bytes
	},
}

// Xf6c4 font data, 1780 bytes, orgbpp: 8
var Xf6c4 = font9.Variable{
	Info: infoXf6c4, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 54, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 54,
		Pix:    pixXf6c4, // 702 bytes
	},
}

// Xf400 font data, 6958 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 401, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 420,
		Pix:    pixXf400, // 5880 bytes
	},
}

// Xa746 font data, 5518 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 292, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 296,
		Pix:    pixXa746, // 4440 bytes
	},
}

// Xa644 font data, 7617 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 497, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 503,
		Pix:    pixXa644, // 6539 bytes
	},
}

// X2e18 font data, 1463 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 33, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 35,
		Pix:    pixX2e18, // 385 bytes
	},
}

// X2c60 font data, 9437 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 636, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 643,
		Pix:    pixX2c60, // 8359 bytes
	},
}

// X2b00 font data, 3663 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 235, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 235,
		Pix:    pixX2b00, // 2585 bytes
	},
}

// X29eb font data, 1715 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 49, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 49,
		Pix:    pixX29eb, // 637 bytes
	},
}

// X28a2 font data, 23438 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1719, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1720,
		Pix:    pixX28a2, // 22360 bytes
	},
}

// X27a1 font data, 18095 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1308, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1309,
		Pix:    pixX27a1, // 17017 bytes
	},
}

// X2580 font data, 18407 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1331, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1333,
		Pix:    pixX2580, // 17329 bytes
	},
}

// X1e01 font data, 31017 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 834 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1637, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX1e01, // 30135 bytes
	},
}

// X1d00 font data, 16562 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1088, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1106,
		Pix:    pixX1d00, // 15484 bytes
	},
}

// X10a0 font data, 12390 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 802, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 808,
		Pix:    pixX10a0, // 11312 bytes
	},
}

// X0101 font data, 30979 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 826 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1978, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2007,
		Pix:    pixX0101, // 30105 bytes
	},
}

// X0000 font data, 25303 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1599, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1615,
		Pix:    pixX0000, // 24225 bytes
	},
}
