// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavubd/dejavubd.14.font

package dejavubd14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 142 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 15, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 64 bytes
	},
}

// Xfb00 font data, 1330 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 81, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 21,
		Pix:    pixXfb00, // 252 bytes
	},
}

// Xf6c5 font data, 1143 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 19, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXf6c5, // 65 bytes
	},
}

// Xf400 font data, 2982 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 393, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 112,
		Pix:    pixXf400, // 1904 bytes
	},
}

// Xa746 font data, 2421 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 301, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 79,
		Pix:    pixXa746, // 1343 bytes
	},
}

// Xa644 font data, 3133 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 516, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 137,
		Pix:    pixXa644, // 2055 bytes
	},
}

// X2e18 font data, 1195 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 33, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 9,
		Pix:    pixX2e18, // 117 bytes
	},
}

// X2c60 font data, 3658 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 645, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 172,
		Pix:    pixX2c60, // 2580 bytes
	},
}

// X2b00 font data, 1962 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 262, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 68,
		Pix:    pixX2b00, // 884 bytes
	},
}

// X29eb font data, 1318 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 55, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 15,
		Pix:    pixX29eb, // 240 bytes
	},
}

// X28a2 font data, 8278 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1785, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 480,
		Pix:    pixX28a2, // 7200 bytes
	},
}

// X27a1 font data, 6422 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1321, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 334,
		Pix:    pixX27a1, // 5344 bytes
	},
}

// X2580 font data, 7366 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1501, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 393,
		Pix:    pixX2580, // 6288 bytes
	},
}

// X1e01 font data, 9946 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 862 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1864, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX1e01, // 9036 bytes
	},
}

// X1d00 font data, 5750 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1036, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 292,
		Pix:    pixX1d00, // 4672 bytes
	},
}

// X10a0 font data, 4886 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 819, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX10a0, // 3808 bytes
	},
}

// X0101 font data, 9926 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 842 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1954, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 9036 bytes
	},
}

// X0000 font data, 7270 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1538, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 387,
		Pix:    pixX0000, // 6192 bytes
	},
}
