// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/anonpro/anonpro.13.font

package anonpro13

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1190 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixXfb01, // 112 bytes
	},
}

// Xf8ff font data, 1222 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixXf8ff, // 144 bytes
	},
}

// Xf6c3 font data, 1084 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 3, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 3,
		Pix:    pixXf6c3, // 6 bytes
	},
}

// Xe000 font data, 1564 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 54, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 54,
		Pix:    pixXe000, // 486 bytes
	},
}

// X2713 font data, 1120 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -5},
			Max: image.Point{X: 7, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 7,
		Pix:    pixX2713, // 42 bytes
	},
}

// X2500 font data, 3958 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 216, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 240,
		Pix:    pixX2500, // 2880 bytes
	},
}

// X2324 font data, 1478 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 50, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 50,
		Pix:    pixX2324, // 400 bytes
	},
}

// X221a font data, 1750 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 54, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 56,
		Pix:    pixX221a, // 672 bytes
	},
}

// X2116 font data, 1546 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 52, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 52,
		Pix:    pixX2116, // 468 bytes
	},
}

// X2013 font data, 2090 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 92, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 92,
		Pix:    pixX2013, // 1012 bytes
	},
}

// X1e02 font data, 2758 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 140, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 140,
		Pix:    pixX1e02, // 1680 bytes
	},
}

// X0490 font data, 1198 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixX0490, // 120 bytes
	},
}

// X0384 font data, 13519 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 950, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 957,
		Pix:    pixX0384, // 12441 bytes
	},
}

// X0218 font data, 1683 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 55, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 55,
		Pix:    pixX0218, // 605 bytes
	},
}

// X0101 font data, 10198 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 750, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 760,
		Pix:    pixX0101, // 9120 bytes
	},
}

// X0000 font data, 14559 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1026, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1037,
		Pix:    pixX0000, // 13481 bytes
	},
}
