// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavu/dejavu.12.font

package dejavu12

import "github.com/embeddedgo/display/pix/fonts"

const (
	Height = 15
	Ascent = 12
)

// Xfff9_ffff subfont, n=7, ￼�
var Xfff9_ffff = fonts.Subfont{
	First:  0xfff9,
	Last:   0xffff,
	Offset: 0,
	Data:   &Xfff9,
}

// Xfb00_fc00 subfont, n=257, ﬀﬁﬂﬃﬄﬅﬆﬓﬔﬕﬖﬗיִﬞײַﬠﬡﬢﬣﬤﬥﬦﬧﬨ﬩שׁשׂשּׁשּׂאַאָאּבּגּדּהּוּזּטּיּךּכּלּמּנּסּףּפּ
var Xfb00_fc00 = fonts.Subfont{
	First:  0xfb00, // 'ﬀ'
	Last:   0xfc00, // 'ﰀ'
	Offset: 0,
	Data:   &Xfb00,
}

// Xf6c5_f7c5 subfont, n=257, 
var Xf6c5_f7c5 = fonts.Subfont{
	First:  0xf6c5,
	Last:   0xf7c5,
	Offset: 0,
	Data:   &Xf6c5,
}

// Xf400_f500 subfont, n=257, 
var Xf400_f500 = fonts.Subfont{
	First:  0xf400,
	Last:   0xf500,
	Offset: 0,
	Data:   &Xf400,
}

// Xa746_a846 subfont, n=257, ꝆꝇꝈꝉꝊꝋꝌꝍꝎꝏꝐꝑꝒꝓꝔꝕꝖꝗꝘꝙꝚꝛꝜꝝꝞꝟꝠꝡꝢꝣꝤꝥꝦꝧꝨꝩꝪꝫꝬꝭꝮꝯꝰꝱꝲꝳꝴꝵ
var Xa746_a846 = fonts.Subfont{
	First:  0xa746, // 'Ꝇ'
	Last:   0xa846, // 'ꡆ'
	Offset: 0,
	Data:   &Xa746,
}

// Xa644_a744 subfont, n=257, ꙄꙅꙆꙇꙈꙉꙊꙋꙌꙍꙎꙏꙐꙑꙒꙓꙔꙕꙖꙗꙘꙙꙚꙛꙜꙝꙞꙟꙠꙡꙢꙣꙤꙥꙦꙧꙨꙩꙪꙫꙬꙭꙮ꙯꙰꙱꙲꙳
var Xa644_a744 = fonts.Subfont{
	First:  0xa644, // 'Ꙅ'
	Last:   0xa744, // 'Ꝅ'
	Offset: 0,
	Data:   &Xa644,
}

// X2e18_2f18 subfont, n=257, ⸘⸙⸚⸛⸜⸝⸞⸟⸠⸡⸢⸣⸤⸥⸦⸧⸨⸩⸪⸫⸬⸭⸮ⸯ⸰⸱⸲⸳⸴⸵⸶⸷⸸⸹⸺⸻⸼⸽⸾⸿⹀⹁⹂⹃⹄⹅⹆⹇
var X2e18_2f18 = fonts.Subfont{
	First:  0x2e18, // '⸘'
	Last:   0x2f18, // '⼘'
	Offset: 0,
	Data:   &X2e18,
}

// X2c60_2d60 subfont, n=257, ⱠⱡⱢⱣⱤⱥⱦⱧⱨⱩⱪⱫⱬⱭⱮⱯⱰⱱⱲⱳⱴⱵⱶⱷⱸⱹⱺⱻⱼⱽⱾⱿⲀⲁⲂⲃⲄⲅⲆⲇⲈⲉⲊⲋⲌⲍⲎⲏ
var X2c60_2d60 = fonts.Subfont{
	First:  0x2c60, // 'Ⱡ'
	Last:   0x2d60, // 'ⵠ'
	Offset: 0,
	Data:   &X2c60,
}

// X2b00_2c00 subfont, n=257, ⬀⬁⬂⬃⬄⬅⬆⬇⬈⬉⬊⬋⬌⬍⬎⬏⬐⬑⬒⬓⬔⬕⬖⬗⬘⬙⬚⬛⬜⬝⬞⬟⬠⬡⬢⬣⬤⬥⬦⬧⬨⬩⬪⬫⬬⬭⬮⬯
var X2b00_2c00 = fonts.Subfont{
	First:  0x2b00, // '⬀'
	Last:   0x2c00, // 'Ⰰ'
	Offset: 0,
	Data:   &X2b00,
}

// X29eb_2aeb subfont, n=257, ⧫⧬⧭⧮⧯⧰⧱⧲⧳⧴⧵⧶⧷⧸⧹⧺⧻⧼⧽⧾⧿⨀⨁⨂⨃⨄⨅⨆⨇⨈⨉⨊⨋⨌⨍⨎⨏⨐⨑⨒⨓⨔⨕⨖⨗⨘⨙⨚
var X29eb_2aeb = fonts.Subfont{
	First:  0x29eb, // '⧫'
	Last:   0x2aeb, // '⫫'
	Offset: 0,
	Data:   &X29eb,
}

// X28a2_29a2 subfont, n=257, ⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑
var X28a2_29a2 = fonts.Subfont{
	First:  0x28a2, // '⢢'
	Last:   0x29a2, // '⦢'
	Offset: 0,
	Data:   &X28a2,
}

// X27a1_28a1 subfont, n=257, ➡➢➣➤➥➦➧➨➩➪➫➬➭➮➯➰➱➲➳➴➵➶➷➸➹➺➻➼➽➾➿⟀⟁⟂⟃⟄⟅⟆⟇⟈⟉⟊⟋⟌⟍⟎⟏⟐
var X27a1_28a1 = fonts.Subfont{
	First:  0x27a1, // '➡'
	Last:   0x28a1, // '⢡'
	Offset: 0,
	Data:   &X27a1,
}

// X2638_2738 subfont, n=257, ☸☹☺☻☼☽☾☿♀♁♂♃♄♅♆♇♈♉♊♋♌♍♎♏♐♑♒♓♔♕♖♗♘♙♚♛♜♝♞♟♠♡♢♣♤♥♦♧
var X2638_2738 = fonts.Subfont{
	First:  0x2638, // '☸'
	Last:   0x2738, // '✸'
	Offset: 0,
	Data:   &X2638,
}

// X2524_2624 subfont, n=257, ┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋╌╍╎╏═║╒╓
var X2524_2624 = fonts.Subfont{
	First:  0x2524, // '┤'
	Last:   0x2624, // '☤'
	Offset: 0,
	Data:   &X2524,
}

// X2423_2523 subfont, n=257, ␣␤␥␦⑀⑁⑂⑃⑄⑅⑆⑇⑈⑉⑊①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳⑴⑵⑶⑷⑸⑹⑺⑻⑼⑽⑾⑿⒀
var X2423_2523 = fonts.Subfont{
	First:  0x2423, // '␣'
	Last:   0x2523, // '┣'
	Offset: 0,
	Data:   &X2423,
}

// X2310_2410 subfont, n=257, ⌐⌑⌒⌓⌔⌕⌖⌗⌘⌙⌚⌛⌜⌝⌞⌟⌠⌡⌢⌣⌤⌥⌦⌧⌨〈〉⌫⌬⌭⌮⌯⌰⌱⌲⌳⌴⌵⌶⌷⌸⌹⌺⌻⌼⌽⌾⌿
var X2310_2410 = fonts.Subfont{
	First:  0x2310, // '⌐'
	Last:   0x2410, // '␐'
	Offset: 0,
	Data:   &X2310,
}

// X220b_230b subfont, n=257, ∋∌∍∎∏∐∑−∓∔∕∖∗∘∙√∛∜∝∞∟∠∡∢∣∤∥∦∧∨∩∪∫∬∭∮∯∰∱∲∳∴∵∶∷∸∹∺
var X220b_230b = fonts.Subfont{
	First:  0x220b, // '∋'
	Last:   0x230b, // '⌋'
	Offset: 0,
	Data:   &X220b,
}

// X2109_2209 subfont, n=257, ℉ℊℋℌℍℎℏℐℑℒℓ℔ℕ№℗℘ℙℚℛℜℝ℞℟℠℡™℣ℤ℥Ω℧ℨ℩KÅℬℭ℮ℯℰℱℲℳℴℵℶℷℸ
var X2109_2209 = fonts.Subfont{
	First:  0x2109, // '℉'
	Last:   0x2209, // '∉'
	Offset: 0,
	Data:   &X2109,
}

// X2003_2103 subfont, n=257, ‐‑‒–—―‖‗‘’‚‛“”„‟†‡•‣․‥…‧‰‱′″‴‵‶‷‸‹›※‼‽‾‿⁀⁁⁂⁃⁄⁅⁆⁇
var X2003_2103 = fonts.Subfont{
	First:  0x2003,
	Last:   0x2103, // '℃'
	Offset: 0,
	Data:   &X2003,
}

// X1f02_2002 subfont, n=257, ἂἃἄἅἆἇἈἉἊἋἌἍἎἏἐἑἒἓἔἕἘἙἚἛἜἝἠἡἢἣἤἥἦἧἨἩἪἫἬἭἮἯἰἱἲἳἴἵ
var X1f02_2002 = fonts.Subfont{
	First:  0x1f02, // 'ἂ'
	Last:   0x2002,
	Offset: 0,
	Data:   &X1f02,
}

// X1e01_1f01 subfont, n=257, ḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯḰ
var X1e01_1f01 = fonts.Subfont{
	First:  0x1e01, // 'ḁ'
	Last:   0x1f01, // 'ἁ'
	Offset: 0,
	Data:   &X1e01,
}

// X1d00_1e00 subfont, n=257, ᴀᴁᴂᴃᴄᴅᴆᴇᴈᴉᴊᴋᴌᴍᴎᴏᴐᴑᴒᴓᴔᴕᴖᴗᴘᴙᴚᴛᴜᴝᴞᴟᴠᴡᴢᴣᴤᴥᴦᴧᴨᴩᴪᴫᴬᴭᴮᴯ
var X1d00_1e00 = fonts.Subfont{
	First:  0x1d00, // 'ᴀ'
	Last:   0x1e00, // 'Ḁ'
	Offset: 0,
	Data:   &X1d00,
}

// X10a0_11a0 subfont, n=257, ႠႡႢႣႤႥႦႧႨႩႪႫႬႭႮႯႰႱႲႳႴႵႶႷႸႹႺႻႼႽႾႿჀჁჂჃჄჅჇჍაბგდევზთ
var X10a0_11a0 = fonts.Subfont{
	First:  0x10a0, // 'Ⴀ'
	Last:   0x11a0, // 'ᆠ'
	Offset: 0,
	Data:   &X10a0,
}

// X0510_0610 subfont, n=257, ԐԑԒԓԔԕԖԗԘԙԚԛԜԝԞԟԠԡԢԣԤԥԦԧԨԩԪԫԬԭԮԯԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀ
var X0510_0610 = fonts.Subfont{
	First:  0x0510, // 'Ԑ'
	Last:   0x0610, // 'ؐ'
	Offset: 0,
	Data:   &X0510,
}

// X0404_0504 subfont, n=257, ЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвг
var X0404_0504 = fonts.Subfont{
	First:  0x0404, // 'Є'
	Last:   0x0504, // 'Ԅ'
	Offset: 0,
	Data:   &X0404,
}

// X0303_0403 subfont, n=257, ̡̢̧̨̛̖̗̘̙̜̝̞̟̠̣̤̥̦̩̪̫̬̭̮̯̰̱̲̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̕̚
var X0303_0403 = fonts.Subfont{
	First:  0x0303, // '̃'
	Last:   0x0403, // 'Ѓ'
	Offset: 0,
	Data:   &X0303,
}

// X0202_0302 subfont, n=257, ȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱ
var X0202_0302 = fonts.Subfont{
	First:  0x0202, // 'Ȃ'
	Last:   0x0302, // '̂'
	Offset: 0,
	Data:   &X0202,
}

// X0101_0201 subfont, n=257, āĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİ
var X0101_0201 = fonts.Subfont{
	First:  0x0101, // 'ā'
	Last:   0x0201, // 'ȁ'
	Offset: 0,
	Data:   &X0101,
}

// X0000_0100 subfont, n=257,  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO
var X0000_0100 = fonts.Subfont{
	First:  0x0000,
	Last:   0x0100, // 'Ā'
	Offset: 0,
	Data:   &X0000,
}
