// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavu/dejavu.14.font

package dejavu14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 303 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 15, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 15,
		Pix:    pixXfff9, // 225 bytes
	},
}

// Xfb00 font data, 1990 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 76, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 76,
		Pix:    pixXfb00, // 912 bytes
	},
}

// Xf6c5 font data, 1282 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 17, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 17,
		Pix:    pixXf6c5, // 204 bytes
	},
}

// Xf400 font data, 7654 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 410, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 411,
		Pix:    pixXf400, // 6576 bytes
	},
}

// Xa746 font data, 5889 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 283, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 283,
		Pix:    pixXa746, // 4811 bytes
	},
}

// Xa644 font data, 8488 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 494, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 494,
		Pix:    pixXa644, // 7410 bytes
	},
}

// X2e18 font data, 1468 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 30, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 30,
		Pix:    pixX2e18, // 390 bytes
	},
}

// X2c60 font data, 10768 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 633, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 646,
		Pix:    pixX2c60, // 9690 bytes
	},
}

// X2b00 font data, 4588 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 270, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 270,
		Pix:    pixX2b00, // 3510 bytes
	},
}

// X29eb font data, 1878 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 50, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 50,
		Pix:    pixX29eb, // 800 bytes
	},
}

// X28a2 font data, 33018 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 890 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 2003, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX28a2, // 32080 bytes
	},
}

// X27a1 font data, 25014 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1495, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1496,
		Pix:    pixX27a1, // 23936 bytes
	},
}

// X2524 font data, 36986 bytes, orgbpp: 8
var X2524 = font9.Variable{
	Info: infoX2524, // 866 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2004, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2004,
		Pix:    pixX2524, // 36072 bytes
	},
}

// X2423 font data, 5254 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 232, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 232,
		Pix:    pixX2423, // 4176 bytes
	},
}

// X1e01 font data, 37142 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 950 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1894, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2008,
		Pix:    pixX1e01, // 36144 bytes
	},
}

// X1d00 font data, 17702 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1038, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1039,
		Pix:    pixX1d00, // 16624 bytes
	},
}

// X10a0 font data, 14422 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 833, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 834,
		Pix:    pixX10a0, // 13344 bytes
	},
}

// X0101 font data, 37004 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 938 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1991, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2001,
		Pix:    pixX0101, // 36018 bytes
	},
}

// X0000 font data, 23542 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1403, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1404,
		Pix:    pixX0000, // 22464 bytes
	},
}
