// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavubi/dejavubi.14.font

package dejavubi14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 334 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 16, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixXfff9, // 256 bytes
	},
}

// Xfb00 font data, 2478 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 100, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 100,
		Pix:    pixXfb00, // 1400 bytes
	},
}

// Xf6c4 font data, 2038 bytes, orgbpp: 8
var Xf6c4 = font9.Variable{
	Info: infoXf6c4, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 64, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 64,
		Pix:    pixXf6c4, // 960 bytes
	},
}

// Xf400 font data, 9238 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 461, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 480,
		Pix:    pixXf400, // 8160 bytes
	},
}

// Xa746 font data, 7198 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 336, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 340,
		Pix:    pixXa746, // 6120 bytes
	},
}

// Xa644 font data, 9778 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 577, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 580,
		Pix:    pixXa644, // 8700 bytes
	},
}

// X2e18 font data, 1572 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 37, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 38,
		Pix:    pixX2e18, // 494 bytes
	},
}

// X2c60 font data, 12178 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 727, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 740,
		Pix:    pixX2c60, // 11100 bytes
	},
}

// X2b00 font data, 4562 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 268, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 268,
		Pix:    pixX2b00, // 3484 bytes
	},
}

// X29eb font data, 1974 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 56, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 56,
		Pix:    pixX29eb, // 896 bytes
	},
}

// X28a2 font data, 27986 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1918, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1922,
		Pix:    pixX28a2, // 26908 bytes
	},
}

// X27a1 font data, 21133 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1334, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1337,
		Pix:    pixX27a1, // 20055 bytes
	},
}

// X2580 font data, 25478 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1524, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1525,
		Pix:    pixX2580, // 24400 bytes
	},
}

// X1e01 font data, 36834 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 714 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1713, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2004,
		Pix:    pixX1e01, // 36072 bytes
	},
}

// X1d00 font data, 22668 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1247, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1270,
		Pix:    pixX1d00, // 21590 bytes
	},
}

// X10a0 font data, 17126 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 941, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 944,
		Pix:    pixX10a0, // 16048 bytes
	},
}

// X0101 font data, 36926 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 734 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1975, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2008,
		Pix:    pixX0101, // 36144 bytes
	},
}

// X0000 font data, 34648 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1845, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1865,
		Pix:    pixX0000, // 33570 bytes
	},
}
