// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusansbd/dejavusansbd.18.font

package dejavusansbd18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 178 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 18, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 100 bytes
	},
}

// Xfe00 font data, 11681 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1740, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 461,
		Pix:    pixXfe00, // 10603 bytes
	},
}

// Xfb00 font data, 12078 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1904, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 500,
		Pix:    pixXfb00, // 11000 bytes
	},
}

// Xf6c5 font data, 1123 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 11, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf6c5, // 45 bytes
	},
}

// Xef00 font data, 1666 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 152, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 42,
		Pix:    pixXef00, // 588 bytes
	},
}

// Xa746 font data, 3430 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 429, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 112,
		Pix:    pixXa746, // 2352 bytes
	},
}

// Xa644 font data, 5542 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 956, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 248,
		Pix:    pixXa644, // 4464 bytes
	},
}

// X4dc0 font data, 4662 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX4dc0, // 3584 bytes
	},
}

// X2d61 font data, 1588 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 114, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 30,
		Pix:    pixX2d61, // 510 bytes
	},
}

// X2c60 font data, 6038 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 940, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 248,
		Pix:    pixX2c60, // 4960 bytes
	},
}

// X2580 font data, 11724 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 610 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1930, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2580, // 11066 bytes
	},
}

// X1e01 font data, 12312 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 718 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1801, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX1e01, // 11546 bytes
	},
}

// X1d00 font data, 7798 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1203, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 336,
		Pix:    pixX1d00, // 6720 bytes
	},
}

// X1646 font data, 6006 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 856, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX1646, // 4928 bytes
	},
}

// X1401 font data, 9147 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 582 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1875, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1401, // 8517 bytes
	},
}

// X10a0 font data, 5695 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 873, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 243,
		Pix:    pixX10a0, // 4617 bytes
	},
}

// X0e3f font data, 5954 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 807, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 212,
		Pix:    pixX0e3f, // 4876 bytes
	},
}

// X07c0 font data, 3529 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 492, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 129,
		Pix:    pixX07c0, // 2451 bytes
	},
}

// X03c0 font data, 74 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 12,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 30 bytes
	},
}

// X03a9 font data, 96 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   14,
	Width: 14,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixX03a9, // 52 bytes
	},
}

// X0101 font data, 11303 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 734 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1986, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX0101, // 10521 bytes
	},
}

// X00a0 font data, 5978 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 955, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 264,
		Pix:    pixX00a0, // 5544 bytes
	},
}

// X0020 font data, 4948 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 907, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 251,
		Pix:    pixX0020, // 4518 bytes
	},
}

// X0000 font data, 92 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0000, // 48 bytes
	},
}
