// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansbd/dejavusansbd.18.font

package dejavusansbd18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 478 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 20, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 20,
		Pix:    pixXfff9, // 400 bytes
	},
}

// Xfe00 font data, 43444 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1839, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1842,
		Pix:    pixXfe00, // 42366 bytes
	},
}

// Xfb00 font data, 45034 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1992, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1998,
		Pix:    pixXfb00, // 43956 bytes
	},
}

// Xf6c5 font data, 1258 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 12, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixXf6c5, // 180 bytes
	},
}

// Xef00 font data, 3430 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 168, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 168,
		Pix:    pixXef00, // 2352 bytes
	},
}

// Xa746 font data, 10423 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 445, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 445,
		Pix:    pixXa746, // 9345 bytes
	},
}

// Xa644 font data, 18916 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 991, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 991,
		Pix:    pixXa644, // 17838 bytes
	},
}

// X4dc0 font data, 15414 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 896,
		Pix:    pixX4dc0, // 14336 bytes
	},
}

// X2d61 font data, 3067 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 117, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 117,
		Pix:    pixX2d61, // 1989 bytes
	},
}

// X2c60 font data, 20878 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 990, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 990,
		Pix:    pixX2c60, // 19800 bytes
	},
}

// X2580 font data, 44900 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 610 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1994, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2011,
		Pix:    pixX2580, // 44242 bytes
	},
}

// X1e01 font data, 46950 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 718 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1812, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2008,
		Pix:    pixX1e01, // 46184 bytes
	},
}

// X1d00 font data, 27898 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1335, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1341,
		Pix:    pixX1d00, // 26820 bytes
	},
}

// X1646 font data, 20724 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 893, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 893,
		Pix:    pixX1646, // 19646 bytes
	},
}

// X1401 font data, 34664 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 582 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1938, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX1401, // 34034 bytes
	},
}

// X10a0 font data, 19489 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 966, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 969,
		Pix:    pixX10a0, // 18411 bytes
	},
}

// X0e3f font data, 20536 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 843, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 846,
		Pix:    pixX0e3f, // 19458 bytes
	},
}

// X07c0 font data, 10844 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 514, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 514,
		Pix:    pixX07c0, // 9766 bytes
	},
}

// X03c0 font data, 164 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 12,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixX03c0, // 120 bytes
	},
}

// X03a9 font data, 226 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   14,
	Width: 14,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixX03a9, // 182 bytes
	},
}

// X0101 font data, 42824 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 734 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 2002, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX0101, // 42042 bytes
	},
}

// X00a0 font data, 22610 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 958, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1056,
		Pix:    pixX00a0, // 22176 bytes
	},
}

// X0020 font data, 18502 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 909, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1004,
		Pix:    pixX0020, // 18072 bytes
	},
}

// X0000 font data, 188 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX0000, // 144 bytes
	},
}
