// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansit/dejavusansit.16.font

package dejavusansit16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 367 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 17, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 17,
		Pix:    pixXfff9, // 289 bytes
	},
}

// Xfe00 font data, 1168 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 30, Y: -12},
		},
		LogN:   3, // 8 bpp
		Stride: 30,
		Pix:    pixXfe00, // 90 bytes
	},
}

// Xfb00 font data, 11720 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 619, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 626,
		Pix:    pixXfb00, // 10642 bytes
	},
}

// Xf6c5 font data, 1218 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixXf6c5, // 140 bytes
	},
}

// Xef00 font data, 2878 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 146, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 150,
		Pix:    pixXef00, // 1800 bytes
	},
}

// Xa746 font data, 8127 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 368, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 371,
		Pix:    pixXa746, // 7049 bytes
	},
}

// Xa644 font data, 15953 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 862, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 875,
		Pix:    pixXa644, // 14875 bytes
	},
}

// X4dc0 font data, 12598 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 768,
		Pix:    pixX4dc0, // 11520 bytes
	},
}

// X2e18 font data, 1654 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 36, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 36,
		Pix:    pixX2e18, // 576 bytes
	},
}

// X2c60 font data, 7090 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 328, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 334,
		Pix:    pixX2c60, // 6012 bytes
	},
}

// X2523 font data, 41010 bytes, orgbpp: 8
var X2523 = font9.Variable{
	Info: infoX2523, // 782 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 2009, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX2523, // 40180 bytes
	},
}

// X2422 font data, 8938 bytes, orgbpp: 8
var X2422 = font9.Variable{
	Info: infoX2422, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 393, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 393,
		Pix:    pixX2422, // 7860 bytes
	},
}

// X1e01 font data, 40854 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 786 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1740, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2001,
		Pix:    pixX1e01, // 40020 bytes
	},
}

// X1d00 font data, 20696 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1132, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1154,
		Pix:    pixX1d00, // 19618 bytes
	},
}

// X1401 font data, 32926 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 702 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1887, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2011,
		Pix:    pixX1401, // 32176 bytes
	},
}

// X10a0 font data, 15256 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 832, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 834,
		Pix:    pixX10a0, // 14178 bytes
	},
}

// X0e3f font data, 14568 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 674, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 710,
		Pix:    pixX0e3f, // 13490 bytes
	},
}

// X03c0 font data, 124 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixX03c0, // 80 bytes
	},
}

// X03a9 font data, 200 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 13,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 13,
		Pix:    pixX03a9, // 156 bytes
	},
}

// X0101 font data, 38911 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 806 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1981, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2003,
		Pix:    pixX0101, // 38057 bytes
	},
}

// X00a0 font data, 17174 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 830, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 930,
		Pix:    pixX00a0, // 16740 bytes
	},
}

// X0020 font data, 15764 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 804, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 902,
		Pix:    pixX0020, // 15334 bytes
	},
}

// X0000 font data, 156 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixX0000, // 112 bytes
	},
}
