// DO NOT EDIT
// Generated by: go run 9font.go -n bit/anonpro/anonpro.12.font

package anonpro12

import (
	"image"

	"github.com/embeddedgo/display/pixd"
	"github.com/embeddedgo/display/pixd/font/font9"
)

// Xfb01 font data, 1110 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfb01, // 32 bytes
	},
}

// Xf8ff font data, 1114 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXf8ff, // 36 bytes
	},
}

// Xf6c3 font data, 1080 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 2, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 1,
		Pix:    pixXf6c3, // 2 bytes
	},
}

// Xe000 font data, 1195 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 50, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixXe000, // 117 bytes
	},
}

// X2713 font data, 1090 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -5},
			Max: image.Point{X: 6, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX2713, // 12 bytes
	},
}

// X2500 font data, 1738 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 187, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 60,
		Pix:    pixX2500, // 660 bytes
	},
}

// X2324 font data, 1182 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 45, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX2324, // 104 bytes
	},
}

// X221a font data, 1221 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 45, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX221a, // 143 bytes
	},
}

// X2116 font data, 1195 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 47, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX2116, // 117 bytes
	},
}

// X2013 font data, 1331 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 76, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 23,
		Pix:    pixX2013, // 253 bytes
	},
}

// X1e02 font data, 1441 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 121, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 33,
		Pix:    pixX1e02, // 363 bytes
	},
}

// X0490 font data, 1105 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0490, // 27 bytes
	},
}

// X0384 font data, 3826 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 860, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 229,
		Pix:    pixX0384, // 2748 bytes
	},
}

// X0218 font data, 1221 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 45, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX0218, // 143 bytes
	},
}

// X0101 font data, 3069 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 682, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 181,
		Pix:    pixX0101, // 1991 bytes
	},
}

// X0000 font data, 4006 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 917, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 244,
		Pix:    pixX0000, // 2928 bytes
	},
}
