// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavubi/dejavubi.16.font

package dejavubi16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 402 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 18, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 18,
		Pix:    pixXfff9, // 324 bytes
	},
}

// Xfb00 font data, 2886 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 112, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 113,
		Pix:    pixXfb00, // 1808 bytes
	},
}

// Xf6c4 font data, 2392 bytes, orgbpp: 8
var Xf6c4 = font9.Variable{
	Info: infoXf6c4, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 73, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 73,
		Pix:    pixXf6c4, // 1314 bytes
	},
}

// Xf400 font data, 11433 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 529, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 545,
		Pix:    pixXf400, // 10355 bytes
	},
}

// Xa746 font data, 8412 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 381, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 386,
		Pix:    pixXa746, // 7334 bytes
	},
}

// Xa644 font data, 12264 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 655, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 658,
		Pix:    pixXa644, // 11186 bytes
	},
}

// X2e18 font data, 1666 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 41, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 42,
		Pix:    pixX2e18, // 588 bytes
	},
}

// X2c60 font data, 15324 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 829, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 838,
		Pix:    pixX2c60, // 14246 bytes
	},
}

// X2b00 font data, 5773 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 313, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 313,
		Pix:    pixX2b00, // 4695 bytes
	},
}

// X28a2 font data, 35022 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 838 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 2000, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2008,
		Pix:    pixX28a2, // 34136 bytes
	},
}

// X27a1 font data, 27275 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1539, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1541,
		Pix:    pixX27a1, // 26197 bytes
	},
}

// X2580 font data, 30879 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1750, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1753,
		Pix:    pixX2580, // 29801 bytes
	},
}

// X2423 font data, 1156 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -2},
			Max: image.Point{X: 13, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 13,
		Pix:    pixX2423, // 78 bytes
	},
}

// X2103 font data, 37036 bytes, orgbpp: 8
var X2103 = font9.Variable{
	Info: infoX2103, // 898 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1999, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX2103, // 36090 bytes
	},
}

// X1e01 font data, 40822 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 634 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1868, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2007,
		Pix:    pixX1e01, // 40140 bytes
	},
}

// X1d00 font data, 27944 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1389, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1414,
		Pix:    pixX1d00, // 26866 bytes
	},
}

// X10a0 font data, 21123 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1053, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1055,
		Pix:    pixX10a0, // 20045 bytes
	},
}

// X0000 font data, 41146 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 998 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1993, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX0000, // 40100 bytes
	},
}
