// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusans/dejavusans.14.font

package dejavusans14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 138 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 60 bytes
	},
}

// Xfe00 font data, 6946 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1154, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 326,
		Pix:    pixXfe00, // 5868 bytes
	},
}

// Xfb00 font data, 7306 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1266, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 346,
		Pix:    pixXfb00, // 6228 bytes
	},
}

// Xf6c5 font data, 1102 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 7, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixXf6c5, // 24 bytes
	},
}

// Xf001 font data, 1177 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 24, Y: -1},
		},
		LogN:   1, // 2 bpp
		Stride: 11,
		Pix:    pixXf001, // 99 bytes
	},
}

// Xef00 font data, 1448 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 109, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 37,
		Pix:    pixXef00, // 370 bytes
	},
}

// Xa746 font data, 2262 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 273, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 74,
		Pix:    pixXa746, // 1184 bytes
	},
}

// Xa644 font data, 3514 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 651, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 174,
		Pix:    pixXa644, // 2436 bytes
	},
}

// X4dc0 font data, 3542 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 704, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 176,
		Pix:    pixX4dc0, // 2464 bytes
	},
}

// X2d61 font data, 1325 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 71, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 19,
		Pix:    pixX2d61, // 247 bytes
	},
}

// X2c60 font data, 3654 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 627, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 161,
		Pix:    pixX2c60, // 2576 bytes
	},
}

// X2104 font data, 9473 bytes, orgbpp: 8
var X2104 = font9.Variable{
	Info: infoX2104, // 874 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1885, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2104, // 8551 bytes
	},
}

// X2003 font data, 5498 bytes, orgbpp: 8
var X2003 = font9.Variable{
	Info: infoX2003, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 975, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 260,
		Pix:    pixX2003, // 4420 bytes
	},
}

// X1f02 font data, 9408 bytes, orgbpp: 8
var X1f02 = font9.Variable{
	Info: infoX1f02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1944, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 490,
		Pix:    pixX1f02, // 8330 bytes
	},
}

// X1e01 font data, 9425 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1804, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 491,
		Pix:    pixX1e01, // 8347 bytes
	},
}

// X1d00 font data, 4742 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 810, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 229,
		Pix:    pixX1d00, // 3664 bytes
	},
}

// X1401 font data, 6982 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 898 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1942, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1401, // 6036 bytes
	},
}

// X10a0 font data, 3570 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 674, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 178,
		Pix:    pixX10a0, // 2492 bytes
	},
}

// X0e3f font data, 3305 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 499, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 131,
		Pix:    pixX0e3f, // 2227 bytes
	},
}

// X0404 font data, 9508 bytes, orgbpp: 8
var X0404 = font9.Variable{
	Info: infoX0404, // 926 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1948, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0404, // 8534 bytes
	},
}

// X03c0 font data, 58 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX03c0, // 14 bytes
	},
}

// X03a9 font data, 74 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 9, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03a9, // 30 bytes
	},
}

// X0303 font data, 7630 bytes, orgbpp: 8
var X0303 = font9.Variable{
	Info: infoX0303, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1359, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 364,
		Pix:    pixX0303, // 6552 bytes
	},
}

// X0202 font data, 8098 bytes, orgbpp: 8
var X0202 = font9.Variable{
	Info: infoX0202, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1469, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 390,
		Pix:    pixX0202, // 7020 bytes
	},
}

// X0101 font data, 9459 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1918, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 493,
		Pix:    pixX0101, // 8381 bytes
	},
}

// X0020 font data, 3100 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 607, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 178,
		Pix:    pixX0020, // 2670 bytes
	},
}

// X0000 font data, 68 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 24 bytes
	},
}
