// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusans/dejavusans.14.font

package dejavusans14

import "github.com/embeddedgo/display/font/subfont"

const (
	Height = 18
	Ascent = 14
)

// NewFace provides a convenient way to create a font face containing the listed
// subfonts. The returned face is SAFE for concurent use.
func NewFace(subfonts ...*subfont.Subfont) *subfont.Face {
	return &subfont.Face{Height: Height, Ascent: Ascent, Subfonts: subfonts}
}

// Xfff9_ffff subfont, n=7, ￼�
var Xfff9_ffff = &subfont.Subfont{
	First:  0xfff9,
	Last:   0xffff,
	Offset: 0,
	Data:   &Xfff9,
}

// Xfe00_feff subfont, n=256, ︀︁︂︃︄︅︆︇︈︉︊︋︌︍︎️︐︑︒︓︔︕︖︗︘︙︧︨︩︪︫︬︭︠︡︢︣︤︥︦︮︯︰︱︲︳︴︵
var Xfe00_feff = &subfont.Subfont{
	First:  0xfe00, // '︀'
	Last:   0xfeff,
	Offset: 0,
	Data:   &Xfe00,
}

// Xfb00_fc00 subfont, n=257, ﬀﬁﬂﬃﬄﬅﬆﬓﬔﬕﬖﬗיִﬞײַﬠﬡﬢﬣﬤﬥﬦﬧﬨ﬩שׁשׂשּׁשּׂאַאָאּבּגּדּהּוּזּטּיּךּכּלּמּנּסּףּפּ
var Xfb00_fc00 = &subfont.Subfont{
	First:  0xfb00, // 'ﬀ'
	Last:   0xfc00, // 'ﰀ'
	Offset: 0,
	Data:   &Xfb00,
}

// Xf6c5_f7c5 subfont, n=257, 
var Xf6c5_f7c5 = &subfont.Subfont{
	First:  0xf6c5,
	Last:   0xf7c5,
	Offset: 0,
	Data:   &Xf6c5,
}

// Xf001_f101 subfont, n=257, 
var Xf001_f101 = &subfont.Subfont{
	First:  0xf001,
	Last:   0xf101,
	Offset: 0,
	Data:   &Xf001,
}

// Xef00_f000 subfont, n=257, 
var Xef00_f000 = &subfont.Subfont{
	First:  0xef00,
	Last:   0xf000,
	Offset: 0,
	Data:   &Xef00,
}

// Xa746_a846 subfont, n=257, ꝆꝇꝈꝉꝊꝋꝌꝍꝎꝏꝐꝑꝒꝓꝔꝕꝖꝗꝘꝙꝚꝛꝜꝝꝞꝟꝠꝡꝢꝣꝤꝥꝦꝧꝨꝩꝪꝫꝬꝭꝮꝯꝰꝱꝲꝳꝴꝵ
var Xa746_a846 = &subfont.Subfont{
	First:  0xa746, // 'Ꝇ'
	Last:   0xa846, // 'ꡆ'
	Offset: 0,
	Data:   &Xa746,
}

// Xa644_a744 subfont, n=257, ꙄꙅꙆꙇꙈꙉꙊꙋꙌꙍꙎꙏꙐꙑꙒꙓꙔꙕꙖꙗꙘꙙꙚꙛꙜꙝꙞꙟꙠꙡꙢꙣꙤꙥꙦꙧꙨꙩꙪꙫꙬꙭꙮ꙯꙰꙱꙲꙳
var Xa644_a744 = &subfont.Subfont{
	First:  0xa644, // 'Ꙅ'
	Last:   0xa744, // 'Ꝅ'
	Offset: 0,
	Data:   &Xa644,
}

// X4dc0_4ec0 subfont, n=257, ䷀䷁䷂䷃䷄䷅䷆䷇䷈䷉䷊䷋䷌䷍䷎䷏䷐䷑䷒䷓䷔䷕䷖䷗䷘䷙䷚䷛䷜䷝䷞䷟䷠䷡䷢䷣䷤䷥䷦䷧䷨䷩䷪䷫䷬䷭䷮䷯
var X4dc0_4ec0 = &subfont.Subfont{
	First:  0x4dc0, // '䷀'
	Last:   0x4ec0, // '什'
	Offset: 0,
	Data:   &X4dc0,
}

// X2d61_2e61 subfont, n=257, ⵡⵢⵣⵤⵥⵦⵧⵯ⵰⵿ⶀⶁⶂⶃⶄⶅⶆⶇⶈⶉⶊⶋⶌⶍⶎⶏⶐⶑⶒⶓⶔⶕⶖⶠⶡⶢⶣⶤⶥⶦⶨⶩⶪⶫⶬⶭⶮⶰ
var X2d61_2e61 = &subfont.Subfont{
	First:  0x2d61, // 'ⵡ'
	Last:   0x2e61,
	Offset: 0,
	Data:   &X2d61,
}

// X2c60_2d60 subfont, n=257, ⱠⱡⱢⱣⱤⱥⱦⱧⱨⱩⱪⱫⱬⱭⱮⱯⱰⱱⱲⱳⱴⱵⱶⱷⱸⱹⱺⱻⱼⱽⱾⱿⲀⲁⲂⲃⲄⲅⲆⲇⲈⲉⲊⲋⲌⲍⲎⲏ
var X2c60_2d60 = &subfont.Subfont{
	First:  0x2c60, // 'Ⱡ'
	Last:   0x2d60, // 'ⵠ'
	Offset: 0,
	Data:   &X2c60,
}

// X2104_21fb subfont, n=248, ℄℅℆ℇ℈℉ℊℋℌℍℎℏℐℑℒℓ℔ℕ№℗℘ℙℚℛℜℝ℞℟℠℡™℣ℤ℥Ω℧ℨ℩KÅℬℭ℮ℯℰℱℲℳ
var X2104_21fb = &subfont.Subfont{
	First:  0x2104, // '℄'
	Last:   0x21fb, // '⇻'
	Offset: 0,
	Data:   &X2104,
}

// X2100_2103 subfont, n=4, ℀℁ℂ
var X2100_2103 = &subfont.Subfont{
	First:  0x2100, // '℀'
	Last:   0x2103, // '℃'
	Offset: 0,
	Data:   &X2003,
}

// X1f02_2002 subfont, n=257, ἂἃἄἅἆἇἈἉἊἋἌἍἎἏἐἑἒἓἔἕἘἙἚἛἜἝἠἡἢἣἤἥἦἧἨἩἪἫἬἭἮἯἰἱἲἳἴἵ
var X1f02_2002 = &subfont.Subfont{
	First:  0x1f02, // 'ἂ'
	Last:   0x2002,
	Offset: 0,
	Data:   &X1f02,
}

// X1e01_1f01 subfont, n=257, ḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯḰ
var X1e01_1f01 = &subfont.Subfont{
	First:  0x1e01, // 'ḁ'
	Last:   0x1f01, // 'ἁ'
	Offset: 0,
	Data:   &X1e01,
}

// X1d00_1e00 subfont, n=257, ᴀᴁᴂᴃᴄᴅᴆᴇᴈᴉᴊᴋᴌᴍᴎᴏᴐᴑᴒᴓᴔᴕᴖᴗᴘᴙᴚᴛᴜᴝᴞᴟᴠᴡᴢᴣᴤᴥᴦᴧᴨᴩᴪᴫᴬᴭᴮᴯ
var X1d00_1e00 = &subfont.Subfont{
	First:  0x1d00, // 'ᴀ'
	Last:   0x1e00, // 'Ḁ'
	Offset: 0,
	Data:   &X1d00,
}

// X1401_1501 subfont, n=257, ᐁᐂᐃᐄᐅᐆᐇᐈᐉᐊᐋᐌᐍᐎᐏᐐᐑᐒᐓᐔᐕᐖᐗᐘᐙᐚᐛᐜᐝᐞᐟᐠᐡᐢᐣᐤᐥᐦᐧᐨᐩᐪᐫᐬᐭᐮᐯᐰ
var X1401_1501 = &subfont.Subfont{
	First:  0x1401, // 'ᐁ'
	Last:   0x1501, // 'ᔁ'
	Offset: 0,
	Data:   &X1401,
}

// X10a0_11a0 subfont, n=257, ႠႡႢႣႤႥႦႧႨႩႪႫႬႭႮႯႰႱႲႳႴႵႶႷႸႹႺႻႼႽႾႿჀჁჂჃჄჅჇჍაბგდევზთ
var X10a0_11a0 = &subfont.Subfont{
	First:  0x10a0, // 'Ⴀ'
	Last:   0x11a0, // 'ᆠ'
	Offset: 0,
	Data:   &X10a0,
}

// X0f00_0f3f subfont, n=64, ༀ༁༂༃༄༅༆༇༈༉༊་༌།༎༏༐༑༒༓༔༕༖༗༘༙༚༛༜༝༞༟༠༡༢༣༤༥༦༧༨༩༪༫༬༭༮༯
var X0f00_0f3f = &subfont.Subfont{
	First:  0x0f00, // 'ༀ'
	Last:   0x0f3f, // '༿'
	Offset: 0,
	Data:   &X0e3f,
}

// X0404_0504 subfont, n=257, ЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвг
var X0404_0504 = &subfont.Subfont{
	First:  0x0404, // 'Є'
	Last:   0x0504, // 'Ԅ'
	Offset: 0,
	Data:   &X0404,
}

// X03c0_03c0 subfont, n=1, 
var X03c0_03c0 = &subfont.Subfont{
	First:  0x03c0, // 'π'
	Last:   0x03c0, // 'π'
	Offset: 0,
	Data:   &X03c0,
}

// X03a9_03a9 subfont, n=1, 
var X03a9_03a9 = &subfont.Subfont{
	First:  0x03a9, // 'Ω'
	Last:   0x03a9, // 'Ω'
	Offset: 0,
	Data:   &X03a9,
}

// X0303_0403 subfont, n=257, ̡̢̧̨̛̖̗̘̙̜̝̞̟̠̣̤̥̦̩̪̫̬̭̮̯̰̱̲̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̕̚
var X0303_0403 = &subfont.Subfont{
	First:  0x0303, // '̃'
	Last:   0x0403, // 'Ѓ'
	Offset: 0,
	Data:   &X0303,
}

// X0202_02ff subfont, n=254, ȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱ
var X0202_02ff = &subfont.Subfont{
	First:  0x0202, // 'Ȃ'
	Last:   0x02ff, // '˿'
	Offset: 0,
	Data:   &X0202,
}

// X0101_0201 subfont, n=257, āĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİ
var X0101_0201 = &subfont.Subfont{
	First:  0x0101, // 'ā'
	Last:   0x0201, // 'ȁ'
	Offset: 0,
	Data:   &X0101,
}

// X0020_007e subfont, n=95,  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO
var X0020_007e = &subfont.Subfont{
	First:  0x0020, // ' '
	Last:   0x007e, // '~'
	Offset: 0,
	Data:   &X0020,
}

// X0000_0000 subfont, n=1, 
var X0000_0000 = &subfont.Subfont{
	First:  0x0000,
	Last:   0x0000,
	Offset: 0,
	Data:   &X0000,
}
