// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavu/dejavu.12.font

package dejavu12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 126 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 12, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 48 bytes
	},
}

// Xfb00 font data, 1265 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 66, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 17,
		Pix:    pixXfb00, // 187 bytes
	},
}

// Xf6c5 font data, 1122 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 16, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXf6c5, // 44 bytes
	},
}

// Xf400 font data, 2338 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 326, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 90,
		Pix:    pixXf400, // 1260 bytes
	},
}

// Xa746 font data, 2008 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 224, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 62,
		Pix:    pixXa746, // 930 bytes
	},
}

// Xa644 font data, 2469 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 393, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 107,
		Pix:    pixXa644, // 1391 bytes
	},
}

// X2e18 font data, 1162 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 22, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 7,
		Pix:    pixX2e18, // 84 bytes
	},
}

// X2c60 font data, 2885 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 492, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 139,
		Pix:    pixX2c60, // 1807 bytes
	},
}

// X2b00 font data, 1771 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 223, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 63,
		Pix:    pixX2b00, // 693 bytes
	},
}

// X29eb font data, 1221 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 42, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 11,
		Pix:    pixX29eb, // 143 bytes
	},
}

// X28a2 font data, 6525 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1428, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 419,
		Pix:    pixX28a2, // 5447 bytes
	},
}

// X27a1 font data, 4848 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 972, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 290,
		Pix:    pixX27a1, // 3770 bytes
	},
}

// X2638 font data, 1672 bytes, orgbpp: 8
var X2638 = font9.Variable{
	Info: infoX2638, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 206, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 54,
		Pix:    pixX2638, // 594 bytes
	},
}

// X2524 font data, 7933 bytes, orgbpp: 8
var X2524 = font9.Variable{
	Info: infoX2524, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1668, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 457,
		Pix:    pixX2524, // 6855 bytes
	},
}

// X2423 font data, 1888 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 194, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 54,
		Pix:    pixX2423, // 810 bytes
	},
}

// X2310 font data, 1723 bytes, orgbpp: 8
var X2310 = font9.Variable{
	Info: infoX2310, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 151, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 43,
		Pix:    pixX2310, // 645 bytes
	},
}

// X220b font data, 3668 bytes, orgbpp: 8
var X220b = font9.Variable{
	Info: infoX220b, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 715, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 185,
		Pix:    pixX220b, // 2590 bytes
	},
}

// X2109 font data, 7546 bytes, orgbpp: 8
var X2109 = font9.Variable{
	Info: infoX2109, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1694, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 462,
		Pix:    pixX2109, // 6468 bytes
	},
}

// X2003 font data, 3136 bytes, orgbpp: 8
var X2003 = font9.Variable{
	Info: infoX2003, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 542, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 147,
		Pix:    pixX2003, // 2058 bytes
	},
}

// X1f02 font data, 8278 bytes, orgbpp: 8
var X1f02 = font9.Variable{
	Info: infoX1f02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1583, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 480,
		Pix:    pixX1f02, // 7200 bytes
	},
}

// X1e01 font data, 8128 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1553, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 470,
		Pix:    pixX1e01, // 7050 bytes
	},
}

// X1d00 font data, 4042 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 792, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 228,
		Pix:    pixX1d00, // 2964 bytes
	},
}

// X10a0 font data, 3640 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 653, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 183,
		Pix:    pixX10a0, // 2562 bytes
	},
}

// X0510 font data, 3976 bytes, orgbpp: 8
var X0510 = font9.Variable{
	Info: infoX0510, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 761, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 207,
		Pix:    pixX0510, // 2898 bytes
	},
}

// X0404 font data, 7138 bytes, orgbpp: 8
var X0404 = font9.Variable{
	Info: infoX0404, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1559, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 404,
		Pix:    pixX0404, // 6060 bytes
	},
}

// X0303 font data, 5458 bytes, orgbpp: 8
var X0303 = font9.Variable{
	Info: infoX0303, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1086, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 292,
		Pix:    pixX0303, // 4380 bytes
	},
}

// X0202 font data, 6643 bytes, orgbpp: 8
var X0202 = font9.Variable{
	Info: infoX0202, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1367, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 371,
		Pix:    pixX0202, // 5565 bytes
	},
}

// X0101 font data, 8458 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1864, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 492,
		Pix:    pixX0101, // 7380 bytes
	},
}

// X0000 font data, 5713 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1224, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 309,
		Pix:    pixX0000, // 4635 bytes
	},
}
