// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavu/dejavu.18.font

package dejavu18

import (
	"image"

	"github.com/embeddedgo/display/pixdisp"
	"github.com/embeddedgo/display/pixdisp/font/font9"
)

// Xfff9 font data, 173 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 18, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 95 bytes
	},
}

// Xfb00 font data, 1453 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 96, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 25,
		Pix:    pixXfb00, // 375 bytes
	},
}

// Xf6c5 font data, 1168 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 22, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 6,
		Pix:    pixXf6c5, // 90 bytes
	},
}

// Xf400 font data, 3518 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 474, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 122,
		Pix:    pixXf400, // 2440 bytes
	},
}

// Xa746 font data, 3036 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 333, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 89,
		Pix:    pixXa746, // 1958 bytes
	},
}

// Xa644 font data, 4023 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 568, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 155,
		Pix:    pixXa644, // 2945 bytes
	},
}

// X2e18 font data, 1231 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 36, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 9,
		Pix:    pixX2e18, // 153 bytes
	},
}

// X2c60 font data, 4821 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 740, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 197,
		Pix:    pixX2c60, // 3743 bytes
	},
}

// X2b00 font data, 2608 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 339, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 90,
		Pix:    pixX2b00, // 1530 bytes
	},
}

// X28a2 font data, 10386 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 762 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1798, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 504,
		Pix:    pixX28a2, // 9576 bytes
	},
}

// X27a1 font data, 9638 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1523, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 428,
		Pix:    pixX27a1, // 8560 bytes
	},
}

// X1e01 font data, 12321 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 750 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1889, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1e01, // 11523 bytes
	},
}

// X1d00 font data, 7678 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1182, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 330,
		Pix:    pixX1d00, // 6600 bytes
	},
}

// X10a0 font data, 6643 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 968, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 265,
		Pix:    pixX10a0, // 5565 bytes
	},
}

// X0101 font data, 11854 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 762 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1938, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 11044 bytes
	},
}

// X0000 font data, 10423 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &pixdisp.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1761, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 445,
		Pix:    pixX0000, // 9345 bytes
	},
}
