// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/anonpro/anonpro.18.font

package anonpro18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1133 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 20, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfb01, // 55 bytes
	},
}

// Xf8ff font data, 1150 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 20, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 6,
		Pix:    pixXf8ff, // 72 bytes
	},
}

// Xf6c3 font data, 1081 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 2, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 1,
		Pix:    pixXf6c3, // 3 bytes
	},
}

// Xe000 font data, 1318 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 70, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 20,
		Pix:    pixXe000, // 240 bytes
	},
}

// X2713 font data, 1102 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX2713, // 24 bytes
	},
}

// X2500 font data, 2590 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 311, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 84,
		Pix:    pixX2500, // 1512 bytes
	},
}

// X2324 font data, 1294 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 62, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 18,
		Pix:    pixX2324, // 216 bytes
	},
}

// X221a font data, 1420 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 69, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 19,
		Pix:    pixX221a, // 342 bytes
	},
}

// X2116 font data, 1294 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 69, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 18,
		Pix:    pixX2116, // 216 bytes
	},
}

// X2013 font data, 1558 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 115, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 32,
		Pix:    pixX2013, // 480 bytes
	},
}

// X1e02 font data, 1942 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 171, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 48,
		Pix:    pixX1e02, // 864 bytes
	},
}

// X0490 font data, 1143 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixX0490, // 65 bytes
	},
}

// X0384 font data, 7324 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1237, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 347,
		Pix:    pixX0384, // 6246 bytes
	},
}

// X0218 font data, 1382 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 62, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 19,
		Pix:    pixX0218, // 304 bytes
	},
}

// X0101 font data, 6028 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 983, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 275,
		Pix:    pixX0101, // 4950 bytes
	},
}

// X0000 font data, 7738 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1316, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 370,
		Pix:    pixX0000, // 6660 bytes
	},
}
