// DO NOT EDIT
// Generated by: go run 9font.go -n bit/shinonome/k16.font shinonome16

package shinonome16

import (
	"image"

	"github.com/embeddedgo/display/pix"
	"github.com/embeddedgo/display/pix/font/font9"
)

// K16_005c font data, 1058 bytes, orgbpp: 1
var K16_005c = font9.Variable{
	Info: infoK16_005c, // 626 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 110, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 24,
		Pix:    pixK16_005c, // 384 bytes
	},
}

// K16_0391 font data, 1814 bytes, orgbpp: 1
var K16_0391 = font9.Variable{
	Info: infoK16_0391, // 230 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 498, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 96,
		Pix:    pixK16_0391, // 1536 bytes
	},
}

// K16_0401 font data, 2486 bytes, orgbpp: 1
var K16_0401 = font9.Variable{
	Info: infoK16_0401, // 326 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 701, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 132,
		Pix:    pixK16_0401, // 2112 bytes
	},
}

// K16_2010 font data, 2598 bytes, orgbpp: 1
var K16_2010 = font9.Variable{
	Info: infoK16_2010, // 1814 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 220, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 46,
		Pix:    pixK16_2010, // 736 bytes
	},
}

// K16_2200 font data, 2206 bytes, orgbpp: 1
var K16_2200 = font9.Variable{
	Info: infoK16_2200, // 1102 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 383, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 66,
		Pix:    pixK16_2200, // 1056 bytes
	},
}

// K16_2500 font data, 2418 bytes, orgbpp: 1
var K16_2500 = font9.Variable{
	Info: infoK16_2500, // 962 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 541, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 88,
		Pix:    pixK16_2500, // 1408 bytes
	},
}

// K16_2605 font data, 702 bytes, orgbpp: 1
var K16_2605 = font9.Variable{
	Info: infoK16_2605, // 430 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 80, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 14,
		Pix:    pixK16_2605, // 224 bytes
	},
}

// K16_3000 font data, 7438 bytes, orgbpp: 1
var K16_3000 = font9.Variable{
	Info: infoK16_3000, // 1022 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2282, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 398,
		Pix:    pixK16_3000, // 6368 bytes
	},
}

// K16_4e00 font data, 8686 bytes, orgbpp: 1
var K16_4e00 = font9.Variable{
	Info: infoK16_4e00, // 2046 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 3007, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 412,
		Pix:    pixK16_4e00, // 6592 bytes
	},
}

// K16_5005 font data, 8282 bytes, orgbpp: 1
var K16_5005 = font9.Variable{
	Info: infoK16_5005, // 2026 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2830, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 388,
		Pix:    pixK16_5005, // 6208 bytes
	},
}

// K16_5200 font data, 8990 bytes, orgbpp: 1
var K16_5200 = font9.Variable{
	Info: infoK16_5200, // 2030 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 3067, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 432,
		Pix:    pixK16_5200, // 6912 bytes
	},
}

// K16_5401 font data, 7082 bytes, orgbpp: 1
var K16_5401 = font9.Variable{
	Info: infoK16_5401, // 2042 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2287, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 312,
		Pix:    pixK16_5401, // 4992 bytes
	},
}

// K16_5606 font data, 6190 bytes, orgbpp: 1
var K16_5606 = font9.Variable{
	Info: infoK16_5606, // 2014 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1870, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 258,
		Pix:    pixK16_5606, // 4128 bytes
	},
}

// K16_5800 font data, 7602 bytes, orgbpp: 1
var K16_5800 = font9.Variable{
	Info: infoK16_5800, // 2050 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2557, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 344,
		Pix:    pixK16_5800, // 5504 bytes
	},
}

// K16_5a01 font data, 6862 bytes, orgbpp: 1
var K16_5a01 = font9.Variable{
	Info: infoK16_5a01, // 2046 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2172, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 298,
		Pix:    pixK16_5a01, // 4768 bytes
	},
}

// K16_5c01 font data, 7018 bytes, orgbpp: 1
var K16_5c01 = font9.Variable{
	Info: infoK16_5c01, // 2042 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2245, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 308,
		Pix:    pixK16_5c01, // 4928 bytes
	},
}

// K16_5e02 font data, 8842 bytes, orgbpp: 1
var K16_5e02 = font9.Variable{
	Info: infoK16_5e02, // 2042 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 3110, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 422,
		Pix:    pixK16_5e02, // 6752 bytes
	},
}

// K16_600e font data, 8346 bytes, orgbpp: 1
var K16_600e = font9.Variable{
	Info: infoK16_600e, // 1994 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2925, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 394,
		Pix:    pixK16_600e, // 6304 bytes
	},
}

// K16_6200 font data, 8222 bytes, orgbpp: 1
var K16_6200 = font9.Variable{
	Info: infoK16_6200, // 2030 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2848, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 384,
		Pix:    pixK16_6200, // 6144 bytes
	},
}

// K16_6406 font data, 7178 bytes, orgbpp: 1
var K16_6406 = font9.Variable{
	Info: infoK16_6406, // 2010 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2377, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 320,
		Pix:    pixK16_6406, // 5120 bytes
	},
}

// K16_6602 font data, 8618 bytes, orgbpp: 1
var K16_6602 = font9.Variable{
	Info: infoK16_6602, // 2042 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2999, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 408,
		Pix:    pixK16_6602, // 6528 bytes
	},
}

// K16_6802 font data, 7978 bytes, orgbpp: 1
var K16_6802 = font9.Variable{
	Info: infoK16_6802, // 2042 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2735, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 368,
		Pix:    pixK16_6802, // 5888 bytes
	},
}

// K16_6a02 font data, 6938 bytes, orgbpp: 1
var K16_6a02 = font9.Variable{
	Info: infoK16_6a02, // 1994 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2284, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 306,
		Pix:    pixK16_6a02, // 4896 bytes
	},
}

// K16_6c08 font data, 7202 bytes, orgbpp: 1
var K16_6c08 = font9.Variable{
	Info: infoK16_6c08, // 2002 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2376, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 322,
		Pix:    pixK16_6c08, // 5152 bytes
	},
}

// K16_6e05 font data, 7066 bytes, orgbpp: 1
var K16_6e05 = font9.Variable{
	Info: infoK16_6e05, // 2026 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2315, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 312,
		Pix:    pixK16_6e05, // 4992 bytes
	},
}

// K16_7001 font data, 5582 bytes, orgbpp: 1
var K16_7001 = font9.Variable{
	Info: infoK16_7001, // 2046 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1620, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 218,
		Pix:    pixK16_7001, // 3488 bytes
	},
}

// K16_7206 font data, 6230 bytes, orgbpp: 1
var K16_7206 = font9.Variable{
	Info: infoK16_7206, // 2022 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1922, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 260,
		Pix:    pixK16_7206, // 4160 bytes
	},
}

// K16_7403 font data, 7334 bytes, orgbpp: 1
var K16_7403 = font9.Variable{
	Info: infoK16_7403, // 2038 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2418, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 328,
		Pix:    pixK16_7403, // 5248 bytes
	},
}

// K16_7601 font data, 6818 bytes, orgbpp: 1
var K16_7601 = font9.Variable{
	Info: infoK16_7601, // 2034 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2190, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 296,
		Pix:    pixK16_7601, // 4736 bytes
	},
}

// K16_7802 font data, 6202 bytes, orgbpp: 1
var K16_7802 = font9.Variable{
	Info: infoK16_7802, // 2026 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1917, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 258,
		Pix:    pixK16_7802, // 4128 bytes
	},
}

// K16_7a00 font data, 7794 bytes, orgbpp: 1
var K16_7a00 = font9.Variable{
	Info: infoK16_7a00, // 2018 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2663, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 358,
		Pix:    pixK16_7a00, // 5728 bytes
	},
}

// K16_7c00 font data, 8194 bytes, orgbpp: 1
var K16_7c00 = font9.Variable{
	Info: infoK16_7c00, // 2034 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2839, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 382,
		Pix:    pixK16_7c00, // 6112 bytes
	},
}

// K16_7e01 font data, 6274 bytes, orgbpp: 1
var K16_7e01 = font9.Variable{
	Info: infoK16_7e01, // 2034 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1947, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 262,
		Pix:    pixK16_7e01, // 4192 bytes
	},
}

// K16_8000 font data, 7662 bytes, orgbpp: 1
var K16_8000 = font9.Variable{
	Info: infoK16_8000, // 2046 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2564, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 348,
		Pix:    pixK16_8000, // 5568 bytes
	},
}

// K16_8201 font data, 7398 bytes, orgbpp: 1
var K16_8201 = font9.Variable{
	Info: infoK16_8201, // 2038 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2477, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 332,
		Pix:    pixK16_8201, // 5312 bytes
	},
}

// K16_8403 font data, 6754 bytes, orgbpp: 1
var K16_8403 = font9.Variable{
	Info: infoK16_8403, // 2034 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2184, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 292,
		Pix:    pixK16_8403, // 4672 bytes
	},
}

// K16_8602 font data, 6118 bytes, orgbpp: 1
var K16_8602 = font9.Variable{
	Info: infoK16_8602, // 2038 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1869, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 252,
		Pix:    pixK16_8602, // 4032 bytes
	},
}

// K16_8805 font data, 6946 bytes, orgbpp: 1
var K16_8805 = font9.Variable{
	Info: infoK16_8805, // 2002 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2283, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 306,
		Pix:    pixK16_8805, // 4896 bytes
	},
}

// K16_8a00 font data, 6846 bytes, orgbpp: 1
var K16_8a00 = font9.Variable{
	Info: infoK16_8a00, // 1646 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2404, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 322,
		Pix:    pixK16_8a00, // 5152 bytes
	},
}

// K16_8c37 font data, 6102 bytes, orgbpp: 1
var K16_8c37 = font9.Variable{
	Info: infoK16_8c37, // 1830 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1950, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 264,
		Pix:    pixK16_8c37, // 4224 bytes
	},
}

// K16_8e08 font data, 6730 bytes, orgbpp: 1
var K16_8e08 = font9.Variable{
	Info: infoK16_8e08, // 2010 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2183, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 292,
		Pix:    pixK16_8e08, // 4672 bytes
	},
}

// K16_9000 font data, 7730 bytes, orgbpp: 1
var K16_9000 = font9.Variable{
	Info: infoK16_9000, // 2050 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2621, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 352,
		Pix:    pixK16_9000, // 5632 bytes
	},
}

// K16_920d font data, 5346 bytes, orgbpp: 1
var K16_920d = font9.Variable{
	Info: infoK16_920d, // 1906 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1576, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 212,
		Pix:    pixK16_920d, // 3392 bytes
	},
}

// K16_9403 font data, 4350 bytes, orgbpp: 1
var K16_9403 = font9.Variable{
	Info: infoK16_9403, // 1934 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1070, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 148,
		Pix:    pixK16_9403, // 2368 bytes
	},
}

// K16_961c font data, 7618 bytes, orgbpp: 1
var K16_961c = font9.Variable{
	Info: infoK16_961c, // 1938 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2544, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 352,
		Pix:    pixK16_961c, // 5632 bytes
	},
}

// K16_9801 font data, 6190 bytes, orgbpp: 1
var K16_9801 = font9.Variable{
	Info: infoK16_9801, // 2046 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1903, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 256,
		Pix:    pixK16_9801, // 4096 bytes
	},
}

// K16_9a01 font data, 5894 bytes, orgbpp: 1
var K16_9a01 = font9.Variable{
	Info: infoK16_9a01, // 2006 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1781, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 240,
		Pix:    pixK16_9a01, // 3840 bytes
	},
}

// K16_9c04 font data, 5530 bytes, orgbpp: 1
var K16_9c04 = font9.Variable{
	Info: infoK16_9c04, // 2026 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1618, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 216,
		Pix:    pixK16_9c04, // 3456 bytes
	},
}

// K16_9e1a font data, 4462 bytes, orgbpp: 1
var K16_9e1a = font9.Variable{
	Info: infoK16_9e1a, // 1566 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1323, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 178,
		Pix:    pixK16_9e1a, // 2848 bytes
	},
}

// K16_ff01 font data, 3878 bytes, orgbpp: 1
var K16_ff01 = font9.Variable{
	Info: infoK16_ff01, // 918 bytes
	Bits: &pix.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 833, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 182,
		Pix:    pixK16_ff01, // 2912 bytes
	},
}
