// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavu/dejavu.14.font

package dejavu14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 138 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 60 bytes
	},
}

// Xfb00 font data, 1306 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 74, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 19,
		Pix:    pixXfb00, // 228 bytes
	},
}

// Xf6c5 font data, 1138 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 17, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXf6c5, // 60 bytes
	},
}

// Xf400 font data, 2726 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 374, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 103,
		Pix:    pixXf400, // 1648 bytes
	},
}

// Xa746 font data, 2285 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 257, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 71,
		Pix:    pixXa746, // 1207 bytes
	},
}

// Xa644 font data, 2938 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 455, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 124,
		Pix:    pixXa644, // 1860 bytes
	},
}

// X2e18 font data, 1182 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 27, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 8,
		Pix:    pixX2e18, // 104 bytes
	},
}

// X2c60 font data, 3508 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 570, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 162,
		Pix:    pixX2c60, // 2430 bytes
	},
}

// X2b00 font data, 1962 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 262, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 68,
		Pix:    pixX2b00, // 884 bytes
	},
}

// X29eb font data, 1286 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 50, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixX29eb, // 208 bytes
	},
}

// X28a2 font data, 8970 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 890 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1675, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX28a2, // 8032 bytes
	},
}

// X27a1 font data, 7062 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1151, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 374,
		Pix:    pixX27a1, // 5984 bytes
	},
}

// X2524 font data, 9932 bytes, orgbpp: 8
var X2524 = font9.Variable{
	Info: infoX2524, // 866 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1871, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX2524, // 9018 bytes
	},
}

// X2423 font data, 2122 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 218, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 58,
		Pix:    pixX2423, // 1044 bytes
	},
}

// X1e01 font data, 10034 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 950 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1888, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX1e01, // 9036 bytes
	},
}

// X1d00 font data, 5238 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 934, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 260,
		Pix:    pixX1d00, // 4160 bytes
	},
}

// X10a0 font data, 4422 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 749, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 209,
		Pix:    pixX10a0, // 3344 bytes
	},
}

// X0101 font data, 10004 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 938 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 1942, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX0101, // 9018 bytes
	},
}

// X0000 font data, 6694 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1392, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 351,
		Pix:    pixX0000, // 5616 bytes
	},
}
