// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusansbd/dejavusansbd.16.font

package dejavusansbd16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 168 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 17, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 90 bytes
	},
}

// Xfe00 font data, 9398 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1539, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 416,
		Pix:    pixXfe00, // 8320 bytes
	},
}

// Xfb00 font data, 9898 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1658, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 441,
		Pix:    pixXfb00, // 8820 bytes
	},
}

// Xf6c5 font data, 1120 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 11, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf6c5, // 42 bytes
	},
}

// Xef00 font data, 1572 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 131, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 38,
		Pix:    pixXef00, // 494 bytes
	},
}

// Xa746 font data, 2959 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 386, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 99,
		Pix:    pixXa746, // 1881 bytes
	},
}

// Xa644 font data, 4852 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 850, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 222,
		Pix:    pixXa644, // 3774 bytes
	},
}

// X4dc0 font data, 4198 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 208,
		Pix:    pixX4dc0, // 3120 bytes
	},
}

// X2d61 font data, 1494 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 99, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 26,
		Pix:    pixX2d61, // 416 bytes
	},
}

// X2c60 font data, 5038 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 834, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 220,
		Pix:    pixX2c60, // 3960 bytes
	},
}

// X2580 font data, 10279 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 674 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1861, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2580, // 9557 bytes
	},
}

// X2422 font data, 1724 bytes, orgbpp: 8
var X2422 = font9.Variable{
	Info: infoX2422, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 142, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 38,
		Pix:    pixX2422, // 646 bytes
	},
}

// X1e01 font data, 10922 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 834 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1707, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX1e01, // 10040 bytes
	},
}

// X1d00 font data, 6195 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1072, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 301,
		Pix:    pixX1d00, // 5117 bytes
	},
}

// X1646 font data, 4973 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 754, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 205,
		Pix:    pixX1646, // 3895 bytes
	},
}

// X1401 font data, 8730 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 634 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1873, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1401, // 8048 bytes
	},
}

// X10a0 font data, 4801 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 765, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 219,
		Pix:    pixX10a0, // 3723 bytes
	},
}

// X0e3f font data, 4938 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 731, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 193,
		Pix:    pixX0e3f, // 3860 bytes
	},
}

// X07c0 font data, 3050 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 442, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 116,
		Pix:    pixX07c0, // 1972 bytes
	},
}

// X0606 font data, 10138 bytes, orgbpp: 8
var X0606 = font9.Variable{
	Info: infoX0606, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1686, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 453,
		Pix:    pixX0606, // 9060 bytes
	},
}

// X03c0 font data, 71 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 27 bytes
	},
}

// X03a9 font data, 92 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 13,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixX03a9, // 48 bytes
	},
}

// X0101 font data, 10894 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 826 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1990, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX0101, // 10020 bytes
	},
}

// X00a0 font data, 4861 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 831, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 233,
		Pix:    pixX00a0, // 4427 bytes
	},
}

// X0020 font data, 4153 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 779, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 219,
		Pix:    pixX0020, // 3723 bytes
	},
}

// X0000 font data, 72 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 28 bytes
	},
}
