// DO NOT EDIT
// Generated by: go run 9font.go -n bit/terminus/terminus.18.font

package terminus18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// X0000 font data, 56 bytes, orgbpp: 1
var X0000 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0000, // 12 bytes
	},
}

// X0020 font data, 1754 bytes, orgbpp: 1
var X0020 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 760, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 95,
		Pix:    pixX0020, // 1710 bytes
	},
}

// X00A0 font data, 4868 bytes, orgbpp: 1
var X00A0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 2140, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 268,
		Pix:    pixX00A0, // 4824 bytes
	},
}

// X0178 font data, 149 bytes, orgbpp: 1
var X0178 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX0178, // 105 bytes
	},
}

// X0186 font data, 56 bytes, orgbpp: 1
var X0186 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0186, // 12 bytes
	},
}

// X018E font data, 80 bytes, orgbpp: 1
var X018E = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 21, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX018E, // 36 bytes
	},
}

// X0192 font data, 59 bytes, orgbpp: 1
var X0192 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0192, // 15 bytes
	},
}

// X019D font data, 74 bytes, orgbpp: 1
var X019D = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 16, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX019D, // 30 bytes
	},
}

// X01B7 font data, 56 bytes, orgbpp: 1
var X01B7 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX01B7, // 12 bytes
	},
}

// X0218 font data, 104 bytes, orgbpp: 1
var X0218 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 28, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX0218, // 60 bytes
	},
}

// X0232 font data, 78 bytes, orgbpp: 1
var X0232 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0232, // 34 bytes
	},
}

// X0237 font data, 56 bytes, orgbpp: 1
var X0237 = font9.Fixed{
	Left:  -2,
	Adv:   10,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 5, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0237, // 12 bytes
	},
}

// X0254 font data, 53 bytes, orgbpp: 1
var X0254 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0254, // 9 bytes
	},
}

// X0258 font data, 62 bytes, orgbpp: 1
var X0258 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0258, // 18 bytes
	},
}

// X025B font data, 53 bytes, orgbpp: 1
var X025B = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX025B, // 9 bytes
	},
}

// X0272 font data, 56 bytes, orgbpp: 1
var X0272 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0272, // 12 bytes
	},
}

// X0292 font data, 56 bytes, orgbpp: 1
var X0292 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0292, // 12 bytes
	},
}

// X02BB font data, 50 bytes, orgbpp: 1
var X02BB = font9.Fixed{
	Left:  -3,
	Adv:   10,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 9, Y: -12},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX02BB, // 6 bytes
	},
}

// X02C6 font data, 48 bytes, orgbpp: 1
var X02C6 = font9.Fixed{
	Left:  -2,
	Adv:   10,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 10, Y: -13},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX02C6, // 4 bytes
	},
}

// X02D8 font data, 48 bytes, orgbpp: 1
var X02D8 = font9.Fixed{
	Left:  -2,
	Adv:   10,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 10, Y: -13},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX02D8, // 4 bytes
	},
}

// X02DB font data, 98 bytes, orgbpp: 1
var X02DB = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 24, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX02DB, // 54 bytes
	},
}

// X0300 font data, 52 bytes, orgbpp: 1
var X0300 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 28, Y: -13},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX0300, // 8 bytes
	},
}

// X0306 font data, 46 bytes, orgbpp: 1
var X0306 = font9.Fixed{
	Left:  -2,
	Adv:   10,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 5, Y: -13},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0306, // 2 bytes
	},
}

// X030C font data, 46 bytes, orgbpp: 1
var X030C = font9.Fixed{
	Left:  -2,
	Adv:   10,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 5, Y: -13},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX030C, // 2 bytes
	},
}

// X0329 font data, 46 bytes, orgbpp: 1
var X0329 = font9.Fixed{
	Left:  -4,
	Adv:   10,
	Width: 1,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 1},
			Max: image.Point{X: 1, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0329, // 2 bytes
	},
}

// X0384 font data, 149 bytes, orgbpp: 1
var X0384 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX0384, // 105 bytes
	},
}

// X038C font data, 58 bytes, orgbpp: 1
var X038C = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX038C, // 14 bytes
	},
}

// X038E font data, 389 bytes, orgbpp: 1
var X038E = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 180, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 23,
		Pix:    pixX038E, // 345 bytes
	},
}

// X03A3 font data, 836 bytes, orgbpp: 1
var X03A3 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 352, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 44,
		Pix:    pixX03A3, // 792 bytes
	},
}

// X03F3 font data, 74 bytes, orgbpp: 1
var X03F3 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX03F3, // 30 bytes
	},
}

// X0400 font data, 1988 bytes, orgbpp: 1
var X0400 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 864, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 108,
		Pix:    pixX0400, // 1944 bytes
	},
}

// X0490 font data, 316 bytes, orgbpp: 1
var X0490 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 126, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 16,
		Pix:    pixX0490, // 272 bytes
	},
}

// X04A0 font data, 156 bytes, orgbpp: 1
var X04A0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 60, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 8,
		Pix:    pixX04A0, // 112 bytes
	},
}

// X04AA font data, 74 bytes, orgbpp: 1
var X04AA = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04AA, // 30 bytes
	},
}

// X04AE font data, 134 bytes, orgbpp: 1
var X04AE = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 48, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX04AE, // 90 bytes
	},
}

// X04B6 font data, 128 bytes, orgbpp: 1
var X04B6 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 48, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX04B6, // 84 bytes
	},
}

// X04D0 font data, 314 bytes, orgbpp: 1
var X04D0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 144, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 18,
		Pix:    pixX04D0, // 270 bytes
	},
}

// X04E2 font data, 368 bytes, orgbpp: 1
var X04E2 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 140, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 18,
		Pix:    pixX04E2, // 324 bytes
	},
}

// X04F8 font data, 74 bytes, orgbpp: 1
var X04F8 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04F8, // 30 bytes
	},
}

// X1E34 font data, 72 bytes, orgbpp: 1
var X1E34 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1E34, // 28 bytes
	},
}

// X1EB8 font data, 74 bytes, orgbpp: 1
var X1EB8 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EB8, // 30 bytes
	},
}

// X1EBC font data, 74 bytes, orgbpp: 1
var X1EBC = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EBC, // 30 bytes
	},
}

// X1ECA font data, 104 bytes, orgbpp: 1
var X1ECA = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 28, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX1ECA, // 60 bytes
	},
}

// X1EE4 font data, 74 bytes, orgbpp: 1
var X1EE4 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EE4, // 30 bytes
	},
}

// X1EF8 font data, 80 bytes, orgbpp: 1
var X1EF8 = font9.Fixed{
	Left:  -1,
	Adv:   10,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 14, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EF8, // 36 bytes
	},
}
