// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavuit/dejavuit.18.font

package dejavuit18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 439 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 19, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 19,
		Pix:    pixXfff9, // 361 bytes
	},
}

// Xfb00 font data, 3184 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 117, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 117,
		Pix:    pixXfb00, // 2106 bytes
	},
}

// Xf6c4 font data, 2408 bytes, orgbpp: 8
var Xf6c4 = font9.Variable{
	Info: infoXf6c4, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 68, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 70,
		Pix:    pixXf6c4, // 1330 bytes
	},
}

// Xf400 font data, 12754 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 553, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 556,
		Pix:    pixXf400, // 11676 bytes
	},
}

// Xa746 font data, 9142 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 379, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 384,
		Pix:    pixXa746, // 8064 bytes
	},
}

// Xa644 font data, 13789 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 664, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 669,
		Pix:    pixXa644, // 12711 bytes
	},
}

// X2e18 font data, 1766 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 42, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 43,
		Pix:    pixX2e18, // 688 bytes
	},
}

// X2c60 font data, 18278 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 842, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 860,
		Pix:    pixX2c60, // 17200 bytes
	},
}

// X2b00 font data, 7096 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 354, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 354,
		Pix:    pixX2b00, // 6018 bytes
	},
}

// X28a2 font data, 37098 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 798 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2012, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2014,
		Pix:    pixX28a2, // 36252 bytes
	},
}

// X27a1 font data, 30642 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1554, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1556,
		Pix:    pixX27a1, // 29564 bytes
	},
}

// X2524 font data, 46965 bytes, orgbpp: 8
var X2524 = font9.Variable{
	Info: infoX2524, // 710 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 2001, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX2524, // 46207 bytes
	},
}

// X2423 font data, 7863 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 295, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 295,
		Pix:    pixX2423, // 6785 bytes
	},
}

// X1e01 font data, 46931 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 630 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1852, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2011,
		Pix:    pixX1e01, // 46253 bytes
	},
}

// X1d00 font data, 29618 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1402, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1427,
		Pix:    pixX1d00, // 28540 bytes
	},
}

// X10a0 font data, 24010 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1088, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1092,
		Pix:    pixX10a0, // 22932 bytes
	},
}

// X0000 font data, 47141 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 978 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1982, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX0000, // 46115 bytes
	},
}
