// DO NOT EDIT
// Generated by: go run 9font.go -n bit/terminus/terminus.12.font

package terminus12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// X0000 font data, 52 bytes, orgbpp: 1
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0000, // 8 bytes
	},
}

// X0020 font data, 908 bytes, orgbpp: 1
var X0020 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 570, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 72,
		Pix:    pixX0020, // 864 bytes
	},
}

// X00A0 font data, 1976 bytes, orgbpp: 1
var X00A0 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1284, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 161,
		Pix:    pixX00A0, // 1932 bytes
	},
}

// X0178 font data, 94 bytes, orgbpp: 1
var X0178 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 40, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX0178, // 50 bytes
	},
}

// X0186 font data, 52 bytes, orgbpp: 1
var X0186 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0186, // 8 bytes
	},
}

// X018E font data, 60 bytes, orgbpp: 1
var X018E = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 15, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX018E, // 16 bytes
	},
}

// X0192 font data, 54 bytes, orgbpp: 1
var X0192 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 5, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0192, // 10 bytes
	},
}

// X019D font data, 64 bytes, orgbpp: 1
var X019D = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX019D, // 20 bytes
	},
}

// X01B7 font data, 52 bytes, orgbpp: 1
var X01B7 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX01B7, // 8 bytes
	},
}

// X0218 font data, 74 bytes, orgbpp: 1
var X0218 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 20, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX0218, // 30 bytes
	},
}

// X0232 font data, 68 bytes, orgbpp: 1
var X0232 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0232, // 24 bytes
	},
}

// X0237 font data, 52 bytes, orgbpp: 1
var X0237 = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 4, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0237, // 8 bytes
	},
}

// X0254 font data, 50 bytes, orgbpp: 1
var X0254 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0254, // 6 bytes
	},
}

// X0258 font data, 56 bytes, orgbpp: 1
var X0258 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0258, // 12 bytes
	},
}

// X025B font data, 50 bytes, orgbpp: 1
var X025B = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX025B, // 6 bytes
	},
}

// X0272 font data, 52 bytes, orgbpp: 1
var X0272 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 5, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0272, // 8 bytes
	},
}

// X0292 font data, 52 bytes, orgbpp: 1
var X0292 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 5, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0292, // 8 bytes
	},
}

// X02BB font data, 46 bytes, orgbpp: 1
var X02BB = font9.Fixed{
	Left:  -2,
	Adv:   6,
	Width: 2,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02BB, // 2 bytes
	},
}

// X02C6 font data, 46 bytes, orgbpp: 1
var X02C6 = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02C6, // 2 bytes
	},
}

// X02D8 font data, 46 bytes, orgbpp: 1
var X02D8 = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02D8, // 2 bytes
	},
}

// X02DB font data, 68 bytes, orgbpp: 1
var X02DB = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 15, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX02DB, // 24 bytes
	},
}

// X0300 font data, 48 bytes, orgbpp: 1
var X0300 = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 16, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0300, // 4 bytes
	},
}

// X0306 font data, 46 bytes, orgbpp: 1
var X0306 = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 3, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0306, // 2 bytes
	},
}

// X030C font data, 46 bytes, orgbpp: 1
var X030C = font9.Fixed{
	Left:  -1,
	Adv:   6,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 3, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX030C, // 2 bytes
	},
}

// X0329 font data, 46 bytes, orgbpp: 1
var X0329 = font9.Fixed{
	Left:  -2,
	Adv:   6,
	Width: 1,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 1, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0329, // 2 bytes
	},
}

// X0384 font data, 94 bytes, orgbpp: 1
var X0384 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 35, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX0384, // 50 bytes
	},
}

// X038C font data, 54 bytes, orgbpp: 1
var X038C = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 5, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX038C, // 10 bytes
	},
}

// X038E font data, 174 bytes, orgbpp: 1
var X038E = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 100, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 13,
		Pix:    pixX038E, // 130 bytes
	},
}

// X03A3 font data, 380 bytes, orgbpp: 1
var X03A3 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 220, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 28,
		Pix:    pixX03A3, // 336 bytes
	},
}

// X03F3 font data, 66 bytes, orgbpp: 1
var X03F3 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX03F3, // 22 bytes
	},
}

// X0400 font data, 908 bytes, orgbpp: 1
var X0400 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 576, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 72,
		Pix:    pixX0400, // 864 bytes
	},
}

// X0490 font data, 176 bytes, orgbpp: 1
var X0490 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 84, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 11,
		Pix:    pixX0490, // 132 bytes
	},
}

// X04A0 font data, 94 bytes, orgbpp: 1
var X04A0 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 36, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX04A0, // 50 bytes
	},
}

// X04AA font data, 64 bytes, orgbpp: 1
var X04AA = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04AA, // 20 bytes
	},
}

// X04AE font data, 94 bytes, orgbpp: 1
var X04AE = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 36, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX04AE, // 50 bytes
	},
}

// X04B6 font data, 94 bytes, orgbpp: 1
var X04B6 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 36, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX04B6, // 50 bytes
	},
}

// X04D0 font data, 164 bytes, orgbpp: 1
var X04D0 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 96, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 12,
		Pix:    pixX04D0, // 120 bytes
	},
}

// X04E2 font data, 200 bytes, orgbpp: 1
var X04E2 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 100, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 13,
		Pix:    pixX04E2, // 156 bytes
	},
}

// X04F8 font data, 64 bytes, orgbpp: 1
var X04F8 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04F8, // 20 bytes
	},
}

// X1E34 font data, 64 bytes, orgbpp: 1
var X1E34 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1E34, // 20 bytes
	},
}

// X1EB8 font data, 64 bytes, orgbpp: 1
var X1EB8 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EB8, // 20 bytes
	},
}

// X1EBC font data, 64 bytes, orgbpp: 1
var X1EBC = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EBC, // 20 bytes
	},
}

// X1ECA font data, 77 bytes, orgbpp: 1
var X1ECA = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 20, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX1ECA, // 33 bytes
	},
}

// X1EE4 font data, 64 bytes, orgbpp: 1
var X1EE4 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EE4, // 20 bytes
	},
}

// X1EF8 font data, 68 bytes, orgbpp: 1
var X1EF8 = font9.Fixed{
	Left:  0,
	Adv:   6,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EF8, // 24 bytes
	},
}
