// DO NOT EDIT
// Generated by: go run 9font.go -n bit/shinonome/k12.font shinonome12

package shinonome12

import (
	"image"

	"github.com/embeddedgo/display/pixd"
	"github.com/embeddedgo/display/pixd/font/font9"
)

// K12_005c font data, 890 bytes, orgbpp: 1
var K12_005c = font9.Variable{
	Info: infoK12_005c, // 626 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 88, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 18,
		Pix:    pixK12_005c, // 216 bytes
	},
}

// K12_0391 font data, 1070 bytes, orgbpp: 1
var K12_0391 = font9.Variable{
	Info: infoK12_0391, // 230 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 378, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 72,
		Pix:    pixK12_0391, // 792 bytes
	},
}

// K12_0401 font data, 1562 bytes, orgbpp: 1
var K12_0401 = font9.Variable{
	Info: infoK12_0401, // 326 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 519, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 99,
		Pix:    pixK12_0401, // 1188 bytes
	},
}

// K12_2010 font data, 2282 bytes, orgbpp: 1
var K12_2010 = font9.Variable{
	Info: infoK12_2010, // 1814 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 171, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 35,
		Pix:    pixK12_2010, // 420 bytes
	},
}

// K12_2200 font data, 1750 bytes, orgbpp: 1
var K12_2200 = font9.Variable{
	Info: infoK12_2200, // 1102 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 303, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 50,
		Pix:    pixK12_2200, // 600 bytes
	},
}

// K12_2500 font data, 1802 bytes, orgbpp: 1
var K12_2500 = font9.Variable{
	Info: infoK12_2500, // 962 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 412, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 66,
		Pix:    pixK12_2500, // 792 bytes
	},
}

// K12_2605 font data, 610 bytes, orgbpp: 1
var K12_2605 = font9.Variable{
	Info: infoK12_2605, // 430 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 60, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 11,
		Pix:    pixK12_2605, // 132 bytes
	},
}

// K12_3000 font data, 4658 bytes, orgbpp: 1
var K12_3000 = font9.Variable{
	Info: infoK12_3000, // 1022 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1693, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 299,
		Pix:    pixK12_3000, // 3588 bytes
	},
}

// K12_4e00 font data, 5802 bytes, orgbpp: 1
var K12_4e00 = font9.Variable{
	Info: infoK12_4e00, // 2046 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2255, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 309,
		Pix:    pixK12_4e00, // 3708 bytes
	},
}

// K12_5005 font data, 5566 bytes, orgbpp: 1
var K12_5005 = font9.Variable{
	Info: infoK12_5005, // 2026 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2142, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 291,
		Pix:    pixK12_5005, // 3492 bytes
	},
}

// K12_5200 font data, 5966 bytes, orgbpp: 1
var K12_5200 = font9.Variable{
	Info: infoK12_5200, // 2030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2358, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 324,
		Pix:    pixK12_5200, // 3888 bytes
	},
}

// K12_5401 font data, 4898 bytes, orgbpp: 1
var K12_5401 = font9.Variable{
	Info: infoK12_5401, // 2042 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1731, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 234,
		Pix:    pixK12_5401, // 2808 bytes
	},
}

// K12_5606 font data, 4390 bytes, orgbpp: 1
var K12_5606 = font9.Variable{
	Info: infoK12_5606, // 2014 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1431, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 194,
		Pix:    pixK12_5606, // 2328 bytes
	},
}

// K12_5800 font data, 5194 bytes, orgbpp: 1
var K12_5800 = font9.Variable{
	Info: infoK12_5800, // 2050 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1913, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 258,
		Pix:    pixK12_5800, // 3096 bytes
	},
}

// K12_5a01 font data, 4782 bytes, orgbpp: 1
var K12_5a01 = font9.Variable{
	Info: infoK12_5a01, // 2046 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1656, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 224,
		Pix:    pixK12_5a01, // 2688 bytes
	},
}

// K12_5c01 font data, 4862 bytes, orgbpp: 1
var K12_5c01 = font9.Variable{
	Info: infoK12_5c01, // 2042 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1708, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 231,
		Pix:    pixK12_5c01, // 2772 bytes
	},
}

// K12_5e02 font data, 5894 bytes, orgbpp: 1
var K12_5e02 = font9.Variable{
	Info: infoK12_5e02, // 2042 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2331, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 317,
		Pix:    pixK12_5e02, // 3804 bytes
	},
}

// K12_600e font data, 5594 bytes, orgbpp: 1
var K12_600e = font9.Variable{
	Info: infoK12_600e, // 1994 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2213, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 296,
		Pix:    pixK12_600e, // 3552 bytes
	},
}

// K12_6200 font data, 5534 bytes, orgbpp: 1
var K12_6200 = font9.Variable{
	Info: infoK12_6200, // 2030 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2166, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 288,
		Pix:    pixK12_6200, // 3456 bytes
	},
}

// K12_6406 font data, 4938 bytes, orgbpp: 1
var K12_6406 = font9.Variable{
	Info: infoK12_6406, // 2010 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1788, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 240,
		Pix:    pixK12_6406, // 2880 bytes
	},
}

// K12_6602 font data, 5762 bytes, orgbpp: 1
var K12_6602 = font9.Variable{
	Info: infoK12_6602, // 2042 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2254, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 306,
		Pix:    pixK12_6602, // 3672 bytes
	},
}

// K12_6802 font data, 5402 bytes, orgbpp: 1
var K12_6802 = font9.Variable{
	Info: infoK12_6802, // 2042 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2061, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 276,
		Pix:    pixK12_6802, // 3312 bytes
	},
}

// K12_6a02 font data, 4802 bytes, orgbpp: 1
var K12_6a02 = font9.Variable{
	Info: infoK12_6a02, // 1994 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1726, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 230,
		Pix:    pixK12_6a02, // 2760 bytes
	},
}

// K12_6c08 font data, 4954 bytes, orgbpp: 1
var K12_6c08 = font9.Variable{
	Info: infoK12_6c08, // 2002 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1787, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 242,
		Pix:    pixK12_6c08, // 2904 bytes
	},
}

// K12_6e05 font data, 4882 bytes, orgbpp: 1
var K12_6e05 = font9.Variable{
	Info: infoK12_6e05, // 2026 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1752, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 234,
		Pix:    pixK12_6e05, // 2808 bytes
	},
}

// K12_7001 font data, 4062 bytes, orgbpp: 1
var K12_7001 = font9.Variable{
	Info: infoK12_7001, // 2046 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1217, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 164,
		Pix:    pixK12_7001, // 1968 bytes
	},
}

// K12_7206 font data, 4410 bytes, orgbpp: 1
var K12_7206 = font9.Variable{
	Info: infoK12_7206, // 2022 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1457, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 195,
		Pix:    pixK12_7206, // 2340 bytes
	},
}

// K12_7403 font data, 5038 bytes, orgbpp: 1
var K12_7403 = font9.Variable{
	Info: infoK12_7403, // 2038 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1814, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 246,
		Pix:    pixK12_7403, // 2952 bytes
	},
}

// K12_7601 font data, 4746 bytes, orgbpp: 1
var K12_7601 = font9.Variable{
	Info: infoK12_7601, // 2034 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1645, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 222,
		Pix:    pixK12_7601, // 2664 bytes
	},
}

// K12_7802 font data, 4402 bytes, orgbpp: 1
var K12_7802 = font9.Variable{
	Info: infoK12_7802, // 2026 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1442, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 194,
		Pix:    pixK12_7802, // 2328 bytes
	},
}

// K12_7a00 font data, 5294 bytes, orgbpp: 1
var K12_7a00 = font9.Variable{
	Info: infoK12_7a00, // 2018 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1980, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 269,
		Pix:    pixK12_7a00, // 3228 bytes
	},
}

// K12_7c00 font data, 5526 bytes, orgbpp: 1
var K12_7c00 = font9.Variable{
	Info: infoK12_7c00, // 2034 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2123, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 287,
		Pix:    pixK12_7c00, // 3444 bytes
	},
}

// K12_7e01 font data, 4446 bytes, orgbpp: 1
var K12_7e01 = font9.Variable{
	Info: infoK12_7e01, // 2034 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1471, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 197,
		Pix:    pixK12_7e01, // 2364 bytes
	},
}

// K12_8000 font data, 5226 bytes, orgbpp: 1
var K12_8000 = font9.Variable{
	Info: infoK12_8000, // 2046 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1934, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 261,
		Pix:    pixK12_8000, // 3132 bytes
	},
}

// K12_8201 font data, 5074 bytes, orgbpp: 1
var K12_8201 = font9.Variable{
	Info: infoK12_8201, // 2038 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1836, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 249,
		Pix:    pixK12_8201, // 2988 bytes
	},
}

// K12_8403 font data, 4710 bytes, orgbpp: 1
var K12_8403 = font9.Variable{
	Info: infoK12_8403, // 2034 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1624, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 219,
		Pix:    pixK12_8403, // 2628 bytes
	},
}

// K12_8602 font data, 4354 bytes, orgbpp: 1
var K12_8602 = font9.Variable{
	Info: infoK12_8602, // 2038 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1413, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 189,
		Pix:    pixK12_8602, // 2268 bytes
	},
}

// K12_8805 font data, 4810 bytes, orgbpp: 1
var K12_8805 = font9.Variable{
	Info: infoK12_8805, // 2002 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1724, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 230,
		Pix:    pixK12_8805, // 2760 bytes
	},
}

// K12_8a00 font data, 4598 bytes, orgbpp: 1
var K12_8a00 = font9.Variable{
	Info: infoK12_8a00, // 1646 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1793, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 242,
		Pix:    pixK12_8a00, // 2904 bytes
	},
}

// K12_8c37 font data, 4254 bytes, orgbpp: 1
var K12_8c37 = font9.Variable{
	Info: infoK12_8c37, // 1830 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1473, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 198,
		Pix:    pixK12_8c37, // 2376 bytes
	},
}

// K12_8e08 font data, 4686 bytes, orgbpp: 1
var K12_8e08 = font9.Variable{
	Info: infoK12_8e08, // 2010 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1660, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 219,
		Pix:    pixK12_8e08, // 2628 bytes
	},
}

// K12_9000 font data, 5266 bytes, orgbpp: 1
var K12_9000 = font9.Variable{
	Info: infoK12_9000, // 2050 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 2031, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 264,
		Pix:    pixK12_9000, // 3168 bytes
	},
}

// K12_920d font data, 3862 bytes, orgbpp: 1
var K12_920d = font9.Variable{
	Info: infoK12_920d, // 1906 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1190, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 159,
		Pix:    pixK12_920d, // 1908 bytes
	},
}

// K12_9403 font data, 3314 bytes, orgbpp: 1
var K12_9403 = font9.Variable{
	Info: infoK12_9403, // 1934 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 827, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 111,
		Pix:    pixK12_9403, // 1332 bytes
	},
}

// K12_961c font data, 5154 bytes, orgbpp: 1
var K12_961c = font9.Variable{
	Info: infoK12_961c, // 1938 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1956, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 264,
		Pix:    pixK12_961c, // 3168 bytes
	},
}

// K12_9801 font data, 4398 bytes, orgbpp: 1
var K12_9801 = font9.Variable{
	Info: infoK12_9801, // 2046 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1442, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 192,
		Pix:    pixK12_9801, // 2304 bytes
	},
}

// K12_9a01 font data, 4214 bytes, orgbpp: 1
var K12_9a01 = font9.Variable{
	Info: infoK12_9a01, // 2006 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1349, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 180,
		Pix:    pixK12_9a01, // 2160 bytes
	},
}

// K12_9c04 font data, 4018 bytes, orgbpp: 1
var K12_9c04 = font9.Variable{
	Info: infoK12_9c04, // 2026 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1212, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 162,
		Pix:    pixK12_9c04, // 1944 bytes
	},
}

// K12_9e1a font data, 3222 bytes, orgbpp: 1
var K12_9e1a = font9.Variable{
	Info: infoK12_9e1a, // 1566 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 999, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 134,
		Pix:    pixK12_9e1a, // 1608 bytes
	},
}

// K12_ff01 font data, 2610 bytes, orgbpp: 1
var K12_ff01 = font9.Variable{
	Info: infoK12_ff01, // 918 bytes
	Bits: &pixd.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 633, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 137,
		Pix:    pixK12_ff01, // 1644 bytes
	},
}
