// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavu/dejavu.18.font

package dejavu18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 439 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 19, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 19,
		Pix:    pixXfff9, // 361 bytes
	},
}

// Xfb00 font data, 2548 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 98, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 98,
		Pix:    pixXfb00, // 1470 bytes
	},
}

// Xf6c5 font data, 1423 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 23, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 23,
		Pix:    pixXf6c5, // 345 bytes
	},
}

// Xf400 font data, 10818 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 486, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 487,
		Pix:    pixXf400, // 9740 bytes
	},
}

// Xa746 font data, 8844 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 353, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 353,
		Pix:    pixXa746, // 7766 bytes
	},
}

// Xa644 font data, 12858 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 615, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 620,
		Pix:    pixXa644, // 11780 bytes
	},
}

// X2e18 font data, 1690 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 36, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 36,
		Pix:    pixX2e18, // 612 bytes
	},
}

// X2c60 font data, 16031 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 775, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 787,
		Pix:    pixX2c60, // 14953 bytes
	},
}

// X2b00 font data, 7147 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 357, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 357,
		Pix:    pixX2b00, // 6069 bytes
	},
}

// X28a2 font data, 39057 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 762 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 2002, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2013,
		Pix:    pixX28a2, // 38247 bytes
	},
}

// X27a1 font data, 35258 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1709, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1709,
		Pix:    pixX27a1, // 34180 bytes
	},
}

// X1e01 font data, 46821 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 750 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1891, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2001,
		Pix:    pixX1e01, // 46023 bytes
	},
}

// X1d00 font data, 27418 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1315, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1317,
		Pix:    pixX1d00, // 26340 bytes
	},
}

// X10a0 font data, 23338 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1059, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1060,
		Pix:    pixX10a0, // 22260 bytes
	},
}

// X0101 font data, 44942 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 762 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1971, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2006,
		Pix:    pixX0101, // 44132 bytes
	},
}

// X0000 font data, 38458 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1769, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1780,
		Pix:    pixX0000, // 37380 bytes
	},
}
