// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusansit/dejavusansit.12.font

package dejavusansit12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 126 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 12, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 48 bytes
	},
}

// Xfe00 font data, 1099 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 19, Y: -9},
		},
		LogN:   1, // 2 bpp
		Stride: 7,
		Pix:    pixXfe00, // 21 bytes
	},
}

// Xfb00 font data, 2638 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 442, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 120,
		Pix:    pixXfb00, // 1560 bytes
	},
}

// Xf6c5 font data, 1100 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixXf6c5, // 22 bytes
	},
}

// Xef00 font data, 1368 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 91, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 29,
		Pix:    pixXef00, // 290 bytes
	},
}

// Xa746 font data, 2128 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 260, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 70,
		Pix:    pixXa746, // 1050 bytes
	},
}

// Xa644 font data, 3288 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 617, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 170,
		Pix:    pixXa644, // 2210 bytes
	},
}

// X4dc0 font data, 2806 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 576, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 144,
		Pix:    pixX4dc0, // 1728 bytes
	},
}

// X2e18 font data, 1174 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 23, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 8,
		Pix:    pixX2e18, // 96 bytes
	},
}

// X2c60 font data, 1910 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 234, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 64,
		Pix:    pixX2c60, // 832 bytes
	},
}

// X2a7d font data, 3483 bytes, orgbpp: 8
var X2a7d = font9.Variable{
	Info: infoX2a7d, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 719, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 185,
		Pix:    pixX2a7d, // 2405 bytes
	},
}

// X2940 font data, 2100 bytes, orgbpp: 8
var X2940 = font9.Variable{
	Info: infoX2940, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 273, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 73,
		Pix:    pixX2940, // 1022 bytes
	},
}

// X2523 font data, 8521 bytes, orgbpp: 8
var X2523 = font9.Variable{
	Info: infoX2523, // 958 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1830, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX2523, // 7515 bytes
	},
}

// X2422 font data, 2263 bytes, orgbpp: 8
var X2422 = font9.Variable{
	Info: infoX2422, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 284, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 79,
		Pix:    pixX2422, // 1185 bytes
	},
}

// X2104 font data, 8044 bytes, orgbpp: 8
var X2104 = font9.Variable{
	Info: infoX2104, // 954 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1888, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2104, // 7042 bytes
	},
}

// X2003 font data, 4753 bytes, orgbpp: 8
var X2003 = font9.Variable{
	Info: infoX2003, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 889, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 245,
		Pix:    pixX2003, // 3675 bytes
	},
}

// X1f02 font data, 8218 bytes, orgbpp: 8
var X1f02 = font9.Variable{
	Info: infoX1f02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1758, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 476,
		Pix:    pixX1f02, // 7140 bytes
	},
}

// X1e01 font data, 8578 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1700, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 500,
		Pix:    pixX1e01, // 7500 bytes
	},
}

// X1d00 font data, 3964 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 789, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 222,
		Pix:    pixX1d00, // 2886 bytes
	},
}

// X1646 font data, 1546 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 144, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 39,
		Pix:    pixX1646, // 468 bytes
	},
}

// X1401 font data, 6990 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 906 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1820, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1401, // 6036 bytes
	},
}

// X10a0 font data, 3184 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 590, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 162,
		Pix:    pixX10a0, // 2106 bytes
	},
}

// X0e3f font data, 3148 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 476, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 138,
		Pix:    pixX0e3f, // 2070 bytes
	},
}

// X03c0 font data, 56 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   7,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX03c0, // 12 bytes
	},
}

// X03a9 font data, 62 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   9,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX03a9, // 18 bytes
	},
}

// X0101 font data, 8573 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1010 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1864, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX0101, // 7515 bytes
	},
}

// X00a0 font data, 3164 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 606, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 182,
		Pix:    pixX00a0, // 2730 bytes
	},
}

// X0020 font data, 2744 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 588, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 178,
		Pix:    pixX0020, // 2314 bytes
	},
}

// X0000 font data, 66 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   7,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 6, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 22 bytes
	},
}
