// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavuit/dejavuit.12.font

package dejavuit12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 130 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixXfff9, // 52 bytes
	},
}

// Xfb00 font data, 1338 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 74, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 20,
		Pix:    pixXfb00, // 260 bytes
	},
}

// Xf6c4 font data, 1234 bytes, orgbpp: 8
var Xf6c4 = font9.Variable{
	Info: infoXf6c4, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 40, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixXf6c4, // 156 bytes
	},
}

// Xf400 font data, 2380 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 357, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 93,
		Pix:    pixXf400, // 1302 bytes
	},
}

// Xa746 font data, 2083 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 244, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 67,
		Pix:    pixXa746, // 1005 bytes
	},
}

// Xa644 font data, 2573 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 425, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 115,
		Pix:    pixXa644, // 1495 bytes
	},
}

// X2e18 font data, 1155 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 26, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 7,
		Pix:    pixX2e18, // 77 bytes
	},
}

// X2c60 font data, 3028 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 533, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 150,
		Pix:    pixX2c60, // 1950 bytes
	},
}

// X2b00 font data, 1727 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 218, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 59,
		Pix:    pixX2b00, // 649 bytes
	},
}

// X29eb font data, 1234 bytes, orgbpp: 8
var X29eb = font9.Variable{
	Info: infoX29eb, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 40, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixX29eb, // 156 bytes
	},
}

// X28a2 font data, 5614 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 1435, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 378,
		Pix:    pixX28a2, // 4536 bytes
	},
}

// X27a1 font data, 4328 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 975, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 250,
		Pix:    pixX27a1, // 3250 bytes
	},
}

// X2638 font data, 1726 bytes, orgbpp: 8
var X2638 = font9.Variable{
	Info: infoX2638, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 208, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 54,
		Pix:    pixX2638, // 648 bytes
	},
}

// X2524 font data, 7588 bytes, orgbpp: 8
var X2524 = font9.Variable{
	Info: infoX2524, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1622, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 434,
		Pix:    pixX2524, // 6510 bytes
	},
}

// X2423 font data, 1798 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 179, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 48,
		Pix:    pixX2423, // 720 bytes
	},
}

// X1e01 font data, 8469 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 906 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1439, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1e01, // 7515 bytes
	},
}

// X1d00 font data, 4578 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 868, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 250,
		Pix:    pixX1d00, // 3500 bytes
	},
}

// X10a0 font data, 3766 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 695, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 192,
		Pix:    pixX10a0, // 2688 bytes
	},
}

// X0101 font data, 8496 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 918 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1643, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 7530 bytes
	},
}

// X0000 font data, 6628 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1275, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 370,
		Pix:    pixX0000, // 5550 bytes
	},
}
