// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/anonpro/anonpro.14.font

package anonpro14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1238 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 16,
		Pix:    pixXfb01, // 160 bytes
	},
}

// Xf8ff font data, 1265 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 17, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 17,
		Pix:    pixXf8ff, // 187 bytes
	},
}

// Xf6c3 font data, 1084 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 1},
			Max: image.Point{X: 3, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 3,
		Pix:    pixXf6c3, // 6 bytes
	},
}

// Xe000 font data, 1738 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 60, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 60,
		Pix:    pixXe000, // 660 bytes
	},
}

// X2713 font data, 1134 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 8, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixX2713, // 56 bytes
	},
}

// X2500 font data, 4872 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 266, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 271,
		Pix:    pixX2500, // 3794 bytes
	},
}

// X2324 font data, 1672 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 54, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 54,
		Pix:    pixX2324, // 594 bytes
	},
}

// X221a font data, 1918 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 58, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 60,
		Pix:    pixX221a, // 840 bytes
	},
}

// X2116 font data, 1638 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 56,
		Pix:    pixX2116, // 560 bytes
	},
}

// X2013 font data, 2391 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 100, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 101,
		Pix:    pixX2013, // 1313 bytes
	},
}

// X1e02 font data, 3164 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 149, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 149,
		Pix:    pixX1e02, // 2086 bytes
	},
}

// X0490 font data, 1210 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixX0490, // 132 bytes
	},
}

// X0384 font data, 15974 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1046, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1064,
		Pix:    pixX0384, // 14896 bytes
	},
}

// X0218 font data, 1918 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 60, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 60,
		Pix:    pixX0218, // 840 bytes
	},
}

// X0101 font data, 13048 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 833, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 855,
		Pix:    pixX0101, // 11970 bytes
	},
}

// X0000 font data, 17150 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 1130, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1148,
		Pix:    pixX0000, // 16072 bytes
	},
}
