// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/vga/vga.font

package vga

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// X0000 font data, 1964 bytes, orgbpp: 1
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1024, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 128,
		Pix:    pixX0000, // 1920 bytes
	},
}

// X00A0 font data, 6188 bytes, orgbpp: 1
var X00A0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 3072, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 384,
		Pix:    pixX00A0, // 6144 bytes
	},
}

// X0222 font data, 284 bytes, orgbpp: 1
var X0222 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 126, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 16,
		Pix:    pixX0222, // 240 bytes
	},
}

// X0250 font data, 1266 bytes, orgbpp: 1
var X0250 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 752, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 94,
		Pix:    pixX0250, // 1222 bytes
	},
}

// X02B0 font data, 436 bytes, orgbpp: 1
var X02B0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 224, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 28,
		Pix:    pixX02B0, // 392 bytes
	},
}

// X02D8 font data, 128 bytes, orgbpp: 1
var X02D8 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 42, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX02D8, // 84 bytes
	},
}

// X02EE font data, 48 bytes, orgbpp: 1
var X02EE = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 5, Y: -7},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02EE, // 4 bytes
	},
}

// X0300 font data, 48 bytes, orgbpp: 1
var X0300 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 10, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0300, // 4 bytes
	},
}

// X0303 font data, 46 bytes, orgbpp: 1
var X0303 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 5, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0303, // 2 bytes
	},
}

// X0309 font data, 47 bytes, orgbpp: 1
var X0309 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 4, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0309, // 3 bytes
	},
}

// X0312 font data, 50 bytes, orgbpp: 1
var X0312 = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 9, Y: -8},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0312, // 6 bytes
	},
}

// X0323 font data, 46 bytes, orgbpp: 1
var X0323 = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 2,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 1},
			Max: image.Point{X: 2, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0323, // 2 bytes
	},
}

// X0340 font data, 48 bytes, orgbpp: 1
var X0340 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 16, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0340, // 4 bytes
	},
}

// X0374 font data, 56 bytes, orgbpp: 1
var X0374 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 6, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0374, // 12 bytes
	},
}

// X037A font data, 47 bytes, orgbpp: 1
var X037A = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 4, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX037A, // 3 bytes
	},
}

// X037E font data, 52 bytes, orgbpp: 1
var X037E = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 3, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX037E, // 8 bytes
	},
}

// X0384 font data, 128 bytes, orgbpp: 1
var X0384 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX0384, // 84 bytes
	},
}

// X038C font data, 56 bytes, orgbpp: 1
var X038C = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX038C, // 12 bytes
	},
}

// X038E font data, 284 bytes, orgbpp: 1
var X038E = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 160, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 20,
		Pix:    pixX038E, // 240 bytes
	},
}

// X03A3 font data, 629 bytes, orgbpp: 1
var X03A3 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 308, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 39,
		Pix:    pixX03A3, // 585 bytes
	},
}

// X03D0 font data, 164 bytes, orgbpp: 1
var X03D0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 64, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 8,
		Pix:    pixX03D0, // 120 bytes
	},
}

// X03DA font data, 408 bytes, orgbpp: 1
var X03DA = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 208, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 26,
		Pix:    pixX03DA, // 364 bytes
	},
}

// X0400 font data, 2069 bytes, orgbpp: 1
var X0400 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1080, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 135,
		Pix:    pixX0400, // 2025 bytes
	},
}

// X0488 font data, 1109 bytes, orgbpp: 1
var X0488 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 568, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 71,
		Pix:    pixX0488, // 1065 bytes
	},
}

// X04D0 font data, 554 bytes, orgbpp: 1
var X04D0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 266, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 34,
		Pix:    pixX04D0, // 510 bytes
	},
}

// X04F8 font data, 68 bytes, orgbpp: 1
var X04F8 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04F8, // 24 bytes
	},
}

// X0500 font data, 236 bytes, orgbpp: 1
var X0500 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 128, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 16,
		Pix:    pixX0500, // 192 bytes
	},
}

// X0530 font data, 473 bytes, orgbpp: 1
var X0530 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 312, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 39,
		Pix:    pixX0530, // 429 bytes
	},
}

// X0559 font data, 68 bytes, orgbpp: 1
var X0559 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 42, Y: -7},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX0559, // 24 bytes
	},
}

// X0561 font data, 551 bytes, orgbpp: 1
var X0561 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 312, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 39,
		Pix:    pixX0561, // 507 bytes
	},
}

// X0589 font data, 58 bytes, orgbpp: 1
var X0589 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0589, // 14 bytes
	},
}

// X0591 font data, 316 bytes, orgbpp: 1
var X0591 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 136, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 17,
		Pix:    pixX0591, // 272 bytes
	},
}

// X05A3 font data, 412 bytes, orgbpp: 1
var X05A3 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 184, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 23,
		Pix:    pixX05A3, // 368 bytes
	},
}

// X05BB font data, 194 bytes, orgbpp: 1
var X05BB = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 80, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 10,
		Pix:    pixX05BB, // 150 bytes
	},
}

// X05D0 font data, 356 bytes, orgbpp: 1
var X05D0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 189, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 24,
		Pix:    pixX05D0, // 312 bytes
	},
}

// X05F0 font data, 94 bytes, orgbpp: 1
var X05F0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 35, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX05F0, // 50 bytes
	},
}

// X060C font data, 48 bytes, orgbpp: 1
var X060C = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 2,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 2, Y: -3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX060C, // 4 bytes
	},
}

// X061B font data, 52 bytes, orgbpp: 1
var X061B = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 3,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 3, Y: -2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX061B, // 8 bytes
	},
}

// X061F font data, 52 bytes, orgbpp: 1
var X061F = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 5, Y: -2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX061F, // 8 bytes
	},
}

// X0621 font data, 408 bytes, orgbpp: 1
var X0621 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 208, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 26,
		Pix:    pixX0621, // 364 bytes
	},
}

// X0640 font data, 396 bytes, orgbpp: 1
var X0640 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 176, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 22,
		Pix:    pixX0640, // 352 bytes
	},
}

// X0660 font data, 226 bytes, orgbpp: 1
var X0660 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 112, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 14,
		Pix:    pixX0660, // 182 bytes
	},
}

// X0670 font data, 2060 bytes, orgbpp: 1
var X0670 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1008, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 126,
		Pix:    pixX0670, // 2016 bytes
	},
}

// X06F0 font data, 239 bytes, orgbpp: 1
var X06F0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 120, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 15,
		Pix:    pixX06F0, // 195 bytes
	},
}

// X10D3 font data, 54 bytes, orgbpp: 1
var X10D3 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX10D3, // 10 bytes
	},
}

// X10D7 font data, 51 bytes, orgbpp: 1
var X10D7 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX10D7, // 7 bytes
	},
}

// X10DA font data, 54 bytes, orgbpp: 1
var X10DA = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX10DA, // 10 bytes
	},
}

// X10DD font data, 51 bytes, orgbpp: 1
var X10DD = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX10DD, // 7 bytes
	},
}

// X10E6 font data, 54 bytes, orgbpp: 1
var X10E6 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX10E6, // 10 bytes
	},
}

// X1E00 font data, 2236 bytes, orgbpp: 1
var X1E00 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1092, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 137,
		Pix:    pixX1E00, // 2192 bytes
	},
}

// X1EA0 font data, 1394 bytes, orgbpp: 1
var X1EA0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 720, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 90,
		Pix:    pixX1EA0, // 1350 bytes
	},
}

// X1F00 font data, 128 bytes, orgbpp: 1
var X1F00 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX1F00, // 84 bytes
	},
}

// X2000 font data, 644 bytes, orgbpp: 1
var X2000 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 320, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 40,
		Pix:    pixX2000, // 600 bytes
	},
}

// X2030 font data, 389 bytes, orgbpp: 1
var X2030 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 184, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 23,
		Pix:    pixX2030, // 345 bytes
	},
}

// X2048 font data, 110 bytes, orgbpp: 1
var X2048 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 48, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX2048, // 66 bytes
	},
}

// X2070 font data, 50 bytes, orgbpp: 1
var X2070 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 5, Y: -5},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2070, // 6 bytes
	},
}

// X2074 font data, 296 bytes, orgbpp: 1
var X2074 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 168, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 21,
		Pix:    pixX2074, // 252 bytes
	},
}

// X20A0 font data, 268 bytes, orgbpp: 1
var X20A0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 128, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 16,
		Pix:    pixX20A0, // 224 bytes
	},
}

// X2100 font data, 929 bytes, orgbpp: 1
var X2100 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 472, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 59,
		Pix:    pixX2100, // 885 bytes
	},
}

// X2153 font data, 681 bytes, orgbpp: 1
var X2153 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 392, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 49,
		Pix:    pixX2153, // 637 bytes
	},
}

// X2190 font data, 1244 bytes, orgbpp: 1
var X2190 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 800, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 100,
		Pix:    pixX2190, // 1200 bytes
	},
}

// X2200 font data, 3432 bytes, orgbpp: 1
var X2200 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1936, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 242,
		Pix:    pixX2200, // 3388 bytes
	},
}

// X2300 font data, 52 bytes, orgbpp: 1
var X2300 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2300, // 8 bytes
	},
}

// X2302 font data, 51 bytes, orgbpp: 1
var X2302 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 7, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2302, // 7 bytes
	},
}

// X2308 font data, 92 bytes, orgbpp: 1
var X2308 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 24, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX2308, // 48 bytes
	},
}

// X2310 font data, 49 bytes, orgbpp: 1
var X2310 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 7, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2310, // 5 bytes
	},
}

// X2318 font data, 52 bytes, orgbpp: 1
var X2318 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 8, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2318, // 8 bytes
	},
}

// X231A font data, 66 bytes, orgbpp: 1
var X231A = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX231A, // 22 bytes
	},
}

// X2320 font data, 76 bytes, orgbpp: 1
var X2320 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 16, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX2320, // 32 bytes
	},
}

// X2329 font data, 72 bytes, orgbpp: 1
var X2329 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 10, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX2329, // 28 bytes
	},
}

// X239B font data, 604 bytes, orgbpp: 1
var X239B = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 280, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 35,
		Pix:    pixX239B, // 560 bytes
	},
}

// X23CE font data, 54 bytes, orgbpp: 1
var X23CE = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX23CE, // 10 bytes
	},
}

// X2409 font data, 94 bytes, orgbpp: 1
var X2409 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 40, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 5,
		Pix:    pixX2409, // 50 bytes
	},
}

// X2423 font data, 64 bytes, orgbpp: 1
var X2423 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 16, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX2423, // 20 bytes
	},
}

// X2426 font data, 54 bytes, orgbpp: 1
var X2426 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2426, // 10 bytes
	},
}

// X2500 font data, 2444 bytes, orgbpp: 1
var X2500 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1200, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 150,
		Pix:    pixX2500, // 2400 bytes
	},
}

// X25A0 font data, 1452 bytes, orgbpp: 1
var X25A0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 704, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 88,
		Pix:    pixX25A0, // 1408 bytes
	},
}

// X2600 font data, 71 bytes, orgbpp: 1
var X2600 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 24, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX2600, // 27 bytes
	},
}

// X2605 font data, 134 bytes, orgbpp: 1
var X2605 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 72, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 9,
		Pix:    pixX2605, // 90 bytes
	},
}

// X2610 font data, 80 bytes, orgbpp: 1
var X2610 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 28, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX2610, // 36 bytes
	},
}

// X2620 font data, 58 bytes, orgbpp: 1
var X2620 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 7, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2620, // 14 bytes
	},
}

// X2622 font data, 52 bytes, orgbpp: 1
var X2622 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 7, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2622, // 8 bytes
	},
}

// X2626 font data, 54 bytes, orgbpp: 1
var X2626 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX2626, // 10 bytes
	},
}

// X2628 font data, 84 bytes, orgbpp: 1
var X2628 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 32, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX2628, // 40 bytes
	},
}

// X262E font data, 144 bytes, orgbpp: 1
var X262E = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 80, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 10,
		Pix:    pixX262E, // 100 bytes
	},
}

// X2639 font data, 395 bytes, orgbpp: 1
var X2639 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 216, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 27,
		Pix:    pixX2639, // 351 bytes
	},
}

// X2660 font data, 116 bytes, orgbpp: 1
var X2660 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 64, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 8,
		Pix:    pixX2660, // 72 bytes
	},
}

// X2669 font data, 128 bytes, orgbpp: 1
var X2669 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 56, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX2669, // 84 bytes
	},
}

// X29FA font data, 49 bytes, orgbpp: 1
var X29FA = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: -2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX29FA, // 5 bytes
	},
}

// XFB00 font data, 104 bytes, orgbpp: 1
var XFB00 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 48, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixXFB00, // 60 bytes
	},
}

// XFB50 font data, 1416 bytes, orgbpp: 1
var XFB50 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 784, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 98,
		Pix:    pixXFB50, // 1372 bytes
	},
}

// XFBD3 font data, 412 bytes, orgbpp: 1
var XFBD3 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 184, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 23,
		Pix:    pixXFBD3, // 368 bytes
	},
}

// XFBFC font data, 76 bytes, orgbpp: 1
var XFBFC = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 32, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixXFBFC, // 32 bytes
	},
}

// XFC5B font data, 152 bytes, orgbpp: 1
var XFC5B = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 72, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 9,
		Pix:    pixXFC5B, // 108 bytes
	},
}

// XFC90 font data, 57 bytes, orgbpp: 1
var XFC90 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 8, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFC90, // 13 bytes
	},
}

// XFCF2 font data, 71 bytes, orgbpp: 1
var XFCF2 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 24, Y: -3},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixXFCF2, // 27 bytes
	},
}

// XFD3C font data, 88 bytes, orgbpp: 1
var XFD3C = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 28, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixXFD3C, // 44 bytes
	},
}

// XFDF2 font data, 52 bytes, orgbpp: 1
var XFDF2 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: -3},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFDF2, // 8 bytes
	},
}

// XFE50 font data, 46 bytes, orgbpp: 1
var XFE50 = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 2,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -3},
			Max: image.Point{X: 6, Y: -1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFE50, // 2 bytes
	},
}

// XFE54 font data, 149 bytes, orgbpp: 1
var XFE54 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 114, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 15,
		Pix:    pixXFE54, // 105 bytes
	},
}

// XFE68 font data, 68 bytes, orgbpp: 1
var XFE68 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 20, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixXFE68, // 24 bytes
	},
}

// XFE70 font data, 71 bytes, orgbpp: 1
var XFE70 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 24, Y: -3},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixXFE70, // 27 bytes
	},
}

// XFE74 font data, 48 bytes, orgbpp: 1
var XFE74 = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -2},
			Max: image.Point{X: 4, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFE74, // 4 bytes
	},
}

// XFE76 font data, 2069 bytes, orgbpp: 1
var XFE76 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1080, Y: 3},
		},
		LogN:   0, // 1 bpp
		Stride: 135,
		Pix:    pixXFE76, // 2025 bytes
	},
}

// XFEFF font data, 60 bytes, orgbpp: 1
var XFEFF = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 8, Y: 4},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFEFF, // 16 bytes
	},
}

// XFFFD font data, 56 bytes, orgbpp: 1
var XFFFD = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 7, Y: 1},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixXFFFD, // 12 bytes
	},
}
