// DO NOT EDIT
// Generated by: go run 9font.go -n bit/vga/vga.font

package vga

import "github.com/embeddedgo/display/font/subfont"

const (
	Height = 16
	Ascent = 12
)

// X0000_007f subfont, n=128,  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO
var X0000_007f = subfont.Subfont{
	First:  0x0000,
	Last:   0x007f,
	Offset: 0,
	Data:   &X0000,
}

// X00a0_021f subfont, n=384, ¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑ
var X00a0_021f = subfont.Subfont{
	First:  0x00a0,
	Last:   0x021f, // 'ȟ'
	Offset: 0,
	Data:   &X00A0,
}

// X0222_0233 subfont, n=18, ȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱȲ
var X0222_0233 = subfont.Subfont{
	First:  0x0222, // 'Ȣ'
	Last:   0x0233, // 'ȳ'
	Offset: 0,
	Data:   &X0222,
}

// X0250_02ad subfont, n=94, ɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟɠɡɢɣɤɥɦɧɨɩɪɫɬɭɮɯɰɱɲɳɴɵɶɷɸɹɺɻɼɽɾɿ
var X0250_02ad = subfont.Subfont{
	First:  0x0250, // 'ɐ'
	Last:   0x02ad, // 'ʭ'
	Offset: 0,
	Data:   &X0250,
}

// X02b0_02cf subfont, n=32, ʰʱʲʳʴʵʶʷʸʹʺʻʼʽʾʿˀˁ˂˃˄˅ˆˇˈˉˊˋˌˍˎ
var X02b0_02cf = subfont.Subfont{
	First:  0x02b0, // 'ʰ'
	Last:   0x02cf, // 'ˏ'
	Offset: 0,
	Data:   &X02B0,
}

// X02d8_02dd subfont, n=6, ˘˙˚˛˜
var X02d8_02dd = subfont.Subfont{
	First:  0x02d8, // '˘'
	Last:   0x02dd, // '˝'
	Offset: 0,
	Data:   &X02D8,
}

// X02ee_02ee subfont, n=1, 
var X02ee_02ee = subfont.Subfont{
	First:  0x02ee, // 'ˮ'
	Last:   0x02ee, // 'ˮ'
	Offset: 0,
	Data:   &X02EE,
}

// X0300_0301 subfont, n=2, ̀
var X0300_0301 = subfont.Subfont{
	First:  0x0300, // '̀'
	Last:   0x0301, // '́'
	Offset: 0,
	Data:   &X0300,
}

// X0303_0303 subfont, n=1, 
var X0303_0303 = subfont.Subfont{
	First:  0x0303, // '̃'
	Last:   0x0303, // '̃'
	Offset: 0,
	Data:   &X0303,
}

// X0309_0309 subfont, n=1, 
var X0309_0309 = subfont.Subfont{
	First:  0x0309, // '̉'
	Last:   0x0309, // '̉'
	Offset: 0,
	Data:   &X0309,
}

// X0312_0314 subfont, n=3, ̒̓
var X0312_0314 = subfont.Subfont{
	First:  0x0312, // '̒'
	Last:   0x0314, // '̔'
	Offset: 0,
	Data:   &X0312,
}

// X0323_0323 subfont, n=1, 
var X0323_0323 = subfont.Subfont{
	First:  0x0323, // '̣'
	Last:   0x0323, // '̣'
	Offset: 0,
	Data:   &X0323,
}

// X0340_0341 subfont, n=2, ̀
var X0340_0341 = subfont.Subfont{
	First:  0x0340, // '̀'
	Last:   0x0341, // '́'
	Offset: 0,
	Data:   &X0340,
}

// X0374_0375 subfont, n=2, ʹ
var X0374_0375 = subfont.Subfont{
	First:  0x0374, // 'ʹ'
	Last:   0x0375, // '͵'
	Offset: 0,
	Data:   &X0374,
}

// X037a_037a subfont, n=1, 
var X037a_037a = subfont.Subfont{
	First:  0x037a, // 'ͺ'
	Last:   0x037a, // 'ͺ'
	Offset: 0,
	Data:   &X037A,
}

// X037e_037e subfont, n=1, 
var X037e_037e = subfont.Subfont{
	First:  0x037e, // ';'
	Last:   0x037e, // ';'
	Offset: 0,
	Data:   &X037E,
}

// X0384_038a subfont, n=7, ΄΅Ά·ΈΉ
var X0384_038a = subfont.Subfont{
	First:  0x0384, // '΄'
	Last:   0x038a, // 'Ί'
	Offset: 0,
	Data:   &X0384,
}

// X038c_038c subfont, n=1, 
var X038c_038c = subfont.Subfont{
	First:  0x038c, // 'Ό'
	Last:   0x038c, // 'Ό'
	Offset: 0,
	Data:   &X038C,
}

// X038e_03a1 subfont, n=20, ΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠ
var X038e_03a1 = subfont.Subfont{
	First:  0x038e, // 'Ύ'
	Last:   0x03a1, // 'Ρ'
	Offset: 0,
	Data:   &X038E,
}

// X03a3_03ce subfont, n=44, ΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύ
var X03a3_03ce = subfont.Subfont{
	First:  0x03a3, // 'Σ'
	Last:   0x03ce, // 'ώ'
	Offset: 0,
	Data:   &X03A3,
}

// X03d0_03d7 subfont, n=8, ϐϑϒϓϔϕϖ
var X03d0_03d7 = subfont.Subfont{
	First:  0x03d0, // 'ϐ'
	Last:   0x03d7, // 'ϗ'
	Offset: 0,
	Data:   &X03D0,
}

// X03da_03f3 subfont, n=26, ϚϛϜϝϞϟϠϡϢϣϤϥϦϧϨϩϪϫϬϭϮϯϰϱϲ
var X03da_03f3 = subfont.Subfont{
	First:  0x03da, // 'Ϛ'
	Last:   0x03f3, // 'ϳ'
	Offset: 0,
	Data:   &X03DA,
}

// X0400_0486 subfont, n=135, ЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ
var X0400_0486 = subfont.Subfont{
	First:  0x0400, // 'Ѐ'
	Last:   0x0486, // '҆'
	Offset: 0,
	Data:   &X0400,
}

// X0488_04ce subfont, n=71, ҈҉ҊҋҌҍҎҏҐґҒғҔҕҖҗҘҙҚқҜҝҞҟҠҡҢңҤҥҦҧҨҩҪҫҬҭҮүҰұҲҳҴҵҶҷ
var X0488_04ce = subfont.Subfont{
	First:  0x0488, // '҈'
	Last:   0x04ce, // 'ӎ'
	Offset: 0,
	Data:   &X0488,
}

// X04d0_04f5 subfont, n=38, ӐӑӒӓӔӕӖӗӘәӚӛӜӝӞӟӠӡӢӣӤӥӦӧӨөӪӫӬӭӮӯӰӱӲӳӴ
var X04d0_04f5 = subfont.Subfont{
	First:  0x04d0, // 'Ӑ'
	Last:   0x04f5, // 'ӵ'
	Offset: 0,
	Data:   &X04D0,
}

// X04f8_04f9 subfont, n=2, Ӹ
var X04f8_04f9 = subfont.Subfont{
	First:  0x04f8, // 'Ӹ'
	Last:   0x04f9, // 'ӹ'
	Offset: 0,
	Data:   &X04F8,
}

// X0500_050f subfont, n=16, ԀԁԂԃԄԅԆԇԈԉԊԋԌԍԎ
var X0500_050f = subfont.Subfont{
	First:  0x0500, // 'Ԁ'
	Last:   0x050f, // 'ԏ'
	Offset: 0,
	Data:   &X0500,
}

// X0530_0556 subfont, n=39, ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕ
var X0530_0556 = subfont.Subfont{
	First:  0x0530,
	Last:   0x0556, // 'Ֆ'
	Offset: 0,
	Data:   &X0530,
}

// X0559_055f subfont, n=7, ՙ՚՛՜՝՞
var X0559_055f = subfont.Subfont{
	First:  0x0559, // 'ՙ'
	Last:   0x055f, // '՟'
	Offset: 0,
	Data:   &X0559,
}

// X0561_0587 subfont, n=39, աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆ
var X0561_0587 = subfont.Subfont{
	First:  0x0561, // 'ա'
	Last:   0x0587, // 'և'
	Offset: 0,
	Data:   &X0561,
}

// X0589_058a subfont, n=2, ։
var X0589_058a = subfont.Subfont{
	First:  0x0589, // '։'
	Last:   0x058a, // '֊'
	Offset: 0,
	Data:   &X0589,
}

// X0591_05a1 subfont, n=17, ֑֖֛֚֒֓֔֕֗֘֙֜֝֞֟֠
var X0591_05a1 = subfont.Subfont{
	First:  0x0591, // '֑'
	Last:   0x05a1, // '֡'
	Offset: 0,
	Data:   &X0591,
}

// X05a3_05b9 subfont, n=23, ְֱֲֳִֵֶַָ֣֤֥֦֧֪֭֮֨֩֫֬֯
var X05a3_05b9 = subfont.Subfont{
	First:  0x05a3, // '֣'
	Last:   0x05b9, // 'ֹ'
	Offset: 0,
	Data:   &X05A3,
}

// X05bb_05c4 subfont, n=10, ֻּֽ־ֿ׀ׁׂ׃
var X05bb_05c4 = subfont.Subfont{
	First:  0x05bb, // 'ֻ'
	Last:   0x05c4, // 'ׄ'
	Offset: 0,
	Data:   &X05BB,
}

// X05d0_05ea subfont, n=27, אבגדהוזחטיךכלםמןנסעףפץצקרש
var X05d0_05ea = subfont.Subfont{
	First:  0x05d0, // 'א'
	Last:   0x05ea, // 'ת'
	Offset: 0,
	Data:   &X05D0,
}

// X05f0_05f4 subfont, n=5, װױײ׳
var X05f0_05f4 = subfont.Subfont{
	First:  0x05f0, // 'װ'
	Last:   0x05f4, // '״'
	Offset: 0,
	Data:   &X05F0,
}

// X060c_060c subfont, n=1, 
var X060c_060c = subfont.Subfont{
	First:  0x060c, // '،'
	Last:   0x060c, // '،'
	Offset: 0,
	Data:   &X060C,
}

// X061b_061b subfont, n=1, 
var X061b_061b = subfont.Subfont{
	First:  0x061b, // '؛'
	Last:   0x061b, // '؛'
	Offset: 0,
	Data:   &X061B,
}

// X061f_061f subfont, n=1, 
var X061f_061f = subfont.Subfont{
	First:  0x061f, // '؟'
	Last:   0x061f, // '؟'
	Offset: 0,
	Data:   &X061F,
}

// X0621_063a subfont, n=26, ءآأؤإئابةتثجحخدذرزسشصضطظع
var X0621_063a = subfont.Subfont{
	First:  0x0621, // 'ء'
	Last:   0x063a, // 'غ'
	Offset: 0,
	Data:   &X0621,
}

// X0640_0655 subfont, n=22, ـفقكلمنهوىيًٌٍَُِّْٓٔ
var X0640_0655 = subfont.Subfont{
	First:  0x0640, // 'ـ'
	Last:   0x0655, // 'ٕ'
	Offset: 0,
	Data:   &X0640,
}

// X0660_066d subfont, n=14, ٠١٢٣٤٥٦٧٨٩٪٫٬
var X0660_066d = subfont.Subfont{
	First:  0x0660, // '٠'
	Last:   0x066d, // '٭'
	Offset: 0,
	Data:   &X0660,
}

// X0670_06ed subfont, n=126, ٰٱٲٳٴٵٶٷٸٹٺٻټٽپٿڀځڂڃڄڅچڇڈډڊڋڌڍڎڏڐڑڒړڔڕږڗژڙښڛڜڝڞڟ
var X0670_06ed = subfont.Subfont{
	First:  0x0670, // 'ٰ'
	Last:   0x06ed, // 'ۭ'
	Offset: 0,
	Data:   &X0670,
}

// X06f0_06fe subfont, n=15, ۰۱۲۳۴۵۶۷۸۹ۺۻۼ۽
var X06f0_06fe = subfont.Subfont{
	First:  0x06f0, // '۰'
	Last:   0x06fe, // '۾'
	Offset: 0,
	Data:   &X06F0,
}

// X10d3_10d3 subfont, n=1, 
var X10d3_10d3 = subfont.Subfont{
	First:  0x10d3, // 'დ'
	Last:   0x10d3, // 'დ'
	Offset: 0,
	Data:   &X10D3,
}

// X10d7_10d7 subfont, n=1, 
var X10d7_10d7 = subfont.Subfont{
	First:  0x10d7, // 'თ'
	Last:   0x10d7, // 'თ'
	Offset: 0,
	Data:   &X10D7,
}

// X10da_10da subfont, n=1, 
var X10da_10da = subfont.Subfont{
	First:  0x10da, // 'ლ'
	Last:   0x10da, // 'ლ'
	Offset: 0,
	Data:   &X10DA,
}

// X10dd_10dd subfont, n=1, 
var X10dd_10dd = subfont.Subfont{
	First:  0x10dd, // 'ო'
	Last:   0x10dd, // 'ო'
	Offset: 0,
	Data:   &X10DD,
}

// X10e6_10e6 subfont, n=1, 
var X10e6_10e6 = subfont.Subfont{
	First:  0x10e6, // 'ღ'
	Last:   0x10e6, // 'ღ'
	Offset: 0,
	Data:   &X10E6,
}

// X1e00_1e9b subfont, n=156, ḀḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯ
var X1e00_1e9b = subfont.Subfont{
	First:  0x1e00, // 'Ḁ'
	Last:   0x1e9b, // 'ẛ'
	Offset: 0,
	Data:   &X1E00,
}

// X1ea0_1ef9 subfont, n=90, ẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏ
var X1ea0_1ef9 = subfont.Subfont{
	First:  0x1ea0, // 'Ạ'
	Last:   0x1ef9, // 'ỹ'
	Offset: 0,
	Data:   &X1EA0,
}

// X1f00_1f07 subfont, n=8, ἀἁἂἃἄἅἆ
var X1f00_1f07 = subfont.Subfont{
	First:  0x1f00, // 'ἀ'
	Last:   0x1f07, // 'ἇ'
	Offset: 0,
	Data:   &X1F00,
}

// X2000_2027 subfont, n=40, ‐‑‒–—―‖‗‘’‚‛“”„‟†‡•‣․‥…
var X2000_2027 = subfont.Subfont{
	First:  0x2000,
	Last:   0x2027, // '‧'
	Offset: 0,
	Data:   &X2000,
}

// X2030_2046 subfont, n=23, ‰‱′″‴‵‶‷‸‹›※‼‽‾‿⁀⁁⁂⁃⁄⁅
var X2030_2046 = subfont.Subfont{
	First:  0x2030, // '‰'
	Last:   0x2046, // '⁆'
	Offset: 0,
	Data:   &X2030,
}

// X2048_204d subfont, n=6, ⁈⁉⁊⁋⁌
var X2048_204d = subfont.Subfont{
	First:  0x2048, // '⁈'
	Last:   0x204d, // '⁍'
	Offset: 0,
	Data:   &X2048,
}

// X2070_2070 subfont, n=1, 
var X2070_2070 = subfont.Subfont{
	First:  0x2070, // '⁰'
	Last:   0x2070, // '⁰'
	Offset: 0,
	Data:   &X2070,
}

// X2074_208f subfont, n=28, ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎
var X2074_208f = subfont.Subfont{
	First:  0x2074, // '⁴'
	Last:   0x208f,
	Offset: 0,
	Data:   &X2074,
}

// X20a0_20af subfont, n=16, ₠₡₢₣₤₥₦₧₨₩₪₫€₭₮
var X20a0_20af = subfont.Subfont{
	First:  0x20a0, // '₠'
	Last:   0x20af, // '₯'
	Offset: 0,
	Data:   &X20A0,
}

// X2100_213a subfont, n=59, ℀℁ℂ℃℄℅℆ℇ℈℉ℊℋℌℍℎℏℐℑℒℓ℔ℕ№℗℘ℙℚℛℜℝ℞℟℠℡™℣ℤ℥Ω℧ℨ℩KÅℬℭ℮ℯ
var X2100_213a = subfont.Subfont{
	First:  0x2100, // '℀'
	Last:   0x213a, // '℺'
	Offset: 0,
	Data:   &X2100,
}

// X2153_2183 subfont, n=49, ⅓⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞⅟ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫⅬⅭⅮⅯⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹⅺⅻⅼⅽⅾⅿↀↁↂ
var X2153_2183 = subfont.Subfont{
	First:  0x2153, // '⅓'
	Last:   0x2183, // 'Ↄ'
	Offset: 0,
	Data:   &X2153,
}

// X2190_21f3 subfont, n=100, ←↑→↓↔↕↖↗↘↙↚↛↜↝↞↟↠↡↢↣↤↥↦↧↨↩↪↫↬↭↮↯↰↱↲↳↴↵↶↷↸↹↺↻↼↽↾↿
var X2190_21f3 = subfont.Subfont{
	First:  0x2190, // '←'
	Last:   0x21f3, // '⇳'
	Offset: 0,
	Data:   &X2190,
}

// X2200_22f1 subfont, n=242, ∀∁∂∃∄∅∆∇∈∉∊∋∌∍∎∏∐∑−∓∔∕∖∗∘∙√∛∜∝∞∟∠∡∢∣∤∥∦∧∨∩∪∫∬∭∮∯
var X2200_22f1 = subfont.Subfont{
	First:  0x2200, // '∀'
	Last:   0x22f1, // '⋱'
	Offset: 0,
	Data:   &X2200,
}

// X2300_2300 subfont, n=1, 
var X2300_2300 = subfont.Subfont{
	First:  0x2300, // '⌀'
	Last:   0x2300, // '⌀'
	Offset: 0,
	Data:   &X2300,
}

// X2302_2302 subfont, n=1, 
var X2302_2302 = subfont.Subfont{
	First:  0x2302, // '⌂'
	Last:   0x2302, // '⌂'
	Offset: 0,
	Data:   &X2302,
}

// X2308_230b subfont, n=4, ⌈⌉⌊
var X2308_230b = subfont.Subfont{
	First:  0x2308, // '⌈'
	Last:   0x230b, // '⌋'
	Offset: 0,
	Data:   &X2308,
}

// X2310_2310 subfont, n=1, 
var X2310_2310 = subfont.Subfont{
	First:  0x2310, // '⌐'
	Last:   0x2310, // '⌐'
	Offset: 0,
	Data:   &X2310,
}

// X2318_2318 subfont, n=1, 
var X2318_2318 = subfont.Subfont{
	First:  0x2318, // '⌘'
	Last:   0x2318, // '⌘'
	Offset: 0,
	Data:   &X2318,
}

// X231a_231b subfont, n=2, ⌚
var X231a_231b = subfont.Subfont{
	First:  0x231a, // '⌚'
	Last:   0x231b, // '⌛'
	Offset: 0,
	Data:   &X231A,
}

// X2320_2321 subfont, n=2, ⌠
var X2320_2321 = subfont.Subfont{
	First:  0x2320, // '⌠'
	Last:   0x2321, // '⌡'
	Offset: 0,
	Data:   &X2320,
}

// X2329_232a subfont, n=2, 〈
var X2329_232a = subfont.Subfont{
	First:  0x2329, // '〈'
	Last:   0x232a, // '〉'
	Offset: 0,
	Data:   &X2329,
}

// X239b_23bd subfont, n=35, ⎛⎜⎝⎞⎟⎠⎡⎢⎣⎤⎥⎦⎧⎨⎩⎪⎫⎬⎭⎮⎯⎰⎱⎲⎳⎴⎵⎶⎷⎸⎹⎺⎻⎼
var X239b_23bd = subfont.Subfont{
	First:  0x239b, // '⎛'
	Last:   0x23bd, // '⎽'
	Offset: 0,
	Data:   &X239B,
}

// X23ce_23ce subfont, n=1, 
var X23ce_23ce = subfont.Subfont{
	First:  0x23ce, // '⏎'
	Last:   0x23ce, // '⏎'
	Offset: 0,
	Data:   &X23CE,
}

// X2409_240d subfont, n=5, ␉␊␋␌
var X2409_240d = subfont.Subfont{
	First:  0x2409, // '␉'
	Last:   0x240d, // '␍'
	Offset: 0,
	Data:   &X2409,
}

// X2423_2424 subfont, n=2, ␣
var X2423_2424 = subfont.Subfont{
	First:  0x2423, // '␣'
	Last:   0x2424, // '␤'
	Offset: 0,
	Data:   &X2423,
}

// X2426_2426 subfont, n=1, 
var X2426_2426 = subfont.Subfont{
	First:  0x2426, // '␦'
	Last:   0x2426, // '␦'
	Offset: 0,
	Data:   &X2426,
}

// X2500_2595 subfont, n=150, ─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯
var X2500_2595 = subfont.Subfont{
	First:  0x2500, // '─'
	Last:   0x2595, // '▕'
	Offset: 0,
	Data:   &X2500,
}

// X25a0_25f7 subfont, n=88, ■□▢▣▤▥▦▧▨▩▪▫▬▭▮▯▰▱▲△▴▵▶▷▸▹►▻▼▽▾▿◀◁◂◃◄◅◆◇◈◉◊○◌◍◎●
var X25a0_25f7 = subfont.Subfont{
	First:  0x25a0, // '■'
	Last:   0x25f7, // '◷'
	Offset: 0,
	Data:   &X25A0,
}

// X2600_2602 subfont, n=3, ☀☁
var X2600_2602 = subfont.Subfont{
	First:  0x2600, // '☀'
	Last:   0x2602, // '☂'
	Offset: 0,
	Data:   &X2600,
}

// X2605_260d subfont, n=9, ★☆☇☈☉☊☋☌
var X2605_260d = subfont.Subfont{
	First:  0x2605, // '★'
	Last:   0x260d, // '☍'
	Offset: 0,
	Data:   &X2605,
}

// X2610_2613 subfont, n=4, ☐☑☒
var X2610_2613 = subfont.Subfont{
	First:  0x2610, // '☐'
	Last:   0x2613, // '☓'
	Offset: 0,
	Data:   &X2610,
}

// X2620_2620 subfont, n=1, 
var X2620_2620 = subfont.Subfont{
	First:  0x2620, // '☠'
	Last:   0x2620, // '☠'
	Offset: 0,
	Data:   &X2620,
}

// X2622_2622 subfont, n=1, 
var X2622_2622 = subfont.Subfont{
	First:  0x2622, // '☢'
	Last:   0x2622, // '☢'
	Offset: 0,
	Data:   &X2622,
}

// X2626_2626 subfont, n=1, 
var X2626_2626 = subfont.Subfont{
	First:  0x2626, // '☦'
	Last:   0x2626, // '☦'
	Offset: 0,
	Data:   &X2626,
}

// X2628_262b subfont, n=4, ☨☩☪
var X2628_262b = subfont.Subfont{
	First:  0x2628, // '☨'
	Last:   0x262b, // '☫'
	Offset: 0,
	Data:   &X2628,
}

// X262e_2637 subfont, n=10, ☮☯☰☱☲☳☴☵☶
var X262e_2637 = subfont.Subfont{
	First:  0x262e, // '☮'
	Last:   0x2637, // '☷'
	Offset: 0,
	Data:   &X262E,
}

// X2639_2653 subfont, n=27, ☹☺☻☼☽☾☿♀♁♂♃♄♅♆♇♈♉♊♋♌♍♎♏♐♑♒
var X2639_2653 = subfont.Subfont{
	First:  0x2639, // '☹'
	Last:   0x2653, // '♓'
	Offset: 0,
	Data:   &X2639,
}

// X2660_2667 subfont, n=8, ♠♡♢♣♤♥♦
var X2660_2667 = subfont.Subfont{
	First:  0x2660, // '♠'
	Last:   0x2667, // '♧'
	Offset: 0,
	Data:   &X2660,
}

// X2669_266f subfont, n=7, ♩♪♫♬♭♮
var X2669_266f = subfont.Subfont{
	First:  0x2669, // '♩'
	Last:   0x266f, // '♯'
	Offset: 0,
	Data:   &X2669,
}

// X29fa_29fa subfont, n=1, 
var X29fa_29fa = subfont.Subfont{
	First:  0x29fa, // '⧺'
	Last:   0x29fa, // '⧺'
	Offset: 0,
	Data:   &X29FA,
}

// Xfb00_fb05 subfont, n=6, ﬀﬁﬂﬃﬄ
var Xfb00_fb05 = subfont.Subfont{
	First:  0xfb00, // 'ﬀ'
	Last:   0xfb05, // 'ﬅ'
	Offset: 0,
	Data:   &XFB00,
}

// Xfb50_fbb1 subfont, n=98, ﭐﭑﭒﭓﭔﭕﭖﭗﭘﭙﭚﭛﭜﭝﭞﭟﭠﭡﭢﭣﭤﭥﭦﭧﭨﭩﭪﭫﭬﭭﭮﭯﭰﭱﭲﭳﭴﭵﭶﭷﭸﭹﭺﭻﭼﭽﭾﭿ
var Xfb50_fbb1 = subfont.Subfont{
	First:  0xfb50, // 'ﭐ'
	Last:   0xfbb1, // 'ﮱ'
	Offset: 0,
	Data:   &XFB50,
}

// Xfbd3_fbe9 subfont, n=23, ﯓﯔﯕﯖﯗﯘﯙﯚﯛﯜﯝﯞﯟﯠﯡﯢﯣﯤﯥﯦﯧﯨ
var Xfbd3_fbe9 = subfont.Subfont{
	First:  0xfbd3, // 'ﯓ'
	Last:   0xfbe9, // 'ﯩ'
	Offset: 0,
	Data:   &XFBD3,
}

// Xfbfc_fbff subfont, n=4, ﯼﯽﯾ
var Xfbfc_fbff = subfont.Subfont{
	First:  0xfbfc, // 'ﯼ'
	Last:   0xfbff, // 'ﯿ'
	Offset: 0,
	Data:   &XFBFC,
}

// Xfc5b_fc63 subfont, n=9, ﱛﱜﱝﱞﱟﱠﱡﱢ
var Xfc5b_fc63 = subfont.Subfont{
	First:  0xfc5b, // 'ﱛ'
	Last:   0xfc63, // 'ﱣ'
	Offset: 0,
	Data:   &XFC5B,
}

// Xfc90_fc90 subfont, n=1, 
var Xfc90_fc90 = subfont.Subfont{
	First:  0xfc90, // 'ﲐ'
	Last:   0xfc90, // 'ﲐ'
	Offset: 0,
	Data:   &XFC90,
}

// Xfcf2_fcf4 subfont, n=3, ﳲﳳ
var Xfcf2_fcf4 = subfont.Subfont{
	First:  0xfcf2, // 'ﳲ'
	Last:   0xfcf4, // 'ﳴ'
	Offset: 0,
	Data:   &XFCF2,
}

// Xfd3c_fd3f subfont, n=4, ﴼﴽ﴾
var Xfd3c_fd3f = subfont.Subfont{
	First:  0xfd3c, // 'ﴼ'
	Last:   0xfd3f, // '﴿'
	Offset: 0,
	Data:   &XFD3C,
}

// Xfdf2_fdf2 subfont, n=1, 
var Xfdf2_fdf2 = subfont.Subfont{
	First:  0xfdf2, // 'ﷲ'
	Last:   0xfdf2, // 'ﷲ'
	Offset: 0,
	Data:   &XFDF2,
}

// Xfe50_fe52 subfont, n=3, ﹐﹑
var Xfe50_fe52 = subfont.Subfont{
	First:  0xfe50, // '﹐'
	Last:   0xfe52, // '﹒'
	Offset: 0,
	Data:   &XFE50,
}

// Xfe54_fe66 subfont, n=19, ﹔﹕﹖﹗﹘﹙﹚﹛﹜﹝﹞﹟﹠﹡﹢﹣﹤﹥
var Xfe54_fe66 = subfont.Subfont{
	First:  0xfe54, // '﹔'
	Last:   0xfe66, // '﹦'
	Offset: 0,
	Data:   &XFE54,
}

// Xfe68_fe6b subfont, n=4, ﹨﹩﹪
var Xfe68_fe6b = subfont.Subfont{
	First:  0xfe68, // '﹨'
	Last:   0xfe6b, // '﹫'
	Offset: 0,
	Data:   &XFE68,
}

// Xfe70_fe72 subfont, n=3, ﹰﹱ
var Xfe70_fe72 = subfont.Subfont{
	First:  0xfe70, // 'ﹰ'
	Last:   0xfe72, // 'ﹲ'
	Offset: 0,
	Data:   &XFE70,
}

// Xfe74_fe74 subfont, n=1, 
var Xfe74_fe74 = subfont.Subfont{
	First:  0xfe74, // 'ﹴ'
	Last:   0xfe74, // 'ﹴ'
	Offset: 0,
	Data:   &XFE74,
}

// Xfe76_fefc subfont, n=135, ﹶﹷﹸﹹﹺﹻﹼﹽﹾﹿﺀﺁﺂﺃﺄﺅﺆﺇﺈﺉﺊﺋﺌﺍﺎﺏﺐﺑﺒﺓﺔﺕﺖﺗﺘﺙﺚﺛﺜﺝﺞﺟﺠﺡﺢﺣﺤﺥ
var Xfe76_fefc = subfont.Subfont{
	First:  0xfe76, // 'ﹶ'
	Last:   0xfefc, // 'ﻼ'
	Offset: 0,
	Data:   &XFE76,
}

// Xfeff_feff subfont, n=1, 
var Xfeff_feff = subfont.Subfont{
	First:  0xfeff,
	Last:   0xfeff,
	Offset: 0,
	Data:   &XFEFF,
}

// Xfffd_fffd subfont, n=1, 
var Xfffd_fffd = subfont.Subfont{
	First:  0xfffd, // '�'
	Last:   0xfffd, // '�'
	Offset: 0,
	Data:   &XFFFD,
}
