// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/anonpro/anonpro.11.font

package anonpro11

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1162 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixXfb01, // 84 bytes
	},
}

// Xf8ff font data, 1174 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 12,
		Pix:    pixXf8ff, // 96 bytes
	},
}

// Xf6c3 font data, 1084 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 3, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 3,
		Pix:    pixXf6c3, // 6 bytes
	},
}

// Xe000 font data, 1462 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 48, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 48,
		Pix:    pixXe000, // 384 bytes
	},
}

// X2713 font data, 1108 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -4},
			Max: image.Point{X: 6, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 6,
		Pix:    pixX2713, // 30 bytes
	},
}

// X2500 font data, 3048 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 180, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 197,
		Pix:    pixX2500, // 1970 bytes
	},
}

// X2324 font data, 1422 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 43, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 43,
		Pix:    pixX2324, // 344 bytes
	},
}

// X221a font data, 1558 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 46, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 48,
		Pix:    pixX221a, // 480 bytes
	},
}

// X2116 font data, 1430 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 44, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 44,
		Pix:    pixX2116, // 352 bytes
	},
}

// X2013 font data, 1780 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 78, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 78,
		Pix:    pixX2013, // 702 bytes
	},
}

// X1e02 font data, 2318 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 121, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 124,
		Pix:    pixX1e02, // 1240 bytes
	},
}

// X0490 font data, 1158 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixX0490, // 80 bytes
	},
}

// X0384 font data, 10285 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 829, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 837,
		Pix:    pixX0384, // 9207 bytes
	},
}

// X0218 font data, 1598 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 47, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 52,
		Pix:    pixX0218, // 520 bytes
	},
}

// X0101 font data, 7798 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 659, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 672,
		Pix:    pixX0101, // 6720 bytes
	},
}

// X0000 font data, 10278 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 901, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 920,
		Pix:    pixX0000, // 9200 bytes
	},
}
