// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/terminus/terminus.14.font

package terminus14

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// X0000 font data, 54 bytes, orgbpp: 1
var X0000 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0000, // 10 bytes
	},
}

// X0020 font data, 1220 bytes, orgbpp: 1
var X0020 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 665, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 84,
		Pix:    pixX0020, // 1176 bytes
	},
}

// X00A0 font data, 3040 bytes, orgbpp: 1
var X00A0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1712, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 214,
		Pix:    pixX00A0, // 2996 bytes
	},
}

// X0178 font data, 128 bytes, orgbpp: 1
var X0178 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 56, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX0178, // 84 bytes
	},
}

// X0186 font data, 54 bytes, orgbpp: 1
var X0186 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0186, // 10 bytes
	},
}

// X018E font data, 74 bytes, orgbpp: 1
var X018E = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 18, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX018E, // 30 bytes
	},
}

// X0192 font data, 56 bytes, orgbpp: 1
var X0192 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 7, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0192, // 12 bytes
	},
}

// X019D font data, 68 bytes, orgbpp: 1
var X019D = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX019D, // 24 bytes
	},
}

// X01B7 font data, 54 bytes, orgbpp: 1
var X01B7 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 6, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX01B7, // 10 bytes
	},
}

// X0218 font data, 92 bytes, orgbpp: 1
var X0218 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 28, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 4,
		Pix:    pixX0218, // 48 bytes
	},
}

// X0232 font data, 72 bytes, orgbpp: 1
var X0232 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0232, // 28 bytes
	},
}

// X0237 font data, 53 bytes, orgbpp: 1
var X0237 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 5,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 5, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0237, // 9 bytes
	},
}

// X0254 font data, 51 bytes, orgbpp: 1
var X0254 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 6, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0254, // 7 bytes
	},
}

// X0258 font data, 58 bytes, orgbpp: 1
var X0258 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX0258, // 14 bytes
	},
}

// X025B font data, 51 bytes, orgbpp: 1
var X025B = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 6, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX025B, // 7 bytes
	},
}

// X0272 font data, 53 bytes, orgbpp: 1
var X0272 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 7, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0272, // 9 bytes
	},
}

// X0292 font data, 53 bytes, orgbpp: 1
var X0292 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 6, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0292, // 9 bytes
	},
}

// X02BB font data, 47 bytes, orgbpp: 1
var X02BB = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 2,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 6, Y: -9},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02BB, // 3 bytes
	},
}

// X02C6 font data, 46 bytes, orgbpp: 1
var X02C6 = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 8, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02C6, // 2 bytes
	},
}

// X02D8 font data, 46 bytes, orgbpp: 1
var X02D8 = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 8, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX02D8, // 2 bytes
	},
}

// X02DB font data, 86 bytes, orgbpp: 1
var X02DB = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 21, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX02DB, // 42 bytes
	},
}

// X0300 font data, 50 bytes, orgbpp: 1
var X0300 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 24, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX0300, // 6 bytes
	},
}

// X0306 font data, 46 bytes, orgbpp: 1
var X0306 = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 4, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0306, // 2 bytes
	},
}

// X030C font data, 46 bytes, orgbpp: 1
var X030C = font9.Fixed{
	Left:  -2,
	Adv:   8,
	Width: 4,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 4, Y: -10},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX030C, // 2 bytes
	},
}

// X0329 font data, 46 bytes, orgbpp: 1
var X0329 = font9.Fixed{
	Left:  -3,
	Adv:   8,
	Width: 1,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 1, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX0329, // 2 bytes
	},
}

// X0384 font data, 128 bytes, orgbpp: 1
var X0384 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 49, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 7,
		Pix:    pixX0384, // 84 bytes
	},
}

// X038C font data, 56 bytes, orgbpp: 1
var X038C = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 7, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 1,
		Pix:    pixX038C, // 12 bytes
	},
}

// X038E font data, 260 bytes, orgbpp: 1
var X038E = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 140, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 18,
		Pix:    pixX038E, // 216 bytes
	},
}

// X03A3 font data, 590 bytes, orgbpp: 1
var X03A3 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 308, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 39,
		Pix:    pixX03A3, // 546 bytes
	},
}

// X03F3 font data, 68 bytes, orgbpp: 1
var X03F3 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX03F3, // 24 bytes
	},
}

// X0400 font data, 1388 bytes, orgbpp: 1
var X0400 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 96,
		Pix:    pixX0400, // 1344 bytes
	},
}

// X0490 font data, 240 bytes, orgbpp: 1
var X0490 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 112, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 14,
		Pix:    pixX0490, // 196 bytes
	},
}

// X04A0 font data, 116 bytes, orgbpp: 1
var X04A0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 48, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX04A0, // 72 bytes
	},
}

// X04AA font data, 68 bytes, orgbpp: 1
var X04AA = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04AA, // 24 bytes
	},
}

// X04AE font data, 116 bytes, orgbpp: 1
var X04AE = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 48, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX04AE, // 72 bytes
	},
}

// X04B6 font data, 116 bytes, orgbpp: 1
var X04B6 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 42, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 6,
		Pix:    pixX04B6, // 72 bytes
	},
}

// X04D0 font data, 212 bytes, orgbpp: 1
var X04D0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 112, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 14,
		Pix:    pixX04D0, // 168 bytes
	},
}

// X04E2 font data, 254 bytes, orgbpp: 1
var X04E2 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 120, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 15,
		Pix:    pixX04E2, // 210 bytes
	},
}

// X04F8 font data, 68 bytes, orgbpp: 1
var X04F8 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX04F8, // 24 bytes
	},
}

// X1E34 font data, 68 bytes, orgbpp: 1
var X1E34 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1E34, // 24 bytes
	},
}

// X1EB8 font data, 68 bytes, orgbpp: 1
var X1EB8 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EB8, // 24 bytes
	},
}

// X1EBC font data, 68 bytes, orgbpp: 1
var X1EBC = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EBC, // 24 bytes
	},
}

// X1ECA font data, 80 bytes, orgbpp: 1
var X1ECA = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 24, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 3,
		Pix:    pixX1ECA, // 36 bytes
	},
}

// X1EE4 font data, 68 bytes, orgbpp: 1
var X1EE4 = font9.Fixed{
	Left:  -1,
	Adv:   8,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 12, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EE4, // 24 bytes
	},
}

// X1EF8 font data, 72 bytes, orgbpp: 1
var X1EF8 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 7,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   0, // 1 bpp
		Stride: 2,
		Pix:    pixX1EF8, // 28 bytes
	},
}
