// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusans/dejavusans.18.font

package dejavusans18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 439 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 19, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 19,
		Pix:    pixXfff9, // 361 bytes
	},
}

// Xfe00 font data, 37510 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1575, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1584,
		Pix:    pixXfe00, // 36432 bytes
	},
}

// Xfb00 font data, 39138 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1730, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1730,
		Pix:    pixXfb00, // 38060 bytes
	},
}

// Xf6c5 font data, 1228 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixXf6c5, // 150 bytes
	},
}

// Xf001 font data, 1741 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 30, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 51,
		Pix:    pixXf001, // 663 bytes
	},
}

// Xef00 font data, 3458 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 157, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 170,
		Pix:    pixXef00, // 2380 bytes
	},
}

// Xa746 font data, 8869 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 371, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 371,
		Pix:    pixXa746, // 7791 bytes
	},
}

// Xa644 font data, 16666 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 863, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 866,
		Pix:    pixXa644, // 15588 bytes
	},
}

// X4dc0 font data, 15414 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 896,
		Pix:    pixX4dc0, // 14336 bytes
	},
}

// X2d61 font data, 2659 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 93, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 93,
		Pix:    pixX2d61, // 1581 bytes
	},
}

// X2c60 font data, 17638 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 827, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 828,
		Pix:    pixX2c60, // 16560 bytes
	},
}

// X1e01 font data, 44896 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 826 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1938, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2001,
		Pix:    pixX1e01, // 44022 bytes
	},
}

// X1d00 font data, 24058 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1148, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1149,
		Pix:    pixX1d00, // 22980 bytes
	},
}

// X1401 font data, 32802 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1941, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 2002,
		Pix:    pixX1401, // 32032 bytes
	},
}

// X10a0 font data, 17874 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 882, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 884,
		Pix:    pixX10a0, // 16796 bytes
	},
}

// X0e3f font data, 17063 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 689, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 695,
		Pix:    pixX0e3f, // 15985 bytes
	},
}

// X07c0 font data, 9058 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 420, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 420,
		Pix:    pixX07c0, // 7980 bytes
	},
}

// X03c0 font data, 143 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixX03c0, // 99 bytes
	},
}

// X03a9 font data, 226 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   14,
	Width: 14,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixX03a9, // 182 bytes
	},
}

// X0101 font data, 45040 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 838 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1997, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2007,
		Pix:    pixX0101, // 44154 bytes
	},
}

// X0020 font data, 16594 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 800, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 898,
		Pix:    pixX0020, // 16164 bytes
	},
}

// X0000 font data, 188 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX0000, // 144 bytes
	},
}
