// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusans/dejavusans.18.font

package dejavusans18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 173 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 18, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 95 bytes
	},
}

// Xfe00 font data, 10186 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1476, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 396,
		Pix:    pixXfe00, // 9108 bytes
	},
}

// Xfb00 font data, 10604 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1664, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 433,
		Pix:    pixXfb00, // 9526 bytes
	},
}

// Xf6c5 font data, 1123 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 9, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf6c5, // 45 bytes
	},
}

// Xf001 font data, 1247 bytes, orgbpp: 8
var Xf001 = font9.Variable{
	Info: infoXf001, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 30, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 13,
		Pix:    pixXf001, // 169 bytes
	},
}

// Xef00 font data, 1680 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 143, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 43,
		Pix:    pixXef00, // 602 bytes
	},
}

// Xa746 font data, 3031 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 355, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 93,
		Pix:    pixXa746, // 1953 bytes
	},
}

// Xa644 font data, 4984 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 824, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 217,
		Pix:    pixXa644, // 3906 bytes
	},
}

// X4dc0 font data, 4662 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX4dc0, // 3584 bytes
	},
}

// X2d61 font data, 1486 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 90, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 24,
		Pix:    pixX2d61, // 408 bytes
	},
}

// X2c60 font data, 5218 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 805, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 207,
		Pix:    pixX2c60, // 4140 bytes
	},
}

// X1e01 font data, 11896 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 826 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1913, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1e01, // 11022 bytes
	},
}

// X1d00 font data, 6838 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1063, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 288,
		Pix:    pixX1d00, // 5760 bytes
	},
}

// X1401 font data, 8786 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1882, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1401, // 8016 bytes
	},
}

// X10a0 font data, 5277 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 810, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 221,
		Pix:    pixX10a0, // 4199 bytes
	},
}

// X0e3f font data, 5080 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 661, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 174,
		Pix:    pixX0e3f, // 4002 bytes
	},
}

// X07c0 font data, 3073 bytes, orgbpp: 8
var X07c0 = font9.Variable{
	Info: infoX07c0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 414, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 105,
		Pix:    pixX07c0, // 1995 bytes
	},
}

// X03c0 font data, 71 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 27 bytes
	},
}

// X03a9 font data, 83 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   14,
	Width: 12,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03a9, // 39 bytes
	},
}

// X0101 font data, 11930 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 838 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1986, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 11044 bytes
	},
}

// X0020 font data, 4480 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 793, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 225,
		Pix:    pixX0020, // 4050 bytes
	},
}

// X0000 font data, 92 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0000, // 48 bytes
	},
}
