// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/anonpro/anonpro.18.font

package anonpro18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfb01 font data, 1298 bytes, orgbpp: 8
var Xfb01 = font9.Variable{
	Info: infoXfb01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 20, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 20,
		Pix:    pixXfb01, // 220 bytes
	},
}

// Xf8ff font data, 1330 bytes, orgbpp: 8
var Xf8ff = font9.Variable{
	Info: infoXf8ff, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 21, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 21,
		Pix:    pixXf8ff, // 252 bytes
	},
}

// Xf6c3 font data, 1090 bytes, orgbpp: 8
var Xf6c3 = font9.Variable{
	Info: infoXf6c3, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: 0},
			Max: image.Point{X: 4, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 4,
		Pix:    pixXf6c3, // 12 bytes
	},
}

// Xe000 font data, 2026 bytes, orgbpp: 8
var Xe000 = font9.Variable{
	Info: infoXe000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 79, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 79,
		Pix:    pixXe000, // 948 bytes
	},
}

// X2713 font data, 1158 bytes, orgbpp: 8
var X2713 = font9.Variable{
	Info: infoX2713, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -7},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixX2713, // 80 bytes
	},
}

// X2500 font data, 7090 bytes, orgbpp: 8
var X2500 = font9.Variable{
	Info: infoX2500, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 334, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 334,
		Pix:    pixX2500, // 6012 bytes
	},
}

// X2324 font data, 1906 bytes, orgbpp: 8
var X2324 = font9.Variable{
	Info: infoX2324, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 68, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 69,
		Pix:    pixX2324, // 828 bytes
	},
}

// X221a font data, 2428 bytes, orgbpp: 8
var X221a = font9.Variable{
	Info: infoX221a, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 75, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 75,
		Pix:    pixX221a, // 1350 bytes
	},
}

// X2116 font data, 1942 bytes, orgbpp: 8
var X2116 = font9.Variable{
	Info: infoX2116, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 72, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 72,
		Pix:    pixX2116, // 864 bytes
	},
}

// X2013 font data, 2983 bytes, orgbpp: 8
var X2013 = font9.Variable{
	Info: infoX2013, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 126, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 127,
		Pix:    pixX2013, // 1905 bytes
	},
}

// X1e02 font data, 4498 bytes, orgbpp: 8
var X1e02 = font9.Variable{
	Info: infoX1e02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 189, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 190,
		Pix:    pixX1e02, // 3420 bytes
	},
}

// X0490 font data, 1312 bytes, orgbpp: 8
var X0490 = font9.Variable{
	Info: infoX0490, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 18, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 18,
		Pix:    pixX0490, // 234 bytes
	},
}

// X0384 font data, 26008 bytes, orgbpp: 8
var X0384 = font9.Variable{
	Info: infoX0384, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1378, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1385,
		Pix:    pixX0384, // 24930 bytes
	},
}

// X0218 font data, 2294 bytes, orgbpp: 8
var X0218 = font9.Variable{
	Info: infoX0218, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 76, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 76,
		Pix:    pixX0218, // 1216 bytes
	},
}

// X0101 font data, 20842 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1090, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1098,
		Pix:    pixX0101, // 19764 bytes
	},
}

// X0000 font data, 27664 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1472, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1477,
		Pix:    pixX0000, // 26586 bytes
	},
}
