// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansbi/dejavusansbi.16.font

package dejavusansbi16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 402 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 18, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 18,
		Pix:    pixXfff9, // 324 bytes
	},
}

// Xfe00 font data, 1198 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 29, Y: -11},
		},
		LogN:   3, // 8 bpp
		Stride: 30,
		Pix:    pixXfe00, // 120 bytes
	},
}

// Xfb00 font data, 13046 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 696, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 704,
		Pix:    pixXfb00, // 11968 bytes
	},
}

// Xf5c5 font data, 1232 bytes, orgbpp: 8
var Xf5c5 = font9.Variable{
	Info: infoXf5c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 11, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixXf5c5, // 154 bytes
	},
}

// Xef00 font data, 3106 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 150, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 156,
		Pix:    pixXef00, // 2028 bytes
	},
}

// Xa746 font data, 9229 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 426, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 429,
		Pix:    pixXa746, // 8151 bytes
	},
}

// Xa644 font data, 17653 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 957, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 975,
		Pix:    pixXa644, // 16575 bytes
	},
}

// X4dc0 font data, 13558 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 832, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 832,
		Pix:    pixX4dc0, // 12480 bytes
	},
}

// X2e18 font data, 1798 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 43, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 45,
		Pix:    pixX2e18, // 720 bytes
	},
}

// X2c60 font data, 7774 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 371, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 372,
		Pix:    pixX2c60, // 6696 bytes
	},
}

// X2580 font data, 38931 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 674 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1996, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2011,
		Pix:    pixX2580, // 38209 bytes
	},
}

// X1e01 font data, 40870 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1771, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX1e01, // 40100 bytes
	},
}

// X1d00 font data, 23059 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1271, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1293,
		Pix:    pixX1d00, // 21981 bytes
	},
}

// X1646 font data, 4998 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 242, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 245,
		Pix:    pixX1646, // 3920 bytes
	},
}

// X1401 font data, 32794 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 602 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1896, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2009,
		Pix:    pixX1401, // 32144 bytes
	},
}

// X10a0 font data, 16361 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 897, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 899,
		Pix:    pixX10a0, // 15283 bytes
	},
}

// X0e3f font data, 17818 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 806, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 837,
		Pix:    pixX0e3f, // 16740 bytes
	},
}

// X03c0 font data, 143 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixX03c0, // 99 bytes
	},
}

// X03a9 font data, 200 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 13,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 13,
		Pix:    pixX03a9, // 156 bytes
	},
}

// X0101 font data, 40970 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1996, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 2010,
		Pix:    pixX0101, // 40200 bytes
	},
}

// X00a0 font data, 20080 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 936, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1034,
		Pix:    pixX00a0, // 19646 bytes
	},
}

// X0020 font data, 17328 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 895, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 994,
		Pix:    pixX0020, // 16898 bytes
	},
}

// X0000 font data, 156 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixX0000, // 112 bytes
	},
}
