// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavusansbi/dejavusansbi.16.font

package dejavusansbi16

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 168 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 17, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 90 bytes
	},
}

// Xfe00 font data, 1110 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 26, Y: -11},
		},
		LogN:   1, // 2 bpp
		Stride: 8,
		Pix:    pixXfe00, // 32 bytes
	},
}

// Xfb00 font data, 4070 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 649, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 176,
		Pix:    pixXfb00, // 2992 bytes
	},
}

// Xf5c5 font data, 1120 bytes, orgbpp: 8
var Xf5c5 = font9.Variable{
	Info: infoXf5c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf5c5, // 42 bytes
	},
}

// Xef00 font data, 1585 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 133, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 39,
		Pix:    pixXef00, // 507 bytes
	},
}

// Xa746 font data, 3130 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 406, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 108,
		Pix:    pixXa746, // 2052 bytes
	},
}

// Xa644 font data, 5226 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 914, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 244,
		Pix:    pixXa644, // 4148 bytes
	},
}

// X4dc0 font data, 4198 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 768, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 208,
		Pix:    pixX4dc0, // 3120 bytes
	},
}

// X2e18 font data, 1270 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 40, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 12,
		Pix:    pixX2e18, // 192 bytes
	},
}

// X2c60 font data, 2752 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 344, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 93,
		Pix:    pixX2c60, // 1674 bytes
	},
}

// X2580 font data, 10279 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 674 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1861, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX2580, // 9557 bytes
	},
}

// X1e01 font data, 10810 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1755, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX1e01, // 10040 bytes
	},
}

// X1d00 font data, 6586 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 1185, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 324,
		Pix:    pixX1d00, // 5508 bytes
	},
}

// X1646 font data, 2070 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 241, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 62,
		Pix:    pixX1646, // 992 bytes
	},
}

// X1401 font data, 8698 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 602 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1838, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1401, // 8048 bytes
	},
}

// X10a0 font data, 4903 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 847, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 225,
		Pix:    pixX10a0, // 3825 bytes
	},
}

// X0e3f font data, 5278 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 767, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 210,
		Pix:    pixX0e3f, // 4200 bytes
	},
}

// X03c0 font data, 71 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 27 bytes
	},
}

// X03a9 font data, 92 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   12,
	Width: 13,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 13, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixX03a9, // 48 bytes
	},
}

// X0101 font data, 10830 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1940, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX0101, // 10060 bytes
	},
}

// X00a0 font data, 5355 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 924, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 259,
		Pix:    pixX00a0, // 4921 bytes
	},
}

// X0020 font data, 4663 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 882, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 249,
		Pix:    pixX0020, // 4233 bytes
	},
}

// X0000 font data, 72 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   10,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 8, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 2,
		Pix:    pixX0000, // 28 bytes
	},
}
