// DO NOT EDIT
// Generated by: go run 9font.go -samedir -maxbpp 2 -dir 2bpp bit/dejavubd/dejavubd.18.font

package dejavubd18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 178 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 20, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 100 bytes
	},
}

// Xfb00 font data, 1483 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 104, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 27,
		Pix:    pixXfb00, // 405 bytes
	},
}

// Xf6c5 font data, 1197 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 25, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 7,
		Pix:    pixXf6c5, // 119 bytes
	},
}

// Xf400 font data, 3850 bytes, orgbpp: 8
var Xf400 = font9.Variable{
	Info: infoXf400, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 513, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 132,
		Pix:    pixXf400, // 2772 bytes
	},
}

// Xa746 font data, 3300 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 382, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 101,
		Pix:    pixXa746, // 2222 bytes
	},
}

// Xa644 font data, 4403 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 667, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 175,
		Pix:    pixXa644, // 3325 bytes
	},
}

// X2e18 font data, 1265 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 40, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 11,
		Pix:    pixX2e18, // 187 bytes
	},
}

// X2c60 font data, 4966 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 809, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 216,
		Pix:    pixX2c60, // 3888 bytes
	},
}

// X2b00 font data, 2608 bytes, orgbpp: 8
var X2b00 = font9.Variable{
	Info: infoX2b00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 339, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 90,
		Pix:    pixX2b00, // 1530 bytes
	},
}

// X28a2 font data, 10325 bytes, orgbpp: 8
var X28a2 = font9.Variable{
	Info: infoX28a2, // 758 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1890, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX28a2, // 9519 bytes
	},
}

// X27a1 font data, 9638 bytes, orgbpp: 8
var X27a1 = font9.Variable{
	Info: infoX27a1, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1692, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 428,
		Pix:    pixX27a1, // 8560 bytes
	},
}

// X2580 font data, 11030 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 962 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1921, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX2580, // 10020 bytes
	},
}

// X2423 font data, 1106 bytes, orgbpp: 8
var X2423 = font9.Variable{
	Info: infoX2423, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -2},
			Max: image.Point{X: 13, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 4,
		Pix:    pixX2423, // 28 bytes
	},
}

// X1e01 font data, 12267 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 650 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1856, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1e01, // 11569 bytes
	},
}

// X1d00 font data, 8458 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1339, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 369,
		Pix:    pixX1d00, // 7380 bytes
	},
}

// X10a0 font data, 6958 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1058, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 280,
		Pix:    pixX10a0, // 5880 bytes
	},
}

// X0101 font data, 12256 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 662 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1956, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 502,
		Pix:    pixX0101, // 11546 bytes
	},
}

// X0000 font data, 11641 bytes, orgbpp: 8
var X0000 = font9.Variable{
	Info: infoX0000, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 2001, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX0000, // 10563 bytes
	},
}
