// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansbd/dejavusansbd.12.font

package dejavusansbd12

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 274 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 14, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixXfff9, // 196 bytes
	},
}

// Xfe00 font data, 20623 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1292, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1303,
		Pix:    pixXfe00, // 19545 bytes
	},
}

// Xfb00 font data, 22093 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1401, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1401,
		Pix:    pixXfb00, // 21015 bytes
	},
}

// Xf6c5 font data, 1166 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 8, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixXf6c5, // 88 bytes
	},
}

// Xef00 font data, 2248 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 117, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 117,
		Pix:    pixXef00, // 1170 bytes
	},
}

// Xa746 font data, 5503 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 295, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 295,
		Pix:    pixXa746, // 4425 bytes
	},
}

// Xa644 font data, 9619 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 656, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 657,
		Pix:    pixXa644, // 8541 bytes
	},
}

// X4dc0 font data, 7990 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 576, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 576,
		Pix:    pixX4dc0, // 6912 bytes
	},
}

// X2d61 font data, 2062 bytes, orgbpp: 8
var X2d61 = font9.Variable{
	Info: infoX2d61, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 82, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 82,
		Pix:    pixX2d61, // 984 bytes
	},
}

// X2c60 font data, 9827 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 671, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 673,
		Pix:    pixX2c60, // 8749 bytes
	},
}

// X2a84 font data, 9996 bytes, orgbpp: 8
var X2a84 = font9.Variable{
	Info: infoX2a84, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 686, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 686,
		Pix:    pixX2a84, // 8918 bytes
	},
}

// X2983 font data, 5964 bytes, orgbpp: 8
var X2983 = font9.Variable{
	Info: infoX2983, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 349, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 349,
		Pix:    pixX2983, // 4886 bytes
	},
}

// X2580 font data, 31021 bytes, orgbpp: 8
var X2580 = font9.Variable{
	Info: infoX2580, // 898 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 2001, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2005,
		Pix:    pixX2580, // 30075 bytes
	},
}

// X2104 font data, 29062 bytes, orgbpp: 8
var X2104 = font9.Variable{
	Info: infoX2104, // 930 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -11},
			Max: image.Point{X: 2001, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2006,
		Pix:    pixX2104, // 28084 bytes
	},
}

// X2003 font data, 16408 bytes, orgbpp: 8
var X2003 = font9.Variable{
	Info: infoX2003, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1021, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1022,
		Pix:    pixX2003, // 15330 bytes
	},
}

// X1f02 font data, 30208 bytes, orgbpp: 8
var X1f02 = font9.Variable{
	Info: infoX1f02, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1936, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1942,
		Pix:    pixX1f02, // 29130 bytes
	},
}

// X1e01 font data, 30148 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1657, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1938,
		Pix:    pixX1e01, // 29070 bytes
	},
}

// X1d00 font data, 13155 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 926, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 929,
		Pix:    pixX1d00, // 12077 bytes
	},
}

// X1401 font data, 27036 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 858 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1959, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2010,
		Pix:    pixX1401, // 26130 bytes
	},
}

// X10a0 font data, 9853 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 675, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 675,
		Pix:    pixX10a0, // 8775 bytes
	},
}

// X0e3f font data, 9913 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 587, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 589,
		Pix:    pixX0e3f, // 8835 bytes
	},
}

// X0404 font data, 31071 bytes, orgbpp: 8
var X0404 = font9.Variable{
	Info: infoX0404, // 918 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1991, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 2007,
		Pix:    pixX0404, // 30105 bytes
	},
}

// X03c0 font data, 92 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   8,
	Width: 8,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -6},
			Max: image.Point{X: 8, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 8,
		Pix:    pixX03c0, // 48 bytes
	},
}

// X03a9 font data, 134 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   9,
	Width: 10,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 10, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 10,
		Pix:    pixX03a9, // 90 bytes
	},
}

// X0303 font data, 22858 bytes, orgbpp: 8
var X0303 = font9.Variable{
	Info: infoX0303, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1436, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1452,
		Pix:    pixX0303, // 21780 bytes
	},
}

// X0202 font data, 25333 bytes, orgbpp: 8
var X0202 = font9.Variable{
	Info: infoX0202, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1611, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1617,
		Pix:    pixX0202, // 24255 bytes
	},
}

// X0101 font data, 30898 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 1959, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 1988,
		Pix:    pixX0101, // 29820 bytes
	},
}

// X00a0 font data, 11459 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -12},
			Max: image.Point{X: 639, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 735,
		Pix:    pixX00a0, // 11025 bytes
	},
}

// X0020 font data, 9556 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -10},
			Max: image.Point{X: 607, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 702,
		Pix:    pixX0020, // 9126 bytes
	},
}

// X0000 font data, 110 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   7,
	Width: 6,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -8},
			Max: image.Point{X: 6, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 6,
		Pix:    pixX0000, // 66 bytes
	},
}
