// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusansbd/dejavusansbd.12.font

package dejavusansbd12

import "github.com/embeddedgo/display/font/subfont"

const (
	Height = 15
	Ascent = 12
)

// NewFace provides a convenient way to create a font face containing the listed
// subfonts. The returned face is SAFE for concurent use.
func NewFace(subfonts ...*subfont.Subfont) *subfont.Face {
	return &subfont.Face{Height: Height, Ascent: Ascent, Subfonts: subfonts}
}

// Xfff9_ffff subfont, n=7, ￼�
var Xfff9_ffff = &subfont.Subfont{
	First:  0xfff9,
	Last:   0xffff,
	Offset: 0,
	Data:   &Xfff9,
}

// Xfe00_ff00 subfont, n=257, ︀︁︂︃︄︅︆︇︈︉︊︋︌︍︎️︐︑︒︓︔︕︖︗︘︙︧︨︩︪︫︬︭︠︡︢︣︤︥︦︮︯︰︱︲︳︴︵
var Xfe00_ff00 = &subfont.Subfont{
	First:  0xfe00, // '︀'
	Last:   0xff00,
	Offset: 0,
	Data:   &Xfe00,
}

// Xfb00_fc00 subfont, n=257, ﬀﬁﬂﬃﬄﬅﬆﬓﬔﬕﬖﬗיִﬞײַﬠﬡﬢﬣﬤﬥﬦﬧﬨ﬩שׁשׂשּׁשּׂאַאָאּבּגּדּהּוּזּטּיּךּכּלּמּנּסּףּפּ
var Xfb00_fc00 = &subfont.Subfont{
	First:  0xfb00, // 'ﬀ'
	Last:   0xfc00, // 'ﰀ'
	Offset: 0,
	Data:   &Xfb00,
}

// Xf6c5_f7c5 subfont, n=257, 
var Xf6c5_f7c5 = &subfont.Subfont{
	First:  0xf6c5,
	Last:   0xf7c5,
	Offset: 0,
	Data:   &Xf6c5,
}

// Xef00_f000 subfont, n=257, 
var Xef00_f000 = &subfont.Subfont{
	First:  0xef00,
	Last:   0xf000,
	Offset: 0,
	Data:   &Xef00,
}

// Xa746_a846 subfont, n=257, ꝆꝇꝈꝉꝊꝋꝌꝍꝎꝏꝐꝑꝒꝓꝔꝕꝖꝗꝘꝙꝚꝛꝜꝝꝞꝟꝠꝡꝢꝣꝤꝥꝦꝧꝨꝩꝪꝫꝬꝭꝮꝯꝰꝱꝲꝳꝴꝵ
var Xa746_a846 = &subfont.Subfont{
	First:  0xa746, // 'Ꝇ'
	Last:   0xa846, // 'ꡆ'
	Offset: 0,
	Data:   &Xa746,
}

// Xa644_a744 subfont, n=257, ꙄꙅꙆꙇꙈꙉꙊꙋꙌꙍꙎꙏꙐꙑꙒꙓꙔꙕꙖꙗꙘꙙꙚꙛꙜꙝꙞꙟꙠꙡꙢꙣꙤꙥꙦꙧꙨꙩꙪꙫꙬꙭꙮ꙯꙰꙱꙲꙳
var Xa644_a744 = &subfont.Subfont{
	First:  0xa644, // 'Ꙅ'
	Last:   0xa744, // 'Ꝅ'
	Offset: 0,
	Data:   &Xa644,
}

// X4dc0_4ec0 subfont, n=257, ䷀䷁䷂䷃䷄䷅䷆䷇䷈䷉䷊䷋䷌䷍䷎䷏䷐䷑䷒䷓䷔䷕䷖䷗䷘䷙䷚䷛䷜䷝䷞䷟䷠䷡䷢䷣䷤䷥䷦䷧䷨䷩䷪䷫䷬䷭䷮䷯
var X4dc0_4ec0 = &subfont.Subfont{
	First:  0x4dc0, // '䷀'
	Last:   0x4ec0, // '什'
	Offset: 0,
	Data:   &X4dc0,
}

// X2d61_2e61 subfont, n=257, ⵡⵢⵣⵤⵥⵦⵧⵯ⵰⵿ⶀⶁⶂⶃⶄⶅⶆⶇⶈⶉⶊⶋⶌⶍⶎⶏⶐⶑⶒⶓⶔⶕⶖⶠⶡⶢⶣⶤⶥⶦⶨⶩⶪⶫⶬⶭⶮⶰ
var X2d61_2e61 = &subfont.Subfont{
	First:  0x2d61, // 'ⵡ'
	Last:   0x2e61,
	Offset: 0,
	Data:   &X2d61,
}

// X2c60_2d60 subfont, n=257, ⱠⱡⱢⱣⱤⱥⱦⱧⱨⱩⱪⱫⱬⱭⱮⱯⱰⱱⱲⱳⱴⱵⱶⱷⱸⱹⱺⱻⱼⱽⱾⱿⲀⲁⲂⲃⲄⲅⲆⲇⲈⲉⲊⲋⲌⲍⲎⲏ
var X2c60_2d60 = &subfont.Subfont{
	First:  0x2c60, // 'Ⱡ'
	Last:   0x2d60, // 'ⵠ'
	Offset: 0,
	Data:   &X2c60,
}

// X2a84_2b84 subfont, n=257, ⪄⪅⪆⪇⪈⪉⪊⪋⪌⪍⪎⪏⪐⪑⪒⪓⪔⪕⪖⪗⪘⪙⪚⪛⪜⪝⪞⪟⪠⪡⪢⪣⪤⪥⪦⪧⪨⪩⪪⪫⪬⪭⪮⪯⪰⪱⪲⪳
var X2a84_2b84 = &subfont.Subfont{
	First:  0x2a84, // '⪄'
	Last:   0x2b84, // '⮄'
	Offset: 0,
	Data:   &X2a84,
}

// X2983_2a83 subfont, n=257, ⦃⦄⦅⦆⦇⦈⦉⦊⦋⦌⦍⦎⦏⦐⦑⦒⦓⦔⦕⦖⦗⦘⦙⦚⦛⦜⦝⦞⦟⦠⦡⦢⦣⦤⦥⦦⦧⦨⦩⦪⦫⦬⦭⦮⦯⦰⦱⦲
var X2983_2a83 = &subfont.Subfont{
	First:  0x2983, // '⦃'
	Last:   0x2a83, // '⪃'
	Offset: 0,
	Data:   &X2983,
}

// X2580_267f subfont, n=256, ▀▁▂▃▄▅▆▇█▉▊▋▌▍▎▏▐░▒▓▔▕▖▗▘▙▚▛▜▝▞▟■□▢▣▤▥▦▧▨▩▪▫▬▭▮▯
var X2580_267f = &subfont.Subfont{
	First:  0x2580, // '▀'
	Last:   0x267f, // '♿'
	Offset: 0,
	Data:   &X2580,
}

// X2104_2204 subfont, n=257, ℄℅℆ℇ℈℉ℊℋℌℍℎℏℐℑℒℓ℔ℕ№℗℘ℙℚℛℜℝ℞℟℠℡™℣ℤ℥Ω℧ℨ℩KÅℬℭ℮ℯℰℱℲℳ
var X2104_2204 = &subfont.Subfont{
	First:  0x2104, // '℄'
	Last:   0x2204, // '∄'
	Offset: 0,
	Data:   &X2104,
}

// X2003_2103 subfont, n=257, ‐‑‒–—―‖‗‘’‚‛“”„‟†‡•‣․‥…‧‰‱′″‴‵‶‷‸‹›※‼‽‾‿⁀⁁⁂⁃⁄⁅⁆⁇
var X2003_2103 = &subfont.Subfont{
	First:  0x2003,
	Last:   0x2103, // '℃'
	Offset: 0,
	Data:   &X2003,
}

// X1f02_2002 subfont, n=257, ἂἃἄἅἆἇἈἉἊἋἌἍἎἏἐἑἒἓἔἕἘἙἚἛἜἝἠἡἢἣἤἥἦἧἨἩἪἫἬἭἮἯἰἱἲἳἴἵ
var X1f02_2002 = &subfont.Subfont{
	First:  0x1f02, // 'ἂ'
	Last:   0x2002,
	Offset: 0,
	Data:   &X1f02,
}

// X1e01_1f01 subfont, n=257, ḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯḰ
var X1e01_1f01 = &subfont.Subfont{
	First:  0x1e01, // 'ḁ'
	Last:   0x1f01, // 'ἁ'
	Offset: 0,
	Data:   &X1e01,
}

// X1d00_1e00 subfont, n=257, ᴀᴁᴂᴃᴄᴅᴆᴇᴈᴉᴊᴋᴌᴍᴎᴏᴐᴑᴒᴓᴔᴕᴖᴗᴘᴙᴚᴛᴜᴝᴞᴟᴠᴡᴢᴣᴤᴥᴦᴧᴨᴩᴪᴫᴬᴭᴮᴯ
var X1d00_1e00 = &subfont.Subfont{
	First:  0x1d00, // 'ᴀ'
	Last:   0x1e00, // 'Ḁ'
	Offset: 0,
	Data:   &X1d00,
}

// X1401_14e7 subfont, n=231, ᐁᐂᐃᐄᐅᐆᐇᐈᐉᐊᐋᐌᐍᐎᐏᐐᐑᐒᐓᐔᐕᐖᐗᐘᐙᐚᐛᐜᐝᐞᐟᐠᐡᐢᐣᐤᐥᐦᐧᐨᐩᐪᐫᐬᐭᐮᐯᐰ
var X1401_14e7 = &subfont.Subfont{
	First:  0x1401, // 'ᐁ'
	Last:   0x14e7, // 'ᓧ'
	Offset: 0,
	Data:   &X1401,
}

// X10a0_11a0 subfont, n=257, ႠႡႢႣႤႥႦႧႨႩႪႫႬႭႮႯႰႱႲႳႴႵႶႷႸႹႺႻႼႽႾႿჀჁჂჃჄჅჇჍაბგდევზთ
var X10a0_11a0 = &subfont.Subfont{
	First:  0x10a0, // 'Ⴀ'
	Last:   0x11a0, // 'ᆠ'
	Offset: 0,
	Data:   &X10a0,
}

// X0e3f_0f3f subfont, n=257, ฿เแโใไๅๆ็่้๊๋์ํ๎๏๐๑๒๓๔๕๖๗๘๙๚๛ກຂຄຆງຈຉຊຌຍຎຏຐຑຒຓດຕຖ
var X0e3f_0f3f = &subfont.Subfont{
	First:  0x0e3f, // '฿'
	Last:   0x0f3f, // '༿'
	Offset: 0,
	Data:   &X0e3f,
}

// X0404_0504 subfont, n=257, ЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвг
var X0404_0504 = &subfont.Subfont{
	First:  0x0404, // 'Є'
	Last:   0x0504, // 'Ԅ'
	Offset: 0,
	Data:   &X0404,
}

// X03c0_03c0 subfont, n=1, 
var X03c0_03c0 = &subfont.Subfont{
	First:  0x03c0, // 'π'
	Last:   0x03c0, // 'π'
	Offset: 0,
	Data:   &X03c0,
}

// X03a9_03a9 subfont, n=1, 
var X03a9_03a9 = &subfont.Subfont{
	First:  0x03a9, // 'Ω'
	Last:   0x03a9, // 'Ω'
	Offset: 0,
	Data:   &X03a9,
}

// X0303_0403 subfont, n=257, ̡̢̧̨̛̖̗̘̙̜̝̞̟̠̣̤̥̦̩̪̫̬̭̮̯̰̱̲̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̕̚
var X0303_0403 = &subfont.Subfont{
	First:  0x0303, // '̃'
	Last:   0x0403, // 'Ѓ'
	Offset: 0,
	Data:   &X0303,
}

// X0202_0302 subfont, n=257, ȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱ
var X0202_0302 = &subfont.Subfont{
	First:  0x0202, // 'Ȃ'
	Last:   0x0302, // '̂'
	Offset: 0,
	Data:   &X0202,
}

// X0101_0201 subfont, n=257, āĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİ
var X0101_0201 = &subfont.Subfont{
	First:  0x0101, // 'ā'
	Last:   0x0201, // 'ȁ'
	Offset: 0,
	Data:   &X0101,
}

// X00a0_00ff subfont, n=96, ¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑ
var X00a0_00ff = &subfont.Subfont{
	First:  0x00a0,
	Last:   0x00ff, // 'ÿ'
	Offset: 0,
	Data:   &X00a0,
}

// X0020_007e subfont, n=95,  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO
var X0020_007e = &subfont.Subfont{
	First:  0x0020, // ' '
	Last:   0x007e, // '~'
	Offset: 0,
	Data:   &X0020,
}

// X0000_0100 subfont, n=257,  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO
var X0000_0100 = &subfont.Subfont{
	First:  0x0000,
	Last:   0x0100, // 'Ā'
	Offset: 0,
	Data:   &X0000,
}
