// DO NOT EDIT
// Generated by: go run 9font.go -n bit/dejavusansit/dejavusansit.18.font

package dejavusansit18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 173 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 18, Y: 2},
		},
		LogN:   1, // 2 bpp
		Stride: 5,
		Pix:    pixXfff9, // 95 bytes
	},
}

// Xfe00 font data, 1114 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 29, Y: -13},
		},
		LogN:   1, // 2 bpp
		Stride: 9,
		Pix:    pixXfe00, // 36 bytes
	},
}

// Xfb00 font data, 4246 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 659, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 176,
		Pix:    pixXfb00, // 3168 bytes
	},
}

// Xf6c5 font data, 1123 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 10, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixXf6c5, // 45 bytes
	},
}

// Xef00 font data, 1638 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 135, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 40,
		Pix:    pixXef00, // 560 bytes
	},
}

// Xa746 font data, 3241 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 384, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 103,
		Pix:    pixXa746, // 2163 bytes
	},
}

// Xa644 font data, 5506 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 898, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 246,
		Pix:    pixXa644, // 4428 bytes
	},
}

// X4dc0 font data, 4662 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 224,
		Pix:    pixX4dc0, // 3584 bytes
	},
}

// X2e18 font data, 1248 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 35, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 10,
		Pix:    pixX2e18, // 170 bytes
	},
}

// X2c60 font data, 2938 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 335, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 93,
		Pix:    pixX2c60, // 1860 bytes
	},
}

// X1e01 font data, 12281 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 710 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1910, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 501,
		Pix:    pixX1e01, // 11523 bytes
	},
}

// X1d00 font data, 7438 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1157, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 318,
		Pix:    pixX1d00, // 6360 bytes
	},
}

// X1646 font data, 2047 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 219, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 57,
		Pix:    pixX1646, // 969 bytes
	},
}

// X1401 font data, 9221 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 622 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1787, Y: 1},
		},
		LogN:   1, // 2 bpp
		Stride: 503,
		Pix:    pixX1401, // 8551 bytes
	},
}

// X10a0 font data, 5486 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 876, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 232,
		Pix:    pixX10a0, // 4408 bytes
	},
}

// X0e3f font data, 5434 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 714, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 198,
		Pix:    pixX0e3f, // 4356 bytes
	},
}

// X03c0 font data, 71 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03c0, // 27 bytes
	},
}

// X03a9 font data, 83 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  -1,
	Adv:   14,
	Width: 12,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 12, Y: 0},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX03a9, // 39 bytes
	},
}

// X0101 font data, 11858 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1922, Y: 5},
		},
		LogN:   1, // 2 bpp
		Stride: 504,
		Pix:    pixX0101, // 11088 bytes
	},
}

// X00a0 font data, 5936 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 930, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 262,
		Pix:    pixX00a0, // 5502 bytes
	},
}

// X0020 font data, 4984 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 897, Y: 4},
		},
		LogN:   1, // 2 bpp
		Stride: 253,
		Pix:    pixX0020, // 4554 bytes
	},
}

// X0000 font data, 92 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   1, // 2 bpp
		Stride: 3,
		Pix:    pixX0000, // 48 bytes
	},
}
