// DO NOT EDIT
// Generated by: go run 9font.go -samedir bit/dejavusansit/dejavusansit.18.font

package dejavusansit18

import (
	"image"

	"github.com/embeddedgo/display/font/subfont/font9"
	"github.com/embeddedgo/display/images"
)

// Xfff9 font data, 439 bytes, orgbpp: 8
var Xfff9 = font9.Variable{
	Info: infoXfff9, // 30 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 19, Y: 2},
		},
		LogN:   3, // 8 bpp
		Stride: 19,
		Pix:    pixXfff9, // 361 bytes
	},
}

// Xfe00 font data, 1218 bytes, orgbpp: 8
var Xfe00 = font9.Variable{
	Info: infoXfe00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 33, Y: -13},
		},
		LogN:   3, // 8 bpp
		Stride: 35,
		Pix:    pixXfe00, // 140 bytes
	},
}

// Xfb00 font data, 13732 bytes, orgbpp: 8
var Xfb00 = font9.Variable{
	Info: infoXfb00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 694, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 703,
		Pix:    pixXfb00, // 12654 bytes
	},
}

// Xf6c5 font data, 1243 bytes, orgbpp: 8
var Xf6c5 = font9.Variable{
	Info: infoXf6c5, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 11, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixXf6c5, // 165 bytes
	},
}

// Xef00 font data, 3304 bytes, orgbpp: 8
var Xef00 = font9.Variable{
	Info: infoXef00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 156, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 159,
		Pix:    pixXef00, // 2226 bytes
	},
}

// Xa746 font data, 9730 bytes, orgbpp: 8
var Xa746 = font9.Variable{
	Info: infoXa746, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 409, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 412,
		Pix:    pixXa746, // 8652 bytes
	},
}

// Xa644 font data, 18790 bytes, orgbpp: 8
var Xa644 = font9.Variable{
	Info: infoXa644, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 972, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 984,
		Pix:    pixXa644, // 17712 bytes
	},
}

// X4dc0 font data, 15414 bytes, orgbpp: 8
var X4dc0 = font9.Variable{
	Info: infoX4dc0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 896, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 896,
		Pix:    pixX4dc0, // 14336 bytes
	},
}

// X2e18 font data, 1741 bytes, orgbpp: 8
var X2e18 = font9.Variable{
	Info: infoX2e18, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 39, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 39,
		Pix:    pixX2e18, // 663 bytes
	},
}

// X2c60 font data, 8498 bytes, orgbpp: 8
var X2c60 = font9.Variable{
	Info: infoX2c60, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 367, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 371,
		Pix:    pixX2c60, // 7420 bytes
	},
}

// X1e01 font data, 46827 bytes, orgbpp: 8
var X1e01 = font9.Variable{
	Info: infoX1e01, // 710 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -18},
			Max: image.Point{X: 1946, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2003,
		Pix:    pixX1e01, // 46069 bytes
	},
}

// X1d00 font data, 26458 bytes, orgbpp: 8
var X1d00 = font9.Variable{
	Info: infoX1d00, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 1258, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 1269,
		Pix:    pixX1d00, // 25380 bytes
	},
}

// X1646 font data, 4954 bytes, orgbpp: 8
var X1646 = font9.Variable{
	Info: infoX1646, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 226, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 228,
		Pix:    pixX1646, // 3876 bytes
	},
}

// X1401 font data, 34874 bytes, orgbpp: 8
var X1401 = font9.Variable{
	Info: infoX1401, // 622 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -16},
			Max: image.Point{X: 1919, Y: 1},
		},
		LogN:   3, // 8 bpp
		Stride: 2012,
		Pix:    pixX1401, // 34204 bytes
	},
}

// X10a0 font data, 18691 bytes, orgbpp: 8
var X10a0 = font9.Variable{
	Info: infoX10a0, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -15},
			Max: image.Point{X: 925, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 927,
		Pix:    pixX10a0, // 17613 bytes
	},
}

// X0e3f font data, 18502 bytes, orgbpp: 8
var X0e3f = font9.Variable{
	Info: infoX0e3f, // 1030 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 755, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 792,
		Pix:    pixX0e3f, // 17424 bytes
	},
}

// X03c0 font data, 143 bytes, orgbpp: 8
var X03c0 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 11,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -9},
			Max: image.Point{X: 11, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 11,
		Pix:    pixX03c0, // 99 bytes
	},
}

// X03a9 font data, 226 bytes, orgbpp: 8
var X03a9 = font9.Fixed{
	Left:  0,
	Adv:   14,
	Width: 14,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 14, Y: 0},
		},
		LogN:   3, // 8 bpp
		Stride: 14,
		Pix:    pixX03a9, // 182 bytes
	},
}

// X0101 font data, 45056 bytes, orgbpp: 8
var X0101 = font9.Variable{
	Info: infoX0101, // 722 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 1991, Y: 5},
		},
		LogN:   3, // 8 bpp
		Stride: 2013,
		Pix:    pixX0101, // 44286 bytes
	},
}

// X00a0 font data, 22379 bytes, orgbpp: 8
var X00a0 = font9.Variable{
	Info: infoX00a0, // 386 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -17},
			Max: image.Point{X: 945, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1045,
		Pix:    pixX00a0, // 21945 bytes
	},
}

// X0020 font data, 18628 bytes, orgbpp: 8
var X0020 = font9.Variable{
	Info: infoX0020, // 382 bytes
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -14},
			Max: image.Point{X: 913, Y: 4},
		},
		LogN:   3, // 8 bpp
		Stride: 1011,
		Pix:    pixX0020, // 18198 bytes
	},
}

// X0000 font data, 188 bytes, orgbpp: 8
var X0000 = font9.Fixed{
	Left:  0,
	Adv:   11,
	Width: 9,
	Bits: &images.ImmAlphaN{
		Rect: image.Rectangle{
			Min: image.Point{X: 0, Y: -13},
			Max: image.Point{X: 9, Y: 3},
		},
		LogN:   3, // 8 bpp
		Stride: 9,
		Pix:    pixX0000, // 144 bytes
	},
}
